Repository Azure/azure-sdk-for-cpp, pull requests merged in 2020-09, with the labels that each got.

#559 Sync eng/common directory with azure-sdk-tools for PR 935
  eng/common/scripts/SemVer.ps1
Labels: EngSys

#547 Sync eng/common directory with azure-sdk-tools for PR 916
  eng/common/pipelines/templates/steps/get-pr-owners.yml
  eng/common/scripts/get-codeowners.ps1
Labels: EngSys

#549 Sync eng/common directory with azure-sdk-tools for PR 930
  eng/common/README.md
Labels: EngSys

#572 Use version.hpp for package versions
  CMakeLists.txt
  cmake-modules/az_version.cmake
  eng/Update-PkgVersion.ps1
  eng/pipelines/templates/jobs/archetype-sdk-client.yml
  eng/pipelines/templates/stages/archetype-cpp-release.yml
  eng/scripts/Get-PkgVersion.ps1
  eng/scripts/SdkVersion-Common.ps1
  eng/scripts/Update-PkgVersion.ps1
  sdk/core/azure-core/CMakeLists.txt
  sdk/core/azure-core/version.txt
  sdk/storage/azure-storage-blobs/CMakeLists.txt
  sdk/storage/azure-storage-blobs/version.txt
  sdk/storage/azure-storage-common/CMakeLists.txt
  sdk/storage/azure-storage-common/version.txt
  sdk/storage/azure-storage-files-datalake/CMakeLists.txt
  sdk/storage/azure-storage-files-datalake/version.txt
  sdk/storage/azure-storage-files-shares/CMakeLists.txt
  sdk/template/azure-template/CHANGELOG.md
  sdk/template/azure-template/CMakeLists.txt
Labels: EngSys

#578 Sync eng/common directory with azure-sdk-tools for PR 946
  eng/common/Update-Change-Log.ps1
Labels: EngSys

#586 Sync eng/common directory with azure-sdk-tools for PR 955
  eng/common/Update-Change-Log.ps1
Labels: EngSys

#576 Add docs.microsoft.com artifact generation
  cmake-modules/doxygen_common.cmake
  eng/pipelines/templates/jobs/archetype-sdk-client.yml
  eng/scripts/New-DocsMsArtifact.ps1
Labels: EngSys

#583 reuse code from tolower char
  sdk/core/azure-core/src/strings.cpp
  sdk/core/azure-core/test/ut/string.cpp
Labels: Azure.Core

#568 [Storage Files Service] File sas
  sdk/storage/azure-storage-blobs/inc/azure/storage/blobs/blob_sas_builder.hpp
  sdk/storage/azure-storage-common/inc/azure/storage/common/storage_credential.hpp
  sdk/storage/azure-storage-files-shares/CMakeLists.txt
  sdk/storage/azure-storage-files-shares/inc/azure/storage/files/shares/share_sas_builder.hpp
  sdk/storage/azure-storage-files-shares/src/share_sas_builder.cpp
  sdk/storage/azure-storage-files-shares/test/share_sas_test.cpp
Labels: Client, Storage

#582 [Storage Blobs Service] Blob Batch
  sdk/storage/azure-storage-blobs/CMakeLists.txt
  sdk/storage/azure-storage-blobs/inc/azure/storage/blobs/blob.hpp
  sdk/storage/azure-storage-blobs/inc/azure/storage/blobs/blob_batch_client.hpp
  sdk/storage/azure-storage-blobs/inc/azure/storage/blobs/blob_container_client.hpp
  sdk/storage/azure-storage-blobs/inc/azure/storage/blobs/blob_options.hpp
  sdk/storage/azure-storage-blobs/inc/azure/storage/blobs/blob_service_client.hpp
  sdk/storage/azure-storage-blobs/src/blob_batch_client.cpp
  sdk/storage/azure-storage-blobs/test/blob_batch_client_test.cpp
Labels: Client, Storage

#416 [Storage Blobs Service] Blob Tags
  sdk/storage/azure-storage-blobs/inc/azure/storage/blobs/blob_client.hpp
  sdk/storage/azure-storage-blobs/inc/azure/storage/blobs/blob_options.hpp
  sdk/storage/azure-storage-blobs/inc/azure/storage/blobs/blob_responses.hpp
  sdk/storage/azure-storage-blobs/inc/azure/storage/blobs/blob_service_client.hpp
  sdk/storage/azure-storage-blobs/inc/azure/storage/blobs/protocol/blob_rest_client.hpp
  sdk/storage/azure-storage-blobs/src/append_blob_client.cpp
  sdk/storage/azure-storage-blobs/src/blob_client.cpp
  sdk/storage/azure-storage-blobs/src/blob_service_client.cpp
  sdk/storage/azure-storage-blobs/src/block_blob_client.cpp
  sdk/storage/azure-storage-blobs/src/page_blob_client.cpp
  sdk/storage/azure-storage-blobs/test/blob_container_client_test.cpp
  sdk/storage/azure-storage-blobs/test/blob_sas_test.cpp
Labels: Client, Storage

#597 fix bug in file sas
  sdk/storage/azure-storage-files-shares/src/share_sas_builder.cpp
Labels: Client, Storage, blocking-release, bug

#546 Sync eng/common directory with azure-sdk-tools for PR 926
  eng/common/Update-Change-Log.ps1
  eng/common/pipelines/templates/steps/publish-blobs.yml
  eng/common/scripts/artifact-metadata-parsing.ps1
  eng/common/scripts/copy-docs-to-blobstorage.ps1
  eng/common/scripts/update-docs-metadata.ps1
Labels: EngSys

#553 Sync eng/common directory with azure-sdk-tools for PR 823
  eng/common/pipelines/templates/steps/verify-changelog.yml
  eng/common/scripts/Package-Properties.ps1
  eng/common/scripts/Verify-ChangeLog.ps1
  eng/common/scripts/common.ps1
Labels: EngSys

#579 Generate Doc Index
  eng/docs/index/Generate-DocIndex.ps1
  eng/docs/index/docfx.json
  eng/docs/index/templates/matthews/styles/main.js
Labels: EngSys

#606 Sync eng/common directory with azure-sdk-tools repository
  eng/common/Update-Change-Log.ps1
Labels: EngSys

#610 Fix typo in comment within request.cpp
  sdk/core/azure-core/src/http/request.cpp
Labels: Azure.Core

#607 Sync eng/common directory with azure-sdk-tools for PR 969
  eng/common/README.md
Labels: EngSys

#611 Add doxygen comments
  sdk/core/azure-core/inc/azure/core/azure.hpp
  sdk/core/azure-core/inc/azure/core/context.hpp
  sdk/core/azure-core/inc/azure/core/credentials/credentials.hpp
  sdk/core/azure-core/inc/azure/core/credentials/policy/policies.hpp
  sdk/core/azure-core/inc/azure/core/http/body_stream.hpp
  sdk/core/azure-core/inc/azure/core/http/curl/curl.hpp
  sdk/core/azure-core/inc/azure/core/http/http.hpp
  sdk/core/azure-core/inc/azure/core/http/pipeline.hpp
  sdk/core/azure-core/inc/azure/core/http/policy.hpp
  sdk/core/azure-core/inc/azure/core/http/transport.hpp
  sdk/core/azure-core/inc/azure/core/http/winhttp/win_http_client.hpp
  sdk/core/azure-core/inc/azure/core/logging/logging.hpp
  sdk/core/azure-core/inc/azure/core/nullable.hpp
  sdk/core/azure-core/inc/azure/core/response.hpp
  sdk/core/azure-core/inc/azure/core/uuid.hpp
  sdk/core/azure-core/inc/azure/core/version.hpp
Labels: Azure.Core, Docs

#613 disable blob tags ut
  sdk/storage/azure-storage-blobs/test/blob_container_client_test.cpp
  sdk/storage/azure-storage-blobs/test/blob_sas_test.cpp
  sdk/storage/azure-storage-blobs/test/blob_service_client_test.cpp
Labels: Client, Storage, blocking-release, test enhancement

#615 [Storage Blobs Service] update changelog
  sdk/storage/azure-storage-blobs/CHANGELOG.md
  sdk/storage/azure-storage-common/CHANGELOG.md
  sdk/storage/azure-storage-files-datalake/CHANGELOG.md
  sdk/storage/azure-storage-files-shares/CHANGELOG.md
Labels: Client, Storage, blocking-release

#637 Add date in Changelog
  sdk/storage/azure-storage-blobs/CHANGELOG.md
  sdk/storage/azure-storage-common/CHANGELOG.md
  sdk/storage/azure-storage-files-datalake/CHANGELOG.md
  sdk/storage/azure-storage-files-shares/CHANGELOG.md
Labels: Client, Storage

#638 Sync eng/common directory with azure-sdk-tools for PR 982
  eng/common/scripts/artifact-metadata-parsing.ps1
Labels: EngSys

#621 Add parameters to function
  eng/scripts/Language-Settings.ps1
Labels: EngSys

#602 Sync eng/common directory with azure-sdk-tools for PR 965
  eng/common/pipelines/templates/steps/docs-metadata-release.yml
Labels: EngSys

#618 Sync eng/common directory with azure-sdk-tools for PR 973
  eng/common/scripts/update-docs-metadata.ps1
Labels: EngSys

#502 Add support for g++ 8 and 9
  eng/pipelines/templates/jobs/archetype-sdk-client.yml
Labels: EngSys

#653 [Storage Blobs Service] fix bug in blob tags
  sdk/storage/azure-storage-blobs/inc/azure/storage/blobs/blob_options.hpp
  sdk/storage/azure-storage-blobs/test/blob_container_client_test.cpp
Labels: Client, Storage, bug

#648 Allow skip publish DocMS or Github IO for each artifact
  eng/pipelines/templates/stages/archetype-cpp-release.yml
Labels: EngSys

#661 Sync eng/common directory with azure-sdk-tools for PR 999
  eng/common/scripts/update-docs-metadata.ps1
Labels: EngSys

#662 Sync eng/common directory with azure-sdk-tools for PR 1000
  eng/common/pipelines/templates/steps/create-pull-request.yml
  eng/common/pipelines/templates/steps/create-tags-and-git-release.yml
  eng/common/pipelines/templates/steps/docs-metadata-release.yml
  eng/common/pipelines/templates/steps/replace-relative-links.yml
Labels: EngSys

#655 [Storage Blob Service] Fix bug: encode blob name
  sdk/storage/azure-storage-blobs/src/blob_client.cpp
  sdk/storage/azure-storage-blobs/src/blob_container_client.cpp
Labels: Client, Storage, bug

#620 Sync eng/common directory with azure-sdk-tools for PR 974
  eng/common/scripts/common.ps1
  eng/common/scripts/logging.ps1
Labels: EngSys

#619 Sync eng/common directory with azure-sdk-tools for PR 895
  eng/common/TestResources/New-TestResources.ps1.md
  eng/common/TestResources/README.md
  eng/common/TestResources/Remove-TestResources.ps1.md
  eng/common/pipelines/templates/steps/verify-links.yml
  eng/common/scripts/Verify-Links.ps1
Labels: EngSys

#645 Vcpkg publish framework
  eng/common/scripts/New-ReleaseAsset.ps1
  eng/pipelines/templates/jobs/archetype-sdk-client.yml
  eng/pipelines/templates/stages/archetype-cpp-release.yml
  eng/scripts/Initialize-VcpkgRelease.ps1
  eng/scripts/New-ReleaseArtifact.ps1
  eng/scripts/New-VcpkgPortDefinition.ps1
  sdk/template/azure-template/CHANGELOG.md
  sdk/template/azure-template/inc/azure/template/version.hpp
  sdk/template/azure-template/vcpkg/CONTROL.template
  sdk/template/azure-template/vcpkg/README.md
  sdk/template/azure-template/vcpkg/portfile.cmake.template
Labels: EngSys

#667 Update CODEOWNERS
  .github/CODEOWNERS
Labels: EngSys

#632 Enable master link replacement feature for cpp
  eng/pipelines/templates/stages/archetype-cpp-release.yml
  sdk/template/azure-template/CHANGELOG.md
Labels: EngSys

#668 Replaced relative link with absolute links and remove locale
  README.md
  SECURITY.md
  eng/pipelines/templates/jobs/archetype-sdk-client.yml
  samples/README.md
  sdk/core/azure-core/README.md
  sdk/core/performance-stress/README.md
  sdk/storage/README.md
  sdk/template/azure-template/README.md
Labels: EngSys

#673 Mention VCPKG_DEFAULT_TRIPLET in Build instruction
  CONTRIBUTING.md
Labels: customer-reported

#670 Sync eng/common directory with azure-sdk-tools for PR 1022
  eng/common/scripts/New-ReleaseAsset.ps1
  eng/common/scripts/copy-docs-to-blobstorage.ps1
Labels: Central-EngSys, EngSys

#647 Sync eng/common directory with azure-sdk-tools for PR 989
  eng/common/pipelines/templates/steps/create-pull-request.yml
  eng/common/scripts/Submit-PullRequest.ps1
  eng/common/scripts/add-pullrequest-reviewers.ps1
  eng/common/scripts/get-pr-creator.ps1
Labels: Central-EngSys, EngSys

#680 Sync eng/common directory with azure-sdk-tools for PR 1041
  eng/common/pipelines/templates/steps/create-pull-request.yml
  eng/common/scripts/Submit-PullRequest.ps1
  eng/common/scripts/add-pullrequest-reviewers.ps1
  eng/common/scripts/get-pr-creator.ps1
Labels: EngSys

#682 Add cgmanifest and NOTICE file to template project
  sdk/template/azure-template/NOTICE.txt
  sdk/template/azure-template/cgmanifest.json
Labels: Client, EngSys, auto-merge

#674 Sync eng/common directory with azure-sdk-tools for PR 1029
  eng/common/TestResources/deploy-test-resources.yml
Labels: Central-EngSys, EngSys

#685 Standardize header includes
  sdk/core/azure-core/inc/azure/core/azure.hpp
  sdk/core/azure-core/inc/azure/core/credentials/policy/policies.hpp
  sdk/core/azure-core/inc/azure/core/http/body_stream.hpp
  sdk/core/azure-core/inc/azure/core/response.hpp
  sdk/core/azure-core/src/context.cpp
  sdk/core/azure-core/src/credentials/credentials.cpp
  sdk/core/azure-core/src/credentials/policy/policies.cpp
  sdk/core/azure-core/src/http/body_stream.cpp
  sdk/core/azure-core/src/http/logging_policy.cpp
  sdk/core/azure-core/src/http/policy.cpp
  sdk/core/azure-core/src/http/raw_response.cpp
  sdk/core/azure-core/src/http/request.cpp
  sdk/core/azure-core/src/http/retry_policy.cpp
  sdk/core/azure-core/src/http/telemetry_policy.cpp
  sdk/core/azure-core/src/http/transport_policy.cpp
  sdk/core/azure-core/src/strings.cpp
  sdk/core/azure-core/test/e2e/azure_core_storage_list_containers_sample.cpp
  sdk/core/azure-core/test/e2e/azure_core_storage_test_sample.cpp
  sdk/core/azure-core/test/e2e/azure_core_with_curl_bodyBuffer.cpp
  sdk/core/azure-core/test/e2e/azure_core_with_curl_bodyStream.cpp
  sdk/core/azure-core/test/ut/context.cpp
  sdk/core/azure-core/test/ut/http.cpp
  sdk/core/azure-core/test/ut/http.hpp
  sdk/core/azure-core/test/ut/transport_adapter_file_upload.cpp
  sdk/template/azure-template/src/template_client.cpp
Labels: Azure.Core, Client

#688 Pin the google test version
  cmake-modules/AddGoogleTest.cmake
Labels: Azure.Core, Client

#689 fix variable casing
  sdk/storage/azure-storage-blobs/inc/azure/storage/blobs/blob_options.hpp
  sdk/storage/azure-storage-blobs/src/blob_client.cpp
  sdk/storage/azure-storage-blobs/src/blob_container_client.cpp
  sdk/storage/azure-storage-blobs/test/blob_container_client_test.cpp
  sdk/storage/azure-storage-blobs/test/page_blob_client_test.cpp
  sdk/storage/azure-storage-files-datalake/test/datalake_path_client_test.cpp
Labels: Client, Storage, blocking-release

#654 Response<T> stores Nullable<T>
  sdk/core/azure-core/inc/azure/core/nullable.hpp
  sdk/core/azure-core/inc/azure/core/response.hpp
Labels: Azure.Core, Client, feature-request

#686 Perf fix windows
  sdk/core/azure-core/inc/azure/core/http/curl/curl.hpp
  sdk/core/azure-core/inc/azure/core/http/policy.hpp
  sdk/core/azure-core/src/http/curl/curl.cpp
  sdk/core/azure-core/src/http/policy.cpp
  sdk/core/azure-core/test/e2e/CMakeLists.txt
  sdk/core/azure-core/test/e2e/azure_hang.cpp
Labels: Azure.Core, Client, bug

#652 [Storage Blobs Service] STG 74 features
  sdk/storage/azure-storage-blobs/inc/azure/storage/blobs/protocol/blob_rest_client.hpp
  sdk/storage/azure-storage-blobs/src/blob_sas_builder.cpp
  sdk/storage/azure-storage-blobs/test/blob_container_client_test.cpp
  sdk/storage/azure-storage-blobs/test/blob_sas_test.cpp
  sdk/storage/azure-storage-blobs/test/block_blob_client_test.cpp
  sdk/storage/azure-storage-common/inc/azure/storage/common/constants.hpp
  sdk/storage/azure-storage-common/inc/azure/storage/common/storage_credential.hpp
  sdk/storage/azure-storage-files-datalake/CMakeLists.txt
  sdk/storage/azure-storage-files-datalake/inc/azure/storage/files/datalake/datalake_responses.hpp
  sdk/storage/azure-storage-files-datalake/inc/azure/storage/files/datalake/datalake_sas_builder.hpp
  sdk/storage/azure-storage-files-datalake/src/datalake_sas_builder.cpp
  sdk/storage/azure-storage-files-datalake/test/datalake_sas_test.cpp
Labels: Client, Storage

#588 [Storage Common] Storage Retry Policy
  sdk/storage/azure-storage-blobs/CMakeLists.txt
  sdk/storage/azure-storage-blobs/inc/azure/storage/blobs/blob_options.hpp
  sdk/storage/azure-storage-blobs/src/blob_batch_client.cpp
  sdk/storage/azure-storage-blobs/src/blob_client.cpp
  sdk/storage/azure-storage-blobs/src/blob_container_client.cpp
  sdk/storage/azure-storage-blobs/src/blob_service_client.cpp
  sdk/storage/azure-storage-blobs/test/blob_service_client_test.cpp
  sdk/storage/azure-storage-blobs/test/storage_retry_policy_test.cpp
  sdk/storage/azure-storage-common/CMakeLists.txt
  sdk/storage/azure-storage-common/inc/azure/storage/common/storage_retry_policy.hpp
  sdk/storage/azure-storage-common/src/storage_retry_policy.cpp
  sdk/storage/azure-storage-common/test/test_base.cpp
  sdk/storage/azure-storage-common/test/test_base.hpp
Labels: Client, Storage

#694 Sync eng/common directory with azure-sdk-tools for PR 1056
  eng/common/scripts/Submit-PullRequest.ps1
Labels: EngSys

#695 Sync eng/common directory with azure-sdk-tools for PR 1059
  eng/common/README.md
Labels: Central-EngSys, EngSys

#675 Sync eng/common directory with azure-sdk-tools for PR 1032
  eng/common/TestResources/New-TestResources.ps1
  eng/common/TestResources/New-TestResources.ps1.md
  eng/common/TestResources/Remove-TestResources.ps1
  eng/common/TestResources/deploy-test-resources.yml
  eng/common/TestResources/setup-az-modules.yml
Labels: Central-EngSys, EngSys

#699 Sync eng/common directory with azure-sdk-tools for PR 1061
  eng/common/scripts/logging.ps1
Labels: Central-EngSys, EngSys
