Repository Azure/azure-sdk-for-cpp, pull requests merged in 2021-12, with the labels that each got.

#3122 Sync eng/common directory with azure-sdk-tools for PR 2248
  eng/common/TestResources/New-TestResources.ps1
  eng/common/TestResources/SubConfig-Helpers.ps1
  eng/common/TestResources/build-test-resource-config.yml
Labels: EngSys, Central-EngSys

#3145 Sync eng/common directory with azure-sdk-tools for PR 2352
  eng/common/pipelines/templates/steps/check-spelling.yml
  eng/common/scripts/check-spelling-in-changed-files.ps1
  eng/common/spelling/Invoke-Cspell.ps1
  eng/common/spelling/package-lock.json
  eng/common/spelling/package.json
Labels: EngSys, Central-EngSys

#3123 Boost code coverage by adding tests
  sdk/core/azure-core/test/ut/curl_session_test_test.cpp
  sdk/core/azure-core/test/ut/etag_test.cpp
  sdk/core/azure-core/test/ut/nullable_test.cpp
  sdk/core/azure-core/test/ut/url_test.cpp
  sdk/core/ci.yml
  sdk/identity/azure-identity/test/ut/CMakeLists.txt
  sdk/identity/azure-identity/test/ut/client_secret_credential_test.cpp
  sdk/identity/azure-identity/test/ut/environment_credential_test.cpp
  sdk/identity/azure-identity/test/ut/managed_identity_credential_test.cpp
  sdk/identity/azure-identity/test/ut/token_credential_impl_test.cpp
  sdk/identity/ci.yml
Labels: MQ

#3153 Sync eng/common directory with azure-sdk-tools for PR 2372
  eng/common/TestResources/New-TestResources.ps1
Labels: EngSys, Central-EngSys

#3155 Sync eng/common directory with azure-sdk-tools for PR 2380
  eng/common/scripts/Verify-Readme.ps1
Labels: EngSys, Central-EngSys

#3158 Sync eng/common directory with azure-sdk-tools for PR 2327
  eng/common/pipelines/templates/steps/update-docsms-metadata.yml
  eng/common/scripts/Update-DocsMsMetadata.ps1
  eng/common/scripts/common.ps1
Labels: EngSys, Central-EngSys

#3162 Sync eng/common directory with azure-sdk-tools for PR 2381
  eng/common/pipelines/templates/steps/write-filesystemmetrics.yml
  eng/common/scripts/Write-FileSystemMetrics.ps1
Labels: EngSys, Central-EngSys

#3159 Sync eng/common directory with azure-sdk-tools for PR 2363
  eng/common/TestResources/New-TestResources.ps1
  eng/common/TestResources/New-TestResources.ps1.md
  eng/common/scripts/stress-testing/deploy-stress-tests.ps1
  eng/common/scripts/stress-testing/stress-test-deployment-lib.ps1
Labels: EngSys, Central-EngSys

#3166 Sync eng/common directory with azure-sdk-tools for PR 2393
  eng/common/scripts/Update-DocsMsPackages.ps1
Labels: EngSys, Central-EngSys

#3154 Update vcpkg and dependencies to the newer commit sha from 11-10-2021, after last SDK release
  eng/vcpkg-commit.txt
  sdk/storage/azure-storage-common/CMakeLists.txt
Labels: MQ

#3170 Sync eng/common directory with azure-sdk-tools for PR 2402
  eng/common/scripts/Invoke-GitHubAPI.ps1
Labels: EngSys, Central-EngSys

#3171 Sync eng/common directory with azure-sdk-tools for PR 2408
  eng/common/scripts/stress-testing/find-all-stress-packages.ps1
  eng/common/scripts/stress-testing/stress-test-deployment-lib.ps1
Labels: EngSys, Central-EngSys

#3173 Sync eng/common directory with azure-sdk-tools for PR 2412
  eng/common/TestResources/New-TestResources.ps1
Labels: EngSys, Central-EngSys, auto-merge

#3175 Sync eng/common directory with azure-sdk-tools for PR 2415
  eng/common/scripts/Update-DocsMsMetadata.ps1
Labels: EngSys, Central-EngSys

#3176 Sync eng/common directory with azure-sdk-tools for PR 2417
  eng/common/pipelines/templates/steps/verify-readme.yml
  eng/common/scripts/Verify-Readme.ps1
Labels: EngSys, Central-EngSys

#3178 Remove static libcurl transport
  sdk/core/azure-core/CMakeLists.txt
  sdk/core/azure-core/src/http/curl/static_curl.cpp
  sdk/core/azure-core/src/http/curl/static_curl_transport.hpp
Labels: Azure.Core, MQ

#3177 Fix DateTime::Parse validation for dates past year 9999 due to adjustments
  sdk/core/azure-core/CHANGELOG.md
  sdk/core/azure-core/src/datetime.cpp
  sdk/core/azure-core/test/ut/datetime_test.cpp
Labels: Azure.Core, MQ

#3163 Add a few simple unit tests to boost coverage
  sdk/core/azure-core/src/http/curl/curl.cpp
  sdk/core/azure-core/src/http/curl/curl_connection_private.hpp
  sdk/core/azure-core/test/ut/CMakeLists.txt
  sdk/core/azure-core/test/ut/curl_connection_pool_test.cpp
  sdk/core/azure-core/test/ut/datetime_test.cpp
  sdk/core/azure-core/test/ut/environment_log_level_listener_test.cpp
  sdk/core/azure-core/test/ut/exception_test.cpp
  sdk/core/azure-core/test/ut/log_policy_test.cpp
  sdk/core/azure-core/test/ut/pipeline_test.cpp
  sdk/core/azure-core/test/ut/retry_policy_test.cpp
  sdk/core/azure-core/test/ut/sha_test.cpp
  sdk/core/azure-core/test/ut/url_test.cpp
  sdk/core/ci.yml
Labels: Azure.Core, MQ

#3179 Exclude uncoverable lines from code coverage
  sdk/core/azure-core/src/azure_assert.cpp
  sdk/core/azure-core/src/datetime.cpp
  sdk/identity/azure-identity/src/managed_identity_credential.cpp
  sdk/identity/ci.yml
Labels: MQ

#3183 Sync eng/common directory with azure-sdk-tools for PR 2442
  eng/common/scripts/Invoke-GitHubAPI.ps1
Labels: EngSys, Central-EngSys

#3190 Fix nightly tests compilation on GCC5
  sdk/core/azure-core/test/ut/retry_policy_test.cpp
Labels: Azure.Core, test-enhancement, test-reliability

#3187 Sync eng/common directory with azure-sdk-tools for PR 2447
  eng/common/scripts/stress-testing/stress-test-deployment-lib.ps1
Labels: EngSys, Central-EngSys

#3198 Make Template to pass the default goals set for code coverage
  sdk/template/azure-template/inc/azure/template/template_client.hpp
  sdk/template/azure-template/src/template_client.cpp
  sdk/template/azure-template/test/ut/template_test.cpp
  sdk/template/ci.yml
Labels: EngSys, MQ

#3197 Do not mix inline and non-inline delegating constructors in polymorphic types
  sdk/identity/azure-identity/CHANGELOG.md
  sdk/identity/azure-identity/inc/azure/identity/client_secret_credential.hpp
  sdk/identity/azure-identity/inc/azure/identity/managed_identity_credential.hpp
  sdk/identity/azure-identity/src/client_secret_credential.cpp
  sdk/identity/azure-identity/src/managed_identity_credential.cpp
Labels: Azure.Identity, MQ

#3200 Add trademark section to readme
  README.md
Labels: auto-merge

#3201 RequestFailedException: decouple Message and what().
  sdk/core/azure-core/inc/azure/core/context.hpp
  sdk/core/azure-core/inc/azure/core/credentials/credentials.hpp
  sdk/core/azure-core/inc/azure/core/exception.hpp
  sdk/core/azure-core/inc/azure/core/http/http.hpp
  sdk/core/azure-core/src/exception.cpp
  sdk/core/azure-core/test/ut/exception_test.cpp
  sdk/storage/azure-storage-common/inc/azure/storage/common/storage_exception.hpp
Labels: Azure.Core, MQ
