Repository Azure/azure-sdk-for-cpp, pull requests merged in 2021-11, with the labels that each got.

#3007 Testing KeyVault live test runs to reproduce errors and disable test to unblock CI
  sdk/keyvault/azure-security-keyvault-certificates/test/ut/certificate_client_test.cpp
Labels: test-enhancement, KeyVault, auto-merge, test-manual-pass

#3016 Sync eng/common directory with azure-sdk-tools for PR 2177
  eng/common/scripts/Invoke-GitHubAPI.ps1
Labels: EngSys, Central-EngSys

#3019 Sync eng/common directory with azure-sdk-tools for PR 2203
  eng/common/pipelines/templates/steps/sparse-checkout.yml
Labels: EngSys, Central-EngSys

#3020 Sync eng/common directory with azure-sdk-tools for PR 2179
  eng/common/pipelines/templates/steps/docker-pull-image.yml
  eng/common/scripts/Update-DocsMsPackages.ps1
Labels: EngSys, Central-EngSys

#3027 Sync eng/common directory with azure-sdk-tools for PR 2053
  eng/common/TestResources/New-TestResources.ps1
Labels: EngSys, Central-EngSys

#3032 Sync eng/common directory with azure-sdk-tools for PR 2199
  eng/common/scripts/stress-testing/deploy-stress-tests.ps1
  eng/common/scripts/stress-testing/find-all-stress-packages.ps1
Labels: EngSys, Central-EngSys

#3001 Use ms for connection timeout
  sdk/core/azure-core/inc/azure/core/http/curl_transport.hpp
  sdk/core/azure-core/src/http/curl/curl.cpp
  sdk/core/azure-core/src/http/curl/static_curl.cpp
  sdk/core/azure-core/test/ut/curl_connection_pool_test.cpp
Labels: Client

#3033 Move Request general ctor to Private
  sdk/core/azure-core/CHANGELOG.md
  sdk/core/azure-core/inc/azure/core/http/http.hpp
Labels: Azure.Core, Client

#3034 use relative instead of source as the source can change
  sdk/keyvault/azure-security-keyvault-certificates/CMakeLists.txt
  sdk/keyvault/azure-security-keyvault-keys/CMakeLists.txt
  sdk/keyvault/azure-security-keyvault-secrets/CMakeLists.txt
Labels: Client, KeyVault

#3036 Sync eng/common directory with azure-sdk-tools for PR 2202
  eng/common/scripts/ChangeLog-Operations.ps1
  eng/common/scripts/Prepare-Release.ps1
Labels: EngSys, Central-EngSys

#3039 Changelog for #2968
  sdk/storage/azure-storage-blobs/CHANGELOG.md
Labels: Client, Storage

#3047 cl release CORE 1.3.0
  sdk/core/azure-core/CHANGELOG.md
  sdk/core/azure-core/src/private/package_version.hpp
Labels: Azure.Core, Client

#3029 [GEARAMA]: Updates from archboard review of KeyVault certificates
  sdk/keyvault/azure-security-keyvault-certificates/README.md
  sdk/keyvault/azure-security-keyvault-certificates/inc/azure/keyvault/certificates/certificate_client.hpp
  sdk/keyvault/azure-security-keyvault-certificates/inc/azure/keyvault/certificates/certificate_client_models.hpp
  sdk/keyvault/azure-security-keyvault-certificates/samples/certificate-GetCertificates/README.md
  sdk/keyvault/azure-security-keyvault-certificates/samples/certificate-GetCertificates/certificate-GetCertificates.cpp
  sdk/keyvault/azure-security-keyvault-certificates/samples/certificate-ImportCertificate/README.md
  sdk/keyvault/azure-security-keyvault-certificates/samples/certificate-ImportCertificate/certificate-ImportCertificate.cpp
  sdk/keyvault/azure-security-keyvault-certificates/samples/certificate-basic-operations/README.md
  sdk/keyvault/azure-security-keyvault-certificates/samples/certificate-basic-operations/certificate-basic-operations.cpp
  sdk/keyvault/azure-security-keyvault-certificates/src/certificate_client.cpp
  sdk/keyvault/azure-security-keyvault-certificates/src/certificate_serializers.cpp
  sdk/keyvault/azure-security-keyvault-certificates/src/private/certificate_serializers.hpp
  sdk/keyvault/azure-security-keyvault-certificates/test/ut/certificate_client_base_test.hpp
  sdk/keyvault/azure-security-keyvault-certificates/test/ut/certificate_client_test.cpp
  sdk/keyvault/azure-security-keyvault-certificates/test/ut/recordings/KeyVaultCertificateClientTest.BackupRestoreCertificate.json
  sdk/keyvault/azure-security-keyvault-certificates/test/ut/recordings/KeyVaultCertificateClientTest.CreateCertificate.json
  sdk/keyvault/azure-security-keyvault-certificates/test/ut/recordings/KeyVaultCertificateClientTest.CreateCertificateResumeToken.json
  sdk/keyvault/azure-security-keyvault-certificates/test/ut/recordings/KeyVaultCertificateClientTest.CreateGetIssuer.json
  sdk/keyvault/azure-security-keyvault-certificates/test/ut/recordings/KeyVaultCertificateClientTest.DeleteWrongCertificate.json
  sdk/keyvault/azure-security-keyvault-certificates/test/ut/recordings/KeyVaultCertificateClientTest.DownloadImportPem.json
  sdk/keyvault/azure-security-keyvault-certificates/test/ut/recordings/KeyVaultCertificateClientTest.DownloadImportPkcs.json
  sdk/keyvault/azure-security-keyvault-certificates/test/ut/recordings/KeyVaultCertificateClientTest.GetCertificate.json
  sdk/keyvault/azure-security-keyvault-certificates/test/ut/recordings/KeyVaultCertificateClientTest.GetCertificatePolicy.json
  sdk/keyvault/azure-security-keyvault-certificates/test/ut/recordings/KeyVaultCertificateClientTest.GetCertificateVersion.json
  sdk/keyvault/azure-security-keyvault-certificates/test/ut/recordings/KeyVaultCertificateClientTest.GetContacts.json
  sdk/keyvault/azure-security-keyvault-certificates/test/ut/recordings/KeyVaultCertificateClientTest.GetContactsDuplicateEmail.json
  sdk/keyvault/azure-security-keyvault-certificates/test/ut/recordings/KeyVaultCertificateClientTest.GetContactsPartial.json
  sdk/keyvault/azure-security-keyvault-certificates/test/ut/recordings/KeyVaultCertificateClientTest.GetDeletedCertificate.json
  sdk/keyvault/azure-security-keyvault-certificates/test/ut/recordings/KeyVaultCertificateClientTest.GetDeletedCertificates.json
  sdk/keyvault/azure-security-keyvault-certificates/test/ut/recordings/KeyVaultCertificateClientTest.GetPropertiesOfCertificateVersions.json
  sdk/keyvault/azure-security-keyvault-certificates/test/ut/recordings/KeyVaultCertificateClientTest.GetPropertiesOfCertificates.json
  sdk/keyvault/azure-security-keyvault-certificates/test/ut/recordings/KeyVaultCertificateClientTest.GetPropertiesOfCertificatesVersionsNoCert.json
  sdk/keyvault/azure-security-keyvault-certificates/test/ut/recordings/KeyVaultCertificateClientTest.GetPropertiesOfIssuers.json
  sdk/keyvault/azure-security-keyvault-certificates/test/ut/recordings/KeyVaultCertificateClientTest.SetContacts.json
  sdk/keyvault/azure-security-keyvault-certificates/test/ut/recordings/KeyVaultCertificateClientTest.UpdateCertificate.json
  sdk/keyvault/azure-security-keyvault-certificates/test/ut/recordings/KeyVaultCertificateClientTest.UpdateCertificatePolicy.json
  sdk/keyvault/azure-security-keyvault-certificates/test/ut/recordings/KeyVaultCertificateClientTest.UpdateIssuer.json
Labels: KeyVault

#3049 Update cspell.json entry for contributor names within azure core changelog.
  .vscode/cspell.json
  sdk/core/azure-core/CHANGELOG.md
Labels: EngSys

#3050 [GEARAMA]: Final set of updates from archboard review of KeyVault certificates
  sdk/keyvault/azure-security-keyvault-certificates/inc/azure/keyvault/certificates/certificate_client_models.hpp
  sdk/keyvault/azure-security-keyvault-certificates/samples/certificate-ImportCertificate/certificate-ImportCertificate.cpp
  sdk/keyvault/azure-security-keyvault-certificates/src/certificate_serializers.cpp
  sdk/keyvault/azure-security-keyvault-certificates/test/ut/certificate_client_base_test.hpp
  sdk/keyvault/azure-security-keyvault-certificates/test/ut/certificate_client_test.cpp
Labels: KeyVault

#3068 Disable unit tests for staticLibCurl since they are failing on Mac
  sdk/core/azure-core/test/ut/transport_adapter_implementation_test.cpp
Labels: Azure.Core, test-reliability

#3069 Fixed linking error when Azure SDK is being built as DLL.
  sdk/core/azure-core/CHANGELOG.md
  sdk/core/azure-core/inc/azure/core/http/curl_transport.hpp
Labels: ARM - Core

#3071 Fix up build error by adding missing parenthesis in tests
  sdk/core/azure-core/test/ut/transport_adapter_implementation_test.cpp
  sdk/core/ci.yml
Labels: Azure.Core, test-enhancement

#3066 Sync eng/common directory with azure-sdk-tools for PR 2219
  eng/common/testproxy/docker-start-proxy.ps1
  eng/common/testproxy/test-proxy-docker.yml
Labels: EngSys, Central-EngSys

#3028 Rename some model types for Queue service
  sdk/storage/azure-storage-queues/CHANGELOG.md
  sdk/storage/azure-storage-queues/inc/azure/storage/queues/protocol/queue_rest_client.hpp
  sdk/storage/azure-storage-queues/inc/azure/storage/queues/queue_client.hpp
  sdk/storage/azure-storage-queues/inc/azure/storage/queues/queue_service_client.hpp
  sdk/storage/azure-storage-queues/src/queue_client.cpp
  sdk/storage/azure-storage-queues/src/queue_service_client.cpp
  sdk/storage/azure-storage-queues/test/ut/queue_client_test.cpp
  sdk/storage/azure-storage-queues/test/ut/queue_sas_test.cpp
  sdk/storage/azure-storage-queues/test/ut/queue_service_client_test.cpp
Labels: Client, Storage

#3076 Storage Nov Release
  sdk/storage/azure-storage-queues/CHANGELOG.md
Labels: Client, Storage

#3079 Reduce incidence of build storms
  eng/pipelines/templates/jobs/archetype-sdk-client.yml
  eng/pipelines/templates/jobs/ci.tests.yml
  eng/pipelines/templates/stages/archetype-cpp-release.yml
  eng/pipelines/templates/stages/archetype-sdk-client.yml
  sdk/core/ci.yml
  sdk/identity/ci.yml
  sdk/keyvault/ci.yml
  sdk/storage/ci.yml
  sdk/template/ci.yml
Labels: EngSys

#3081 Sync eng/common directory with azure-sdk-tools for PR 2223
  eng/common/scripts/stress-testing/deploy-stress-tests.ps1
  eng/common/scripts/stress-testing/find-all-stress-packages.ps1
Labels: EngSys, Central-EngSys

#3083 Remove `en-us` from links in code comments
  sdk/core/azure-core/src/http/curl/curl.cpp
  sdk/core/azure-core/src/http/retry_policy.cpp
  sdk/identity/azure-identity/inc/azure/identity/client_secret_credential.hpp
  sdk/keyvault/azure-security-keyvault-keys/test/ut/key_client_import_test_live.cpp
  sdk/keyvault/azure-security-keyvault-keys/test/ut/mocked_transport_adapter_test.hpp
  sdk/storage/azure-storage-blobs/inc/azure/storage/blobs/blob_options.hpp
  sdk/storage/azure-storage-blobs/inc/azure/storage/blobs/protocol/blob_rest_client.hpp
  sdk/storage/azure-storage-files-datalake/inc/azure/storage/files/datalake/datalake_options.hpp
  sdk/storage/azure-storage-queues/inc/azure/storage/queues/queue_options.hpp
Labels: Docs

#3084 Update repo links (master => main)
  sdk/core/azure-core-test/README.md
Labels: Docs

#3080 [GEARAMA]: Changelog for KeyVault Certificates
  sdk/keyvault/azure-security-keyvault-certificates/CHANGELOG.md
Labels: KeyVault

#3088 Sync eng/common directory with azure-sdk-tools for PR 2240
  eng/common/scripts/get-codeowners.ps1
Labels: EngSys, Central-EngSys

#3089 Sync eng/common directory with azure-sdk-tools for PR 2242
  eng/common/testproxy/test-proxy-tool.yml
Labels: EngSys, Central-EngSys

#3085 Remove `LICENSE` file duplicates
  sdk/core/azure-core-test/README.md
  sdk/core/azure-core/LICENSE
  sdk/core/azure-core/README.md
  sdk/identity/azure-identity/README.md
  sdk/keyvault/azure-security-keyvault-certificates/README.md
  sdk/keyvault/azure-security-keyvault-secrets/LICENSE
  sdk/keyvault/azure-security-keyvault-secrets/README.md
  sdk/template/azure-template/LICENSE
  sdk/template/azure-template/README.md
Labels: MQ

#3097 Sync eng/common directory with azure-sdk-tools for PR 2249
  eng/common/testproxy/test-proxy-docker.yml
  eng/common/testproxy/test-proxy-tool.yml
Labels: EngSys, Central-EngSys

#3099 Sync eng/common directory with azure-sdk-tools for PR 2247
  eng/common/TestResources/New-TestResources.ps1
  eng/common/TestResources/clouds/AzureChinaCloud.json
  eng/common/TestResources/clouds/AzureCloud.json
  eng/common/TestResources/clouds/AzureUSGovernment.json
Labels: EngSys, Central-EngSys

#3102 Sync eng/common directory with azure-sdk-tools for PR 2259
  eng/common/testproxy/test-proxy-tool.yml
Labels: EngSys, Central-EngSys

#3104 Sync eng/common directory with azure-sdk-tools for PR 2265
  eng/common/scripts/Verify-Links.ps1
Labels: EngSys, Central-EngSys

#3101 Require Azure Core 1.3.1 for KeyVault packages
  sdk/keyvault/azure-security-keyvault-certificates/vcpkg/Config.cmake.in
  sdk/keyvault/azure-security-keyvault-certificates/vcpkg/vcpkg.json
  sdk/keyvault/azure-security-keyvault-keys/vcpkg/Config.cmake.in
  sdk/keyvault/azure-security-keyvault-keys/vcpkg/vcpkg.json
  sdk/keyvault/azure-security-keyvault-secrets/vcpkg/Config.cmake.in
  sdk/keyvault/azure-security-keyvault-secrets/vcpkg/vcpkg.json
Labels: Client, KeyVault

#3107 Sync eng/common directory with azure-sdk-tools for PR 2276
  eng/common/pipelines/templates/jobs/archetype-sdk-tests-generate.yml
Labels: EngSys, Central-EngSys

#3109 Sync eng/common directory with azure-sdk-tools for PR 2267
  eng/common/scripts/Prepare-Release.ps1
Labels: EngSys, Central-EngSys

#3110 Sync eng/common directory with azure-sdk-tools for PR 2272
  eng/common/scripts/Helpers/Resource-Helpers.ps1
Labels: EngSys, Central-EngSys

#3108 Move Key Vault samples from certificates and secrets to same structure as Keys
  sdk/keyvault/azure-security-keyvault-certificates/CMakeLists.txt
  sdk/keyvault/azure-security-keyvault-certificates/README.md
  sdk/keyvault/azure-security-keyvault-certificates/samples/README.md
  sdk/keyvault/azure-security-keyvault-certificates/samples/certificate-GetCertificates/CMakeLists.txt
  sdk/keyvault/azure-security-keyvault-certificates/samples/certificate-ImportCertificate/CMakeLists.txt
  sdk/keyvault/azure-security-keyvault-certificates/samples/certificate_basic_operations.md
  sdk/keyvault/azure-security-keyvault-certificates/samples/certificate_get_certificates.md
  sdk/keyvault/azure-security-keyvault-certificates/samples/certificate_import_certificate.md
  sdk/keyvault/azure-security-keyvault-certificates/test/samples/CMakeLists.txt
  sdk/keyvault/azure-security-keyvault-certificates/test/samples/certificate-basic-operations/CMakeLists.txt
  sdk/keyvault/azure-security-keyvault-certificates/test/samples/certificate-basic-operations/certificate_basic_operations.cpp
  sdk/keyvault/azure-security-keyvault-certificates/test/samples/certificate-get-certificates/CMakeLists.txt
  sdk/keyvault/azure-security-keyvault-certificates/test/samples/certificate-get-certificates/certificate_get_certificates.cpp
  sdk/keyvault/azure-security-keyvault-certificates/test/samples/certificate-import-certificate/CMakeLists.txt
  sdk/keyvault/azure-security-keyvault-certificates/test/samples/certificate-import-certificate/certificate_import_certificate.cpp
  sdk/keyvault/azure-security-keyvault-secrets/CMakeLists.txt
  sdk/keyvault/azure-security-keyvault-secrets/README.md
  sdk/keyvault/azure-security-keyvault-secrets/samples/README.md
  sdk/keyvault/azure-security-keyvault-secrets/samples/sample1_basic_operations.md
  sdk/keyvault/azure-security-keyvault-secrets/samples/sample2_backup_restore.md
  sdk/keyvault/azure-security-keyvault-secrets/samples/sample3_delete_recover.md
  sdk/keyvault/azure-security-keyvault-secrets/samples/sample4_get_secrets_deleted.md
  sdk/keyvault/azure-security-keyvault-secrets/test/samples/CMakeLists.txt
  sdk/keyvault/azure-security-keyvault-secrets/test/samples/sample1-basic-operations/CMakeLists.txt
  sdk/keyvault/azure-security-keyvault-secrets/test/samples/sample1-basic-operations/sample1_basic_operations.cpp
  sdk/keyvault/azure-security-keyvault-secrets/test/samples/sample2-backup-restore/CMakeLists.txt
  sdk/keyvault/azure-security-keyvault-secrets/test/samples/sample2-backup-restore/sample2_backup_restore.cpp
  sdk/keyvault/azure-security-keyvault-secrets/test/samples/sample3-delete-recover/CMakeLists.txt
  sdk/keyvault/azure-security-keyvault-secrets/test/samples/sample3-delete-recover/sample3_delete_recover.cpp
  sdk/keyvault/azure-security-keyvault-secrets/test/samples/sample4-get-secrets-deleted/CMakeLists.txt
  sdk/keyvault/azure-security-keyvault-secrets/test/samples/sample4-get-secrets-deleted/sample4_get_secrets_deleted.cpp
Labels: Client, KeyVault, MQ

#3098 New API: CopyFromUri, which copies a blob synchronously
  sdk/storage/azure-storage-blobs/CHANGELOG.md
  sdk/storage/azure-storage-blobs/inc/azure/storage/blobs/blob_client.hpp
  sdk/storage/azure-storage-blobs/inc/azure/storage/blobs/blob_options.hpp
  sdk/storage/azure-storage-blobs/inc/azure/storage/blobs/protocol/blob_rest_client.hpp
  sdk/storage/azure-storage-blobs/src/blob_client.cpp
  sdk/storage/azure-storage-blobs/test/ut/append_blob_client_test.cpp
  sdk/storage/azure-storage-blobs/test/ut/blob_container_client_test.cpp
  sdk/storage/azure-storage-blobs/test/ut/block_blob_client_test.cpp
Labels: Client, Storage

#3112 Sync eng/common directory with azure-sdk-tools for PR 2290
  eng/common/testproxy/docker-start-proxy.ps1
  eng/common/testproxy/test-proxy-tool.yml
Labels: EngSys, Central-EngSys

#3111 Do not initialize statics in inline functions
  sdk/core/azure-core/CMakeLists.txt
  sdk/core/azure-core/inc/azure/core/etag.hpp
  sdk/core/azure-core/inc/azure/core/internal/io/null_body_stream.hpp
  sdk/core/azure-core/src/etag.cpp
  sdk/core/azure-core/src/io/body_stream.cpp
Labels: Azure.Core, MQ

#3114 fix a bug in generated xml code
  sdk/storage/azure-storage-blobs/inc/azure/storage/blobs/protocol/blob_rest_client.hpp
  sdk/storage/azure-storage-common/src/xml_wrapper.cpp
  sdk/storage/azure-storage-queues/inc/azure/storage/queues/protocol/queue_rest_client.hpp
Labels: Client, Storage

#3059 Proposal: Breaking Change: Make AZURE_ASSERT and related macros internal
  sdk/core/azure-core/CHANGELOG.md
  sdk/core/azure-core/CMakeLists.txt
  sdk/core/azure-core/inc/azure/core.hpp
  sdk/core/azure-core/inc/azure/core/azure_assert.hpp
  sdk/core/azure-core/inc/azure/core/context.hpp
  sdk/core/azure-core/inc/azure/core/cryptography/hash.hpp
  sdk/core/azure-core/inc/azure/core/etag.hpp
  sdk/core/azure-core/inc/azure/core/http/http.hpp
  sdk/core/azure-core/inc/azure/core/http/raw_response.hpp
  sdk/core/azure-core/inc/azure/core/internal/azure_assert.hpp
  sdk/core/azure-core/inc/azure/core/io/body_stream.hpp
  sdk/core/azure-core/inc/azure/core/nullable.hpp
  sdk/core/azure-core/src/azure_assert.cpp
  sdk/core/azure-core/src/cryptography/sha_hash.cpp
  sdk/core/azure-core/src/http/curl/curl.cpp
  sdk/core/azure-core/src/io/body_stream.cpp
  sdk/storage/azure-storage-blobs/inc/azure/storage/blobs/blob_responses.hpp
  sdk/storage/azure-storage-blobs/src/blob_client.cpp
  sdk/storage/azure-storage-blobs/src/blob_lease_client.cpp
  sdk/storage/azure-storage-blobs/src/blob_responses.cpp
  sdk/storage/azure-storage-common/src/crypt.cpp
  sdk/storage/azure-storage-files-datalake/src/datalake_file_client.cpp
  sdk/storage/azure-storage-files-datalake/src/datalake_responses.cpp
  sdk/storage/azure-storage-files-shares/inc/azure/storage/files/shares/share_responses.hpp
  sdk/storage/azure-storage-files-shares/src/share_file_client.cpp
  sdk/storage/azure-storage-files-shares/src/share_lease_client.cpp
Labels: Azure.Core, MQ, breaking-change

#3105 Run service samples on CI gate with ubuntu
  eng/pipelines/templates/jobs/archetype-sdk-tests.yml
  eng/pipelines/templates/stages/platform-matrix.json
  sdk/keyvault/azure-security-keyvault-certificates/test/samples/certificate-basic-operations/CMakeLists.txt
  sdk/keyvault/azure-security-keyvault-certificates/test/samples/certificate-get-certificates/CMakeLists.txt
  sdk/keyvault/azure-security-keyvault-certificates/test/samples/certificate-get-certificates/certificate_get_certificates.cpp
  sdk/keyvault/azure-security-keyvault-certificates/test/samples/certificate-import-certificate/CMakeLists.txt
  sdk/keyvault/azure-security-keyvault-keys/test/samples/sample1-hello-world/CMakeLists.txt
  sdk/keyvault/azure-security-keyvault-keys/test/samples/sample1-hello-world/sample1_hello_world.cpp
  sdk/keyvault/azure-security-keyvault-keys/test/samples/sample2-backup-and-restore/CMakeLists.txt
  sdk/keyvault/azure-security-keyvault-keys/test/samples/sample3-get-keys/CMakeLists.txt
  sdk/keyvault/azure-security-keyvault-keys/test/samples/sample3-get-keys/sample3_get_keys.cpp
  sdk/keyvault/azure-security-keyvault-keys/test/samples/sample4-encrypt-decrypt/CMakeLists.txt
  sdk/keyvault/azure-security-keyvault-keys/test/samples/sample5-sign-verify/CMakeLists.txt
  sdk/keyvault/azure-security-keyvault-keys/test/samples/sample5-sign-verify/sample5_sign_verify.cpp
  sdk/keyvault/azure-security-keyvault-keys/test/samples/sample6-wrap-unwrap/CMakeLists.txt
  sdk/keyvault/azure-security-keyvault-secrets/test/samples/sample1-basic-operations/CMakeLists.txt
  sdk/keyvault/azure-security-keyvault-secrets/test/samples/sample2-backup-restore/CMakeLists.txt
  sdk/keyvault/azure-security-keyvault-secrets/test/samples/sample3-delete-recover/CMakeLists.txt
  sdk/keyvault/azure-security-keyvault-secrets/test/samples/sample4-get-secrets-deleted/CMakeLists.txt
  sdk/keyvault/azure-security-keyvault-secrets/test/samples/sample4-get-secrets-deleted/sample4_get_secrets_deleted.cpp
Labels: Client, EngSys, test-enhancement, MQ

#3120 Exclude test, samples, and 3rd party code from code coverage
  sdk/core/azure-core/CMakeLists.txt
  sdk/identity/azure-identity/CMakeLists.txt
  sdk/keyvault/azure-security-keyvault-certificates/CMakeLists.txt
  sdk/keyvault/azure-security-keyvault-keys/CMakeLists.txt
  sdk/keyvault/azure-security-keyvault-secrets/CMakeLists.txt
  sdk/keyvault/ci.yml
  sdk/storage/azure-storage-blobs/CMakeLists.txt
  sdk/storage/azure-storage-common/CMakeLists.txt
  sdk/storage/azure-storage-files-datalake/CMakeLists.txt
  sdk/storage/azure-storage-files-shares/CMakeLists.txt
  sdk/storage/azure-storage-queues/CMakeLists.txt
  sdk/template/azure-template/CMakeLists.txt
Labels: MQ

#3124 Sync eng/common directory with azure-sdk-tools for PR 2321
  eng/common/testproxy/docker-start-proxy.ps1
  eng/common/testproxy/test-proxy-tool.yml
Labels: EngSys, Central-EngSys

#3125 Sync eng/common directory with azure-sdk-tools for PR 2306
  eng/common/scripts/Helpers/Resource-Helpers.ps1
Labels: EngSys, Central-EngSys

#3133 Sync eng/common directory with azure-sdk-tools for PR 2322
  eng/common/scripts/get-codeowners.ps1
Labels: EngSys, Central-EngSys

#3135 Sync eng/common directory with azure-sdk-tools for PR 2333
  eng/common/testproxy/docker-start-proxy.ps1
Labels: EngSys, Central-EngSys

#3138 Sync eng/common directory with azure-sdk-tools for PR 2086
  eng/common/pipelines/templates/steps/get-pr-owners.yml
  eng/common/scripts/Update-DocsMsMetadata.ps1
  eng/common/scripts/get-codeowners.ps1
Labels: EngSys, Central-EngSys

#3141 add LeaseId to Get/SetTags, return all matching tags in FindBlobsByTags
  sdk/storage/azure-storage-blobs/inc/azure/storage/blobs/blob_options.hpp
  sdk/storage/azure-storage-blobs/inc/azure/storage/blobs/protocol/blob_rest_client.hpp
  sdk/storage/azure-storage-blobs/src/blob_client.cpp
  sdk/storage/azure-storage-blobs/test/ut/blob_container_client_test.cpp
Labels: customer-reported

#3144 Sync eng/common directory with azure-sdk-tools for PR 2348
  eng/common/scripts/get-codeowners.ps1
Labels: EngSys, Central-EngSys

#3143 Fix unit tests on Mac
  sdk/identity/azure-identity/test/ut/client_secret_credential_test.cpp
  sdk/identity/azure-identity/test/ut/environment_credential_test.cpp
  sdk/identity/azure-identity/test/ut/managed_identity_credential_test.cpp
Labels: test-enhancement, Azure.Identity, test-reliability

#3142 Sync eng/common directory with azure-sdk-tools for PR 2331
  eng/common/scripts/stress-testing/deploy-stress-tests.ps1
  eng/common/scripts/stress-testing/stress-test-deployment-lib.ps1
Labels: EngSys, Central-EngSys
