Repository Azure/azure-sdk-for-cpp, pull requests merged in 2021-09, with the labels that each got.

#2820 Sync eng/common directory with azure-sdk-tools for PR 1967
  eng/common/pipelines/templates/steps/daily-dev-build-variable.yml
Labels: EngSys, Central-EngSys

#2821 Sync eng/common directory with azure-sdk-tools for PR 1972
  eng/common/scripts/Create-APIReview.ps1
  eng/common/scripts/SemVer.ps1
Labels: EngSys, Central-EngSys

#2819 core cl update for 1.2.1
  sdk/core/azure-core/CHANGELOG.md
  sdk/core/azure-core/src/private/package_version.hpp
Labels: Azure.Core, Client

#2823 Storage Queue Review Feedback
  sdk/storage/azure-storage-queues/CHANGELOG.md
  sdk/storage/azure-storage-queues/inc/azure/storage/queues/protocol/queue_rest_client.hpp
  sdk/storage/azure-storage-queues/inc/azure/storage/queues/queue_client.hpp
  sdk/storage/azure-storage-queues/inc/azure/storage/queues/queue_service_client.hpp
  sdk/storage/azure-storage-queues/sample/queue_encode_message.cpp
  sdk/storage/azure-storage-queues/sample/queue_getting_started.cpp
  sdk/storage/azure-storage-queues/src/queue_client.cpp
  sdk/storage/azure-storage-queues/src/queue_service_client.cpp
  sdk/storage/azure-storage-queues/test/ut/queue_client_test.cpp
  sdk/storage/azure-storage-queues/test/ut/queue_service_client_test.cpp
Labels: Client, Storage

#2829 Make AccessPolicy::StartsOn and ExpiresOn nullable values.
  sdk/storage/azure-storage-files-shares/CHANGELOG.md
  sdk/storage/azure-storage-files-shares/inc/azure/storage/files/shares/protocol/share_rest_client.hpp
  sdk/storage/azure-storage-files-shares/test/share_client_test.cpp
Labels: Client, Storage, blocking-release, auto-merge

#2828 StartsOn and ExpiresOn were changed to nullable
  sdk/storage/azure-storage-blobs/CHANGELOG.md
  sdk/storage/azure-storage-blobs/inc/azure/storage/blobs/protocol/blob_rest_client.hpp
  sdk/storage/azure-storage-blobs/test/ut/blob_container_client_test.cpp
  sdk/storage/azure-storage-files-datalake/CHANGELOG.md
  sdk/storage/azure-storage-files-datalake/test/datalake_file_system_client_test.cpp
Labels: Client, Storage, blocking-release

#2832 small fix in checking nullable variable
  sdk/storage/azure-storage-blobs/src/blob_container_client.cpp
Labels: Client, Storage

#2830 New XML parser on Windows
  sdk/storage/README.md
  sdk/storage/azure-storage-blobs/test/ut/blob_container_client_test.cpp
  sdk/storage/azure-storage-common/CHANGELOG.md
  sdk/storage/azure-storage-common/CMakeLists.txt
  sdk/storage/azure-storage-common/inc/azure/storage/common/internal/xml_wrapper.hpp
  sdk/storage/azure-storage-common/src/xml_wrapper.cpp
  sdk/storage/azure-storage-common/vcpkg/Config.cmake.in
  sdk/storage/azure-storage-common/vcpkg/vcpkg.json
Labels: Client, Storage, blocking-release

#2838 Improvement: Create less threads when there isn't enough data to transfer
  sdk/storage/azure-storage-blobs/CHANGELOG.md
  sdk/storage/azure-storage-common/inc/azure/storage/common/internal/concurrent_transfer.hpp
  sdk/storage/azure-storage-files-datalake/CHANGELOG.md
  sdk/storage/azure-storage-files-shares/CHANGELOG.md
Labels: Client, Storage, blocking-release

#2837 Fix a bug where blobs with some characters cannot be listed
  sdk/storage/azure-storage-blobs/CHANGELOG.md
  sdk/storage/azure-storage-blobs/test/ut/blob_container_client_test.cpp
  sdk/storage/azure-storage-common/inc/azure/storage/common/internal/xml_wrapper.hpp
  sdk/storage/azure-storage-common/src/crypt.cpp
  sdk/storage/azure-storage-common/src/xml_wrapper.cpp
  sdk/storage/azure-storage-files-datalake/CHANGELOG.md
  sdk/storage/azure-storage-files-shares/CHANGELOG.md
Labels: Client, Storage, blocking-release

#2818 Adding Key Vault Certificates - GetCertificateWithPolicy API
  sdk/keyvault/CMakeLists.txt
  sdk/keyvault/azure-security-keyvault-certificates/CHANGELOG.md
  sdk/keyvault/azure-security-keyvault-certificates/CMakeLists.txt
  sdk/keyvault/azure-security-keyvault-certificates/NOTICE.txt
  sdk/keyvault/azure-security-keyvault-certificates/README.md
  sdk/keyvault/azure-security-keyvault-certificates/cgmanifest.json
  sdk/keyvault/azure-security-keyvault-certificates/inc/azure/keyvault/certificates/certificate_client.hpp
  sdk/keyvault/azure-security-keyvault-certificates/inc/azure/keyvault/certificates/certificate_client_models.hpp
  sdk/keyvault/azure-security-keyvault-certificates/inc/azure/keyvault/certificates/certificate_client_options.hpp
  sdk/keyvault/azure-security-keyvault-certificates/inc/azure/keyvault/certificates/dll_import_export.hpp
  sdk/keyvault/azure-security-keyvault-certificates/inc/azure/keyvault/keyvault_certificates.hpp
  sdk/keyvault/azure-security-keyvault-certificates/src/certificate_client.cpp
  sdk/keyvault/azure-security-keyvault-certificates/src/keyvault_certificate.cpp
  sdk/keyvault/azure-security-keyvault-certificates/src/keyvault_certificates_common_request.cpp
  sdk/keyvault/azure-security-keyvault-certificates/src/private/certificate_constants.hpp
  sdk/keyvault/azure-security-keyvault-certificates/src/private/certificate_serializers.hpp
  sdk/keyvault/azure-security-keyvault-certificates/src/private/keyvault_certificates_common_request.hpp
  sdk/keyvault/azure-security-keyvault-certificates/src/private/package_version.hpp
  sdk/keyvault/azure-security-keyvault-certificates/test/ut/CMakeLists.txt
  sdk/keyvault/azure-security-keyvault-certificates/test/ut/certificate_client_base_test.hpp
  sdk/keyvault/azure-security-keyvault-certificates/test/ut/certificate_client_test.cpp
  sdk/keyvault/azure-security-keyvault-certificates/test/ut/macro_guard.cpp
  sdk/keyvault/azure-security-keyvault-certificates/test/ut/recordings/KeyVaultCertificateClientTest.GetCertificate.json
  sdk/keyvault/azure-security-keyvault-certificates/test/ut/recordings/KeyVaultCertificateClientTest.GetCertificateVersion.json
  sdk/keyvault/azure-security-keyvault-certificates/vcpkg/Config.cmake.in
  sdk/keyvault/azure-security-keyvault-certificates/vcpkg/portfile.cmake
  sdk/keyvault/azure-security-keyvault-certificates/vcpkg/vcpkg.json
Labels: Client, KeyVault

#2843 Sync eng/common directory with azure-sdk-tools for PR 1986
  eng/common/testproxy/docker-start-proxy.ps1
Labels: EngSys, Central-EngSys

#2845 Update vcpkg.json
  sdk/storage/azure-storage-common/vcpkg/vcpkg.json
Labels: Client, Storage

#2840 Key Vault Keys - Release 4.1.0 - Sep 2021 - Changelog
  sdk/keyvault/azure-security-keyvault-keys/CHANGELOG.md
  sdk/keyvault/azure-security-keyvault-keys/src/private/package_version.hpp
Labels: Client, KeyVault

#2849 Sync eng/common directory with azure-sdk-tools for PR 1982
  eng/common/pipelines/templates/steps/set-test-pipeline-version.yml
Labels: EngSys, Central-EngSys

#2858 Add ut for queue message containing special characters
  sdk/storage/azure-storage-queues/test/ut/queue_client_messages_test.cpp
Labels: Client, Storage

#2859 Sync eng/common directory with azure-sdk-tools for PR 1977
  eng/common/scripts/Update-DocsMsPackages.ps1
Labels: EngSys, Central-EngSys

#2857 Sync eng/common directory with azure-sdk-tools for PR 1995
  eng/common/scripts/stress-testing/deploy-stress-tests.ps1
Labels: EngSys, Central-EngSys

#2860 Sync eng/common directory with azure-sdk-tools for PR 1983
  eng/common/TestResources/New-TestResources.ps1
  eng/common/TestResources/New-TestResources.ps1.md
  eng/common/TestResources/README.md
Labels: EngSys, Central-EngSys

#2862 Sync eng/common directory with azure-sdk-tools for PR 1946
  eng/common/scripts/check-spelling-in-changed-files.ps1
Labels: EngSys, Central-EngSys

#2863 Sync eng/common directory with azure-sdk-tools for PR 2006
  eng/common/scripts/SemVer.ps1
Labels: EngSys, Central-EngSys

#2864 Sync eng/common directory with azure-sdk-tools for PR 1979
  eng/common/scripts/ChangeLog-Operations.ps1
  eng/common/scripts/Update-ChangeLog.ps1
Labels: EngSys, Central-EngSys

#2900 Sync eng/common directory with azure-sdk-tools for PR 2008
  eng/common/scripts/ChangeLog-Operations.ps1
  eng/common/scripts/Prepare-Release.ps1
  eng/common/scripts/Update-ChangeLog.ps1
Labels: EngSys, Central-EngSys

#2897 Sync eng/common directory with azure-sdk-tools for PR 2009
  eng/common/pipelines/templates/steps/cache-ps-modules.yml
Labels: EngSys, Central-EngSys

#2904 Sync eng/common directory with azure-sdk-tools for PR 2016
  eng/common/pipelines/templates/steps/verify-changelog.yml
Labels: EngSys, Central-EngSys

#2903 Sync eng/common directory with azure-sdk-tools for PR 2011
  eng/common/pipelines/templates/steps/detect-api-changes.yml
  eng/common/scripts/Detect-Api-Changes.ps1
Labels: EngSys, Central-EngSys

#2907 Sync eng/common directory with azure-sdk-tools for PR 2010
  eng/common/scripts/ChangeLog-Operations.ps1
  eng/common/scripts/Prepare-Release.ps1
  eng/common/scripts/Update-ChangeLog.ps1
Labels: EngSys, Central-EngSys

#2913 Sync eng/common directory with azure-sdk-tools for PR 2025
  eng/common/scripts/Collect-ChangeLogs.ps1
  eng/common/scripts/Update-ChangeLog.ps1
  eng/common/scripts/Verify-ChangeLog.ps1
Labels: EngSys, Central-EngSys

#2918 Sync eng/common directory with azure-sdk-tools for PR 2035
  eng/common/scripts/Update-DocsMsPackages.ps1
Labels: EngSys, Central-EngSys

#2920 Sync eng/common directory with azure-sdk-tools for PR 2031
  eng/common/pipelines/templates/steps/policheck.yml
Labels: EngSys, Central-EngSys

#2915 Sync eng/common directory with azure-sdk-tools for PR 2027
  eng/common/scripts/stress-testing/deploy-stress-tests.ps1
Labels: EngSys, Central-EngSys

#2919 Sync eng/common directory with azure-sdk-tools for PR 2039
  eng/common/scripts/stress-testing/deploy-stress-tests.ps1
Labels: EngSys, Central-EngSys

#2917 Adding GetCryptographyClient to KeyClient
  sdk/keyvault/azure-security-keyvault-keys/CHANGELOG.md
  sdk/keyvault/azure-security-keyvault-keys/CMakeLists.txt
  sdk/keyvault/azure-security-keyvault-keys/inc/azure/keyvault/keys/cryptography/cryptography_client.hpp
  sdk/keyvault/azure-security-keyvault-keys/inc/azure/keyvault/keys/key_client.hpp
  sdk/keyvault/azure-security-keyvault-keys/src/cryptography/cryptography_client.cpp
  sdk/keyvault/azure-security-keyvault-keys/src/key_client.cpp
  sdk/keyvault/azure-security-keyvault-keys/src/private/cryptography_internal_access.hpp
  sdk/keyvault/azure-security-keyvault-keys/test/ut/key_cryptographic_client_test_live.cpp
Labels: Client, KeyVault
