Repository Azure/azure-sdk-for-cpp, pull requests merged in 2022-07, with the labels that each got.

#3790 Blob batch improvement
  sdk/storage/azure-storage-blobs/inc/azure/storage/blobs/blob_batch.hpp
  sdk/storage/azure-storage-blobs/inc/azure/storage/blobs/blob_client.hpp
  sdk/storage/azure-storage-blobs/inc/azure/storage/blobs/blob_container_client.hpp
  sdk/storage/azure-storage-blobs/inc/azure/storage/blobs/blob_service_client.hpp
  sdk/storage/azure-storage-blobs/inc/azure/storage/blobs/deferred_response.hpp
  sdk/storage/azure-storage-blobs/src/blob_batch.cpp
  sdk/storage/azure-storage-blobs/src/blob_container_client.cpp
  sdk/storage/azure-storage-blobs/src/blob_service_client.cpp
  sdk/storage/azure-storage-blobs/test/ut/blob_batch_client_test.cpp
Labels: Client, Storage

#3793 Sync eng/common directory with azure-sdk-tools for PR 3563
  eng/common/pipelines/templates/steps/verify-samples.yml
Labels: EngSys, Central-EngSys

#3798 Sync eng/common directory with azure-sdk-tools for PR 3428
  eng/common/scripts/Helpers/Metadata-Helpers.ps1
  eng/common/scripts/Service-Level-Readme-Automation.ps1
  eng/common/scripts/Update-DocsMsToc.ps1
Labels: EngSys, Central-EngSys

#3800 add const qualifiers for CreateBatch()
  sdk/storage/azure-storage-blobs/inc/azure/storage/blobs/blob_container_client.hpp
  sdk/storage/azure-storage-blobs/inc/azure/storage/blobs/blob_service_client.hpp
  sdk/storage/azure-storage-blobs/src/blob_container_client.cpp
  sdk/storage/azure-storage-blobs/src/blob_service_client.cpp
Labels: Client, Storage

#3791 Sync eng/common directory with azure-sdk-tools for PR 3527
  eng/common/scripts/Helpers/PSModule-Helpers.ps1
Labels: EngSys, Central-EngSys

#3804 Sync eng/common directory with azure-sdk-tools for PR 3568
  eng/common/scripts/Verify-Resource-Ref.ps1
Labels: EngSys, Central-EngSys

#3802 Sync eng/common directory with azure-sdk-tools for PR 3500
  eng/common/testproxy/target_version.txt
Labels: EngSys, Central-EngSys

#3782 Azure Storage July Release
  sdk/storage/azure-storage-blobs/CHANGELOG.md
Labels: Client, Storage

#3806 Sync eng/common directory with azure-sdk-tools for PR 3480
  eng/common/pipelines/templates/steps/validate-filename.yml
Labels: EngSys, Central-EngSys

#3813 Sync eng/common directory with azure-sdk-tools for PR 3546
  eng/common/scripts/SetTestPipelineVersion.ps1
Labels: EngSys, Central-EngSys

#3814 Sync eng/common directory with azure-sdk-tools for PR 3590
  eng/common/pipelines/templates/steps/set-test-pipeline-version.yml
  eng/common/scripts/SetTestPipelineVersion.ps1
Labels: EngSys, Central-EngSys

#3815 Sync eng/common directory with azure-sdk-tools for PR 3606
  eng/common/pipelines/templates/steps/sparse-checkout.yml
Labels: EngSys, Central-EngSys

#3816 Sync eng/common directory with azure-sdk-tools for PR 3584
  eng/common/pipelines/templates/jobs/docindex.yml
Labels: EngSys, Central-EngSys

#3819 Sync eng/common directory with azure-sdk-tools for PR 3578
  eng/common/scripts/Helpers/Metadata-Helpers.ps1
  eng/common/scripts/Service-Level-Readme-Automation.ps1
  eng/common/scripts/common.ps1
Labels: EngSys, Central-EngSys

#3824 Sync eng/common directory with azure-sdk-tools for PR 3642
  eng/common/scripts/Helpers/Metadata-Helpers.ps1
  eng/common/scripts/Service-Level-Readme-Automation.ps1
Labels: EngSys, Central-EngSys

#3830 Update attestation core vcpkg dependency to latest GA version that is required.
  sdk/attestation/azure-security-attestation/vcpkg/Config.cmake.in
  sdk/attestation/azure-security-attestation/vcpkg/vcpkg.json
Labels: Attestation

#3833 Sync eng/common directory with azure-sdk-tools for PR 3657
  eng/common/pipelines/templates/jobs/perf.yml
Labels: EngSys, Central-EngSys

#3834 Sync eng/common directory with azure-sdk-tools for PR 3656
  eng/common/testproxy/test-proxy-docker.yml
  eng/common/testproxy/test-proxy-tool.yml
Labels: EngSys, Central-EngSys

#3792 Transfer Manager, copy support & journal for downloading
  sdk/storage/azure-storage-common/inc/azure/storage/common/internal/file_io.hpp
  sdk/storage/azure-storage-common/src/file_io.cpp
  sdk/storage/azure-storage-datamovement/CMakeLists.txt
  sdk/storage/azure-storage-datamovement/inc/azure/storage/datamovement/blob_folder.hpp
  sdk/storage/azure-storage-datamovement/inc/azure/storage/datamovement/blob_transfer_manager.hpp
  sdk/storage/azure-storage-datamovement/inc/azure/storage/datamovement/datamovement_options.hpp
  sdk/storage/azure-storage-datamovement/inc/azure/storage/datamovement/job_engine.hpp
  sdk/storage/azure-storage-datamovement/inc/azure/storage/datamovement/job_properties.hpp
  sdk/storage/azure-storage-datamovement/inc/azure/storage/datamovement/task.hpp
  sdk/storage/azure-storage-datamovement/inc/azure/storage/datamovement/tasks/async_copy_blob_task.hpp
  sdk/storage/azure-storage-datamovement/inc/azure/storage/datamovement/tasks/download_blob_to_file_task.hpp
  sdk/storage/azure-storage-datamovement/inc/azure/storage/datamovement/transfer_engine.hpp
  sdk/storage/azure-storage-datamovement/src/blob_transfer_manager.cpp
  sdk/storage/azure-storage-datamovement/src/job_engine.cpp
  sdk/storage/azure-storage-datamovement/src/job_engine_task_generation.cpp
  sdk/storage/azure-storage-datamovement/src/tasks/async_copy_blob_task.cpp
  sdk/storage/azure-storage-datamovement/src/tasks/download_blob_to_file_task.cpp
  sdk/storage/azure-storage-datamovement/src/transfer_engine.cpp
  sdk/storage/azure-storage-datamovement/src/utilities.cpp
  sdk/storage/azure-storage-datamovement/test/ut/CMakeLists.txt
  sdk/storage/azure-storage-datamovement/test/ut/blob_transfer_manager_async_copy_test.cpp
  sdk/storage/azure-storage-datamovement/test/ut/blob_transfer_manager_download_test.cpp
  sdk/storage/azure-storage-datamovement/test/ut/blob_transfer_manager_test.cpp
  sdk/storage/azure-storage-datamovement/test/ut/blob_transfer_manager_test.hpp
  sdk/storage/azure-storage-datamovement/test/ut/blob_transfer_manager_upload_test.cpp
Labels: Client, Storage

#3821 Sync eng/common directory with azure-sdk-tools for PR 3628
  eng/common/scripts/Update-DocsMsMetadata.ps1
Labels: EngSys, Central-EngSys

#3842 Sync eng/common directory with azure-sdk-tools for PR 3700
  eng/common/pipelines/templates/jobs/perf.yml
Labels: EngSys, Central-EngSys

#3843 Sync eng/common directory with azure-sdk-tools for PR 3702
  eng/common/scripts/Test-SampleMetadata.ps1
Labels: EngSys, Central-EngSys

#3846 Sync eng/common directory with azure-sdk-tools for PR 3661
  eng/common/pipelines/templates/steps/sparse-checkout.yml
Labels: EngSys, Central-EngSys

#3845 Sync eng/common directory with azure-sdk-tools for PR 3735
  eng/common/scripts/Detect-Api-Changes.ps1
Labels: EngSys, Central-EngSys

#3851 Sync eng/common directory with azure-sdk-tools for PR 3754
  eng/common/pipelines/templates/steps/sparse-checkout.yml
Labels: EngSys, Central-EngSys

#3857 Sync eng/common directory with azure-sdk-tools for PR 3753
  eng/common/scripts/job-matrix/README.md
  eng/common/scripts/job-matrix/samples/matrix.json
  eng/common/scripts/job-matrix/tests/job-matrix-functions.filter.tests.ps1
  eng/common/scripts/job-matrix/tests/job-matrix-functions.tests.ps1
Labels: EngSys, Central-EngSys

#3859 Sync eng/common directory with azure-sdk-tools for PR 3787
  eng/common/TestResources/setup-environments.yml
Labels: EngSys, Central-EngSys
