Repository Azure/azure-sdk-for-cpp, pull requests merged in 2022-10, with the labels that each got.

#3952 fix LROs in keyvault
  sdk/keyvault/azure-security-keyvault-certificates/test/ut/certificate_client_test.cpp
  sdk/keyvault/azure-security-keyvault-certificates/test/ut/recordings/KeyVaultCertificateClientTest.CreateCertificate.json
  sdk/keyvault/azure-security-keyvault-certificates/test/ut/recordings/KeyVaultCertificateClientTest.CreateCertificateResumeToken.json
  sdk/keyvault/azure-security-keyvault-keys/src/delete_key_operation.cpp
  sdk/keyvault/azure-security-keyvault-keys/src/recover_deleted_key_operation.cpp
  sdk/keyvault/azure-security-keyvault-keys/test/ut/key_client_delete_test_live.cpp
  sdk/keyvault/azure-security-keyvault-keys/test/ut/recordings/KeyVaultKeyClient.RecoverOperationResumeToken.json
  sdk/keyvault/azure-security-keyvault-secrets/test/ut/recordings/KeyVaultSecretClientTest.RecoverSecret.json
  sdk/keyvault/azure-security-keyvault-secrets/test/ut/secret_client_test.cpp
Labels: KeyVault

#3997 Fixup comment in unique_handle.hpp to reference curl_easy_cleanup rather than curl_free.
  sdk/core/azure-core/inc/azure/core/internal/unique_handle.hpp
Labels: Docs, Azure.Core

#3996 Azure Core October Release
  sdk/core/azure-core/CHANGELOG.md
Labels: Azure.Core

#3999 Sync eng/common directory with azure-sdk-tools for PR 4315
  eng/common/testproxy/target_version.txt
Labels: EngSys, Central-EngSys

#4001 Sync eng/common directory with azure-sdk-tools for PR 4311
  eng/common/scripts/Verify-Links.ps1
Labels: EngSys, Central-EngSys

#3974 enable datalake softdelete tests
  sdk/storage/azure-storage-files-datalake/test/ut/datalake_file_system_client_test.cpp
  sdk/storage/azure-storage-files-datalake/test/ut/recordings/DataLakeFileSystemClientTest.ListDeletedPaths.json
  sdk/storage/azure-storage-files-datalake/test/ut/recordings/DataLakeFileSystemClientTest.Undelete.json
  sdk/storage/test-resources-post.ps1
  sdk/storage/test-resources.json
Labels: Client, Storage

#4008 Add default .assets directory to .gitignore
  .gitignore
Labels: Central-EngSys

#3975 Storage October release
  cmake-modules/FolderList.cmake
  sdk/storage/azure-storage-blobs/CHANGELOG.md
  sdk/storage/azure-storage-blobs/src/private/package_version.hpp
  sdk/storage/azure-storage-blobs/vcpkg.json
  sdk/storage/azure-storage-files-datalake/CHANGELOG.md
  sdk/storage/azure-storage-files-datalake/vcpkg.json
  sdk/storage/azure-storage-files-shares/CHANGELOG.md
  sdk/storage/azure-storage-files-shares/src/private/package_version.hpp
  sdk/storage/azure-storage-files-shares/vcpkg.json
Labels: Client, Storage

#4016 Updated attestation change log to add periods for consistency
  sdk/attestation/azure-security-attestation/CHANGELOG.md
Labels: Docs, Attestation

#4020 Sync eng/common directory with azure-sdk-tools for PR 4372
  eng/common/scripts/get-codeowners.ps1
Labels: EngSys, Central-EngSys

#4029 Create dmlib feature branch
  cmake-modules/FolderList.cmake
  sdk/storage/CMakeLists.txt
  sdk/storage/azure-storage-blobs/inc/azure/storage/blobs/blob_client.hpp
  sdk/storage/azure-storage-common/inc/azure/storage/common/internal/constants.hpp
  sdk/storage/azure-storage-common/inc/azure/storage/common/internal/file_io.hpp
  sdk/storage/azure-storage-common/src/file_io.cpp
  sdk/storage/azure-storage-datamovement/CHANGELOG.md
  sdk/storage/azure-storage-datamovement/CMakeLists.txt
  sdk/storage/azure-storage-datamovement/NOTICE.txt
  sdk/storage/azure-storage-datamovement/cgmanifest.json
  sdk/storage/azure-storage-datamovement/inc/azure/storage/datamovement/blob_folder.hpp
  sdk/storage/azure-storage-datamovement/inc/azure/storage/datamovement/blob_transfer_manager.hpp
  sdk/storage/azure-storage-datamovement/inc/azure/storage/datamovement/datamovement_options.hpp
  sdk/storage/azure-storage-datamovement/inc/azure/storage/datamovement/dll_import_export.hpp
  sdk/storage/azure-storage-datamovement/inc/azure/storage/datamovement/filesystem.hpp
  sdk/storage/azure-storage-datamovement/inc/azure/storage/datamovement/job_engine.hpp
  sdk/storage/azure-storage-datamovement/inc/azure/storage/datamovement/job_properties.hpp
  sdk/storage/azure-storage-datamovement/inc/azure/storage/datamovement/rtti.hpp
  sdk/storage/azure-storage-datamovement/inc/azure/storage/datamovement/storage_transfer_manager.hpp
  sdk/storage/azure-storage-datamovement/inc/azure/storage/datamovement/task.hpp
  sdk/storage/azure-storage-datamovement/inc/azure/storage/datamovement/task_shared_status.hpp
  sdk/storage/azure-storage-datamovement/inc/azure/storage/datamovement/tasks/async_copy_blob_task.hpp
  sdk/storage/azure-storage-datamovement/inc/azure/storage/datamovement/tasks/download_blob_to_file_task.hpp
  sdk/storage/azure-storage-datamovement/inc/azure/storage/datamovement/tasks/upload_blob_from_file_task.hpp
  sdk/storage/azure-storage-datamovement/inc/azure/storage/datamovement/transfer_engine.hpp
  sdk/storage/azure-storage-datamovement/inc/azure/storage/datamovement/utilities.hpp
  sdk/storage/azure-storage-datamovement/samples/CMakeLists.txt
  sdk/storage/azure-storage-datamovement/samples/datamovement_getting_started.cpp
  sdk/storage/azure-storage-datamovement/src/blob_folder.cpp
  sdk/storage/azure-storage-datamovement/src/blob_transfer_manager.cpp
  sdk/storage/azure-storage-datamovement/src/filesystem.cpp
  sdk/storage/azure-storage-datamovement/src/job_engine.cpp
  sdk/storage/azure-storage-datamovement/src/job_engine_serialization.cpp
  sdk/storage/azure-storage-datamovement/src/job_engine_task_generation.cpp
  sdk/storage/azure-storage-datamovement/src/job_properties.cpp
  sdk/storage/azure-storage-datamovement/src/private/package_version.hpp
  sdk/storage/azure-storage-datamovement/src/storage_transfer_manager.cpp
  sdk/storage/azure-storage-datamovement/src/task_shared_status.cpp
  sdk/storage/azure-storage-datamovement/src/tasks/async_copy_blob_task.cpp
  sdk/storage/azure-storage-datamovement/src/tasks/download_blob_to_file_task.cpp
  sdk/storage/azure-storage-datamovement/src/tasks/upload_blob_from_file_task.cpp
  sdk/storage/azure-storage-datamovement/src/transfer_engine.cpp
  sdk/storage/azure-storage-datamovement/src/utilities.cpp
  sdk/storage/azure-storage-datamovement/test/ut/CMakeLists.txt
  sdk/storage/azure-storage-datamovement/test/ut/blob_folder_test.cpp
  sdk/storage/azure-storage-datamovement/test/ut/blob_transfer_manager_async_copy_test.cpp
  sdk/storage/azure-storage-datamovement/test/ut/blob_transfer_manager_download_test.cpp
  sdk/storage/azure-storage-datamovement/test/ut/blob_transfer_manager_test.cpp
  sdk/storage/azure-storage-datamovement/test/ut/blob_transfer_manager_test.hpp
  sdk/storage/azure-storage-datamovement/test/ut/blob_transfer_manager_upload_test.cpp
  sdk/storage/azure-storage-datamovement/vcpkg.json
  sdk/storage/azure-storage-datamovement/vcpkg/Config.cmake.in
  sdk/storage/azure-storage-datamovement/vcpkg/portfile.cmake
  sdk/storage/azure-storage-datamovement/vcpkg/vcpkg.json
  sdk/storage/ci.yml
Labels: Client, Storage

#4038 datalake encryption scopes
  sdk/storage/azure-storage-files-datalake/inc/azure/storage/files/datalake/datalake_options.hpp
  sdk/storage/azure-storage-files-datalake/inc/azure/storage/files/datalake/datalake_responses.hpp
  sdk/storage/azure-storage-files-datalake/src/datalake_file_system_client.cpp
  sdk/storage/azure-storage-files-datalake/src/datalake_path_client.cpp
  sdk/storage/azure-storage-files-datalake/src/datalake_service_client.cpp
  sdk/storage/azure-storage-files-datalake/test/ut/datalake_file_system_client_test.cpp
  sdk/storage/azure-storage-files-datalake/test/ut/datalake_sas_test.cpp
  sdk/storage/azure-storage-files-datalake/test/ut/datalake_service_client_test.cpp
  sdk/storage/azure-storage-files-datalake/test/ut/recordings/DataLakeFileSystemClientTest.EncryptionScope.json
  sdk/storage/azure-storage-files-datalake/test/ut/recordings/DataLakeServiceClientTest.ListFileSystemsSegment.json
Labels: Storage

#4041 Sync eng/common directory with azure-sdk-tools for PR 3790
  eng/common/scripts/Helpers/PSModule-Helpers.ps1
  eng/common/scripts/job-matrix/Create-JobMatrix.ps1
  eng/common/scripts/job-matrix/job-matrix-functions.ps1
  eng/common/scripts/stress-testing/deploy-stress-tests.ps1
  eng/common/scripts/stress-testing/find-all-stress-packages.ps1
  eng/common/scripts/stress-testing/generate-scenario-matrix.ps1
  eng/common/scripts/stress-testing/stress-test-deployment-lib.ps1
Labels: EngSys, Central-EngSys

#4044 Sync eng/common directory with azure-sdk-tools for PR 4486
  eng/common/spelling/Invoke-Cspell.ps1
  eng/common/spelling/package-lock.json
  eng/common/spelling/package.json
Labels: EngSys, Central-EngSys

#4046 Sync eng/common directory with azure-sdk-tools for PR 4480
  eng/common/scripts/Update-DocsMsToc.ps1
Labels: EngSys, Central-EngSys

#4024 In-memory Identity token cache
  sdk/core/azure-core/CHANGELOG.md
  sdk/core/azure-core/inc/azure/core/credentials/credentials.hpp
  sdk/core/azure-core/src/http/bearer_token_authentication_policy.cpp
  sdk/identity/azure-identity/CHANGELOG.md
  sdk/identity/azure-identity/CMakeLists.txt
  sdk/identity/azure-identity/inc/azure/identity/client_secret_credential.hpp
  sdk/identity/azure-identity/inc/azure/identity/managed_identity_credential.hpp
  sdk/identity/azure-identity/src/client_secret_credential.cpp
  sdk/identity/azure-identity/src/managed_identity_source.cpp
  sdk/identity/azure-identity/src/private/managed_identity_source.hpp
  sdk/identity/azure-identity/src/private/token_cache.hpp
  sdk/identity/azure-identity/src/private/token_cache_internals.hpp
  sdk/identity/azure-identity/src/token_cache.cpp
  sdk/identity/azure-identity/test/ut/CMakeLists.txt
  sdk/identity/azure-identity/test/ut/credential_test_helper.cpp
  sdk/identity/azure-identity/test/ut/token_cache_test.cpp
  sdk/identity/azure-identity/test/ut/token_credential_impl_test.cpp
  sdk/identity/azure-identity/test/ut/token_credential_test.cpp
Labels: Azure.Identity

#4065 Sync eng/common directory with azure-sdk-tools for PR 4504
  eng/common/scripts/stress-testing/generate-scenario-matrix.ps1
  eng/common/scripts/stress-testing/stress-test-deployment-lib.ps1
Labels: EngSys, Central-EngSys

#4066 Sync eng/common directory with azure-sdk-tools for PR 4527
  eng/common/testproxy/target_version.txt
Labels: EngSys, Central-EngSys

#4071 Sync eng/common directory with azure-sdk-tools for PR 4543
  eng/common/scripts/stress-testing/find-all-stress-packages.ps1
Labels: EngSys, Central-EngSys

#4069 Sync eng/common directory with azure-sdk-tools for PR 4532
  eng/common/TestResources/New-TestResources.ps1
Labels: EngSys, Central-EngSys
