Repository Azure/azure-sdk-for-cpp, pull requests merged in 2022-06, with the labels that each got.

#3680 Sync eng/common directory with azure-sdk-tools for PR 3381
  eng/common/pipelines/templates/steps/sparse-checkout.yml
Labels: EngSys, Central-EngSys

#3694 Sync eng/common directory with azure-sdk-tools for PR 3392
  eng/common/scripts/job-matrix/job-matrix-functions.ps1
  eng/common/scripts/job-matrix/tests/job-matrix-functions.modification.tests.ps1
Labels: EngSys, Central-EngSys

#3686 Storage June Release
  cmake-modules/FolderList.cmake
  sdk/storage/azure-storage-blobs/CHANGELOG.md
  sdk/storage/azure-storage-blobs/CMakeLists.txt
  sdk/storage/azure-storage-blobs/vcpkg.json
  sdk/storage/azure-storage-blobs/vcpkg/Config.cmake.in
  sdk/storage/azure-storage-blobs/vcpkg/vcpkg.json
  sdk/storage/azure-storage-common/CHANGELOG.md
  sdk/storage/azure-storage-common/src/private/package_version.hpp
  sdk/storage/azure-storage-common/vcpkg.json
Labels: Client, Storage

#3696 Override live test location default to westus
  eng/pipelines/templates/stages/archetype-sdk-client.yml
Labels: Central-EngSys

#3731 Sync eng/common directory with azure-sdk-tools for PR 3433
  eng/common/pipelines/templates/steps/create-apireview.yml
Labels: EngSys, Central-EngSys

#3655 Sync eng/common directory with azure-sdk-tools for PR 3267
  eng/common/scripts/Helpers/Metadata-Helpers.ps1
  eng/common/scripts/Helpers/Package-Helpers.ps1
  eng/common/scripts/Service-Level-Readme-Automation.ps1
  eng/common/scripts/common.ps1
Labels: EngSys, Central-EngSys

#3715 Update DistributedTracing.md
  doc/DistributedTracing.md
Labels: Docs

#3711 ApiView command line generation script
  eng/scripts/Get-ApiViewCommandLine.ps1
Labels: EngSys

#3739 Add missing license header to http_sanitizer source file
  sdk/core/azure-core/src/http/http_sanitizer.cpp
Labels: Azure.Core

#3740 Sync eng/common directory with azure-sdk-tools for PR 3457
  eng/common/TestResources/New-TestResources.ps1
  eng/common/TestResources/Remove-TestResources.ps1
  eng/common/TestResources/deploy-test-resources.yml
  eng/common/TestResources/remove-test-resources.yml
Labels: EngSys, Central-EngSys

#3744 Update identity codeowners
  .github/CODEOWNERS
Labels: EngSys, Azure.Identity

#3742 Storage Transfer Manager: Job Engine Implementation
  sdk/storage/azure-storage-datamovement/CMakeLists.txt
  sdk/storage/azure-storage-datamovement/inc/azure/storage/datamovement/blob_folder.hpp
  sdk/storage/azure-storage-datamovement/inc/azure/storage/datamovement/datamovement_options.hpp
  sdk/storage/azure-storage-datamovement/inc/azure/storage/datamovement/directory_iterator.hpp
  sdk/storage/azure-storage-datamovement/inc/azure/storage/datamovement/filesystem.hpp
  sdk/storage/azure-storage-datamovement/inc/azure/storage/datamovement/job_engine.hpp
  sdk/storage/azure-storage-datamovement/inc/azure/storage/datamovement/job_properties.hpp
  sdk/storage/azure-storage-datamovement/inc/azure/storage/datamovement/storage_transfer_manager.hpp
  sdk/storage/azure-storage-datamovement/inc/azure/storage/datamovement/task.hpp
  sdk/storage/azure-storage-datamovement/inc/azure/storage/datamovement/task_shared_status.hpp
  sdk/storage/azure-storage-datamovement/inc/azure/storage/datamovement/tasks/download_blob_directory_task.hpp
  sdk/storage/azure-storage-datamovement/inc/azure/storage/datamovement/tasks/download_blob_to_file_task.hpp
  sdk/storage/azure-storage-datamovement/inc/azure/storage/datamovement/tasks/upload_blob_from_file_task.hpp
  sdk/storage/azure-storage-datamovement/inc/azure/storage/datamovement/tasks/upload_blobs_from_directory_task.hpp
  sdk/storage/azure-storage-datamovement/inc/azure/storage/datamovement/transfer_engine.hpp
  sdk/storage/azure-storage-datamovement/inc/azure/storage/datamovement/utilities.hpp
  sdk/storage/azure-storage-datamovement/samples/datamovement_getting_started.cpp
  sdk/storage/azure-storage-datamovement/src/blob_folder.cpp
  sdk/storage/azure-storage-datamovement/src/blob_transfer_manager.cpp
  sdk/storage/azure-storage-datamovement/src/directory_iterator.cpp
  sdk/storage/azure-storage-datamovement/src/filesystem.cpp
  sdk/storage/azure-storage-datamovement/src/job_engine.cpp
  sdk/storage/azure-storage-datamovement/src/job_engine_serialization.cpp
  sdk/storage/azure-storage-datamovement/src/job_engine_task_generation.cpp
  sdk/storage/azure-storage-datamovement/src/job_properties.cpp
  sdk/storage/azure-storage-datamovement/src/storage_transfer_manager.cpp
  sdk/storage/azure-storage-datamovement/src/task_shared_status.cpp
  sdk/storage/azure-storage-datamovement/src/tasks/download_blob_directory_task.cpp
  sdk/storage/azure-storage-datamovement/src/tasks/download_blob_to_file_task.cpp
  sdk/storage/azure-storage-datamovement/src/tasks/upload_blob_from_file_task.cpp
  sdk/storage/azure-storage-datamovement/src/tasks/upload_blobs_from_directory_task.cpp
  sdk/storage/azure-storage-datamovement/src/transfer_engine.cpp
  sdk/storage/azure-storage-datamovement/src/utilities.cpp
  sdk/storage/azure-storage-datamovement/test/ut/blob_transfer_manager_download_test.cpp
  sdk/storage/azure-storage-datamovement/test/ut/blob_transfer_manager_test.cpp
  sdk/storage/azure-storage-datamovement/test/ut/blob_transfer_manager_upload_test.cpp
Labels: Client, Storage

#3734 ManagedIdentityCredential: Add support for AppServiceV2019
  sdk/identity/azure-identity/CHANGELOG.md
  sdk/identity/azure-identity/src/managed_identity_credential.cpp
  sdk/identity/azure-identity/src/managed_identity_source.cpp
  sdk/identity/azure-identity/src/private/managed_identity_source.hpp
  sdk/identity/azure-identity/test/ut/managed_identity_credential_test.cpp
Labels: Azure.Identity

#3758 Sync eng/common directory with azure-sdk-tools for PR 3453
  eng/common/scripts/Verify-Resource-Ref.ps1
Labels: EngSys, Central-EngSys

#3764 Sync eng/common directory with azure-sdk-tools for PR 3481
  eng/common/scripts/Helpers/PSModule-Helpers.ps1
  eng/common/scripts/common.ps1
  eng/common/scripts/stress-testing/deploy-stress-tests.ps1
  eng/common/scripts/stress-testing/find-all-stress-packages.ps1
  eng/common/scripts/stress-testing/stress-test-deployment-lib.ps1
Labels: EngSys, Central-EngSys

#3763 Add auto apiview review creation
  eng/pipelines/templates/jobs/archetype-sdk-client.yml
  eng/scripts/Create-APIReview.ps1
  eng/scripts/Language-Settings.ps1
  sdk/core/ci.yml
Labels: Central-EngSys

#3778 Sync eng/common directory with azure-sdk-tools for PR 3510
  eng/common/pipelines/templates/steps/verify-readme.yml
  eng/common/scripts/Verify-Readme.ps1
Labels: EngSys, Central-EngSys

#3781 Sync eng/common directory with azure-sdk-tools for PR 3491
  eng/common/scripts/stress-testing/stress-test-deployment-lib.ps1
Labels: EngSys, Central-EngSys

#3776 Azure Storage Blob Batch
  sdk/storage/azure-storage-blobs/CHANGELOG.md
  sdk/storage/azure-storage-blobs/CMakeLists.txt
  sdk/storage/azure-storage-blobs/inc/azure/storage/blobs.hpp
  sdk/storage/azure-storage-blobs/inc/azure/storage/blobs/blob_batch.hpp
  sdk/storage/azure-storage-blobs/inc/azure/storage/blobs/blob_client.hpp
  sdk/storage/azure-storage-blobs/inc/azure/storage/blobs/blob_container_client.hpp
  sdk/storage/azure-storage-blobs/inc/azure/storage/blobs/blob_options.hpp
  sdk/storage/azure-storage-blobs/inc/azure/storage/blobs/blob_responses.hpp
  sdk/storage/azure-storage-blobs/inc/azure/storage/blobs/blob_service_client.hpp
  sdk/storage/azure-storage-blobs/inc/azure/storage/blobs/deferred_response.hpp
  sdk/storage/azure-storage-blobs/src/blob_batch.cpp
  sdk/storage/azure-storage-blobs/src/blob_container_client.cpp
  sdk/storage/azure-storage-blobs/src/blob_service_client.cpp
  sdk/storage/azure-storage-blobs/test/ut/CMakeLists.txt
  sdk/storage/azure-storage-blobs/test/ut/blob_batch_client_test.cpp
  sdk/storage/azure-storage-blobs/test/ut/recordings/BlobBatchClientTest.exceptions.json
  sdk/storage/azure-storage-blobs/test/ut/recordings/BlobBatchClientTest.submitdeletebatch.json
  sdk/storage/azure-storage-blobs/test/ut/recordings/BlobBatchClientTest.tokenauthorization.json
Labels: Client, Storage
