Repository Azure/azure-sdk-for-cpp, pull requests merged in 2022-12, with the labels that each got.

#4148 Sync eng/common directory with azure-sdk-tools for PR 4856
  eng/common/pipelines/templates/steps/publish-artifact.yml
Labels: EngSys, Central-EngSys

#4146 AzureCliCredential
  sdk/core/azure-core/inc/azure/core/internal/unique_handle.hpp
  sdk/identity/azure-identity/CHANGELOG.md
  sdk/identity/azure-identity/CMakeLists.txt
  sdk/identity/azure-identity/inc/azure/identity.hpp
  sdk/identity/azure-identity/inc/azure/identity/azure_cli_credential.hpp
  sdk/identity/azure-identity/inc/azure/identity/client_secret_credential.hpp
  sdk/identity/azure-identity/inc/azure/identity/environment_credential.hpp
  sdk/identity/azure-identity/samples/CMakeLists.txt
  sdk/identity/azure-identity/samples/azure_cli_credential.cpp
  sdk/identity/azure-identity/src/azure_cli_credential.cpp
  sdk/identity/azure-identity/src/client_secret_credential.cpp
  sdk/identity/azure-identity/src/private/token_cache_internals.hpp
  sdk/identity/azure-identity/src/private/token_credential_impl.hpp
  sdk/identity/azure-identity/src/token_credential_impl.cpp
  sdk/identity/azure-identity/test/ut/CMakeLists.txt
  sdk/identity/azure-identity/test/ut/azure_cli_credential_test.cpp
  sdk/identity/azure-identity/test/ut/token_credential_impl_test.cpp
Labels: Azure.Identity

#4156 Sync eng/common directory with azure-sdk-tools for PR 4878
  eng/common/pipelines/templates/jobs/perf.yml
Labels: EngSys, Central-EngSys

#4158 Add private interface to disable reliable stream
  sdk/storage/azure-storage-common/src/reliable_stream.cpp
Labels: Client, Storage

#4165 AzureCliCredential: use --scope
  sdk/identity/azure-identity/inc/azure/identity/azure_cli_credential.hpp
  sdk/identity/azure-identity/src/azure_cli_credential.cpp
  sdk/identity/azure-identity/test/ut/azure_cli_credential_test.cpp
Labels: Azure.Identity

#4164 Update ChainedTokenCredential sample to use AzureCliCredential
  sdk/identity/azure-identity/samples/chained_token_credential.cpp
Labels: Azure.Identity

#4167 Use nlohmann::json to parse Identity token
  sdk/identity/azure-identity/src/token_credential_impl.cpp
  sdk/identity/azure-identity/test/ut/azure_cli_credential_test.cpp
  sdk/identity/azure-identity/test/ut/token_credential_impl_test.cpp
Labels: Azure.Identity

#4169 Better TokenRequestContext initialization
  sdk/attestation/azure-security-attestation/src/attestation_administration_client.cpp
  sdk/attestation/azure-security-attestation/src/attestation_client.cpp
  sdk/core/azure-core/test/ut/bearer_token_authentication_policy_test.cpp
  sdk/identity/azure-identity/test/e2e/azure_identity_e2e_test.cpp
  sdk/identity/azure-identity/test/ut/token_credential_impl_test.cpp
  sdk/keyvault/azure-security-keyvault-certificates/src/certificate_client.cpp
  sdk/keyvault/azure-security-keyvault-keys/src/cryptography/cryptography_client.cpp
  sdk/keyvault/azure-security-keyvault-keys/src/key_client.cpp
  sdk/keyvault/azure-security-keyvault-secrets/src/secret_client.cpp
Labels: Azure.Identity

#4160 Per-credential-instance token cache
  sdk/identity/azure-identity/CHANGELOG.md
  sdk/identity/azure-identity/CMakeLists.txt
  sdk/identity/azure-identity/inc/azure/identity/azure_cli_credential.hpp
  sdk/identity/azure-identity/inc/azure/identity/client_certificate_credential.hpp
  sdk/identity/azure-identity/inc/azure/identity/client_secret_credential.hpp
  sdk/identity/azure-identity/inc/azure/identity/detail/token_cache.hpp
  sdk/identity/azure-identity/src/azure_cli_credential.cpp
  sdk/identity/azure-identity/src/client_certificate_credential.cpp
  sdk/identity/azure-identity/src/client_secret_credential.cpp
  sdk/identity/azure-identity/src/managed_identity_source.cpp
  sdk/identity/azure-identity/src/private/managed_identity_source.hpp
  sdk/identity/azure-identity/src/private/token_cache_internals.hpp
  sdk/identity/azure-identity/src/token_cache.cpp
  sdk/identity/azure-identity/test/ut/client_secret_credential_test.cpp
  sdk/identity/azure-identity/test/ut/credential_test_helper.cpp
  sdk/identity/azure-identity/test/ut/credential_test_helper.hpp
  sdk/identity/azure-identity/test/ut/environment_credential_test.cpp
  sdk/identity/azure-identity/test/ut/managed_identity_credential_test.cpp
  sdk/identity/azure-identity/test/ut/token_cache_test.cpp
  sdk/identity/azure-identity/test/ut/token_credential_impl_test.cpp
  sdk/identity/azure-identity/test/ut/token_credential_test.cpp
Labels: Azure.Identity

#4175 Sync eng/common directory with azure-sdk-tools for PR 4813
  eng/common/scripts/Helpers/ApiView-Helpers.ps1
Labels: EngSys, Central-EngSys

#4182 fix #740
  sdk/storage/azure-storage-files-shares/test/ut/share_service_client_test.cpp
Labels: Storage

#4184 Add support for space character instead of 'T' when parsing RFC3339 DateTimes
  sdk/core/azure-core/CHANGELOG.md
  sdk/core/azure-core/src/datetime.cpp
  sdk/core/azure-core/test/ut/datetime_test.cpp
  sdk/identity/azure-identity/src/token_credential_impl.cpp
Labels: Azure.Core

#4185 Sync eng/common directory with azure-sdk-tools for PR 4930
  eng/common/pipelines/templates/jobs/prepare-pipelines.yml
  eng/common/pipelines/templates/steps/prepare-pipelines.yml
Labels: EngSys, Central-EngSys

#4181 ClientCertificateCredential: Add AuthorityHost override and Azure Stack support
  .vscode/cspell.json
  sdk/identity/azure-identity/CHANGELOG.md
  sdk/identity/azure-identity/CMakeLists.txt
  sdk/identity/azure-identity/inc/azure/identity/client_certificate_credential.hpp
  sdk/identity/azure-identity/inc/azure/identity/client_secret_credential.hpp
  sdk/identity/azure-identity/inc/azure/identity/detail/client_credential_core.hpp
  sdk/identity/azure-identity/inc/azure/identity/environment_credential.hpp
  sdk/identity/azure-identity/src/azure_cli_credential.cpp
  sdk/identity/azure-identity/src/client_certificate_credential.cpp
  sdk/identity/azure-identity/src/client_credential_core.cpp
  sdk/identity/azure-identity/src/client_secret_credential.cpp
  sdk/identity/azure-identity/src/environment_credential.cpp
  sdk/identity/azure-identity/test/ut/client_certificate_credential_test.cpp
Labels: Azure.Identity, Azure Stack

#4187 Update prepare-pipelines.yml to use the new jobs-based template
  eng/pipelines/prepare-pipelines.yml
Labels: Central-EngSys

#4191 Sync eng/common directory with azure-sdk-tools for PR 4944
  eng/common/scripts/stress-testing/deploy-stress-tests.ps1
  eng/common/scripts/stress-testing/stress-test-deployment-lib.ps1
Labels: EngSys, Central-EngSys

#4190 Sync eng/common directory with azure-sdk-tools for PR 4514
  eng/common/scripts/Verify-AgentOS.ps1
Labels: EngSys, Central-EngSys

#4193 Sync eng/common directory with azure-sdk-tools for PR 4962
  eng/common/pipelines/templates/jobs/prepare-pipelines.yml
Labels: EngSys, Central-EngSys

#4192 Sync eng/common directory with azure-sdk-tools for PR 4940
  eng/common/scripts/Test-SampleMetadata.ps1
Labels: EngSys, Central-EngSys

#4202 Sync eng/common directory with azure-sdk-tools for PR 4988
  eng/common/pipelines/templates/steps/install-pipeline-generation.yml
  eng/common/pipelines/templates/steps/prepare-pipelines.yml
  eng/common/scripts/get-codeowners.ps1
Labels: EngSys, Central-EngSys

#4205 Sync eng/common directory with azure-sdk-tools for PR 4998
  eng/common/pipelines/templates/jobs/prepare-pipelines.yml
  eng/common/pipelines/templates/steps/install-pipeline-generation.yml
Labels: EngSys, Central-EngSys

#4203 Sync eng/common directory with azure-sdk-tools for PR 4880
  eng/common/pipelines/templates/jobs/docindex.yml
  eng/common/scripts/job-matrix/README.md
  eng/common/scripts/job-matrix/samples/matrix.json
  eng/common/scripts/job-matrix/tests/job-matrix-functions.filter.tests.ps1
  eng/common/scripts/job-matrix/tests/job-matrix-functions.modification.tests.ps1
  eng/common/scripts/job-matrix/tests/job-matrix-functions.tests.ps1
Labels: EngSys, Central-EngSys

#4207 Update prepare-pipelines flags
  eng/pipelines/prepare-pipelines.yml
Labels: Central-EngSys

#4209 Sync eng/common directory with azure-sdk-tools for PR 4985
  eng/common/scripts/Helpers/Package-Helpers.ps1
  eng/common/scripts/Update-DocsMsMetadata.ps1
  eng/common/scripts/Update-DocsMsPackages.ps1
  eng/common/scripts/common.ps1
Labels: EngSys, Central-EngSys
