Repository Azure/azure-sdk-for-cpp, pull requests merged in 2022-03, with the labels that each got.

#3385 Sync eng/common directory with azure-sdk-tools for PR 2833
  eng/common/pipelines/templates/steps/detect-api-changes.yml
  eng/common/scripts/Detect-Api-Changes.ps1
Labels: EngSys, Central-EngSys

#3387 Sync eng/common directory with azure-sdk-tools for PR 2823
  eng/common/testproxy/docker-start-proxy.ps1
  eng/common/testproxy/target_version.txt
  eng/common/testproxy/test-proxy-docker.yml
  eng/common/testproxy/test-proxy-tool.yml
Labels: EngSys, Central-EngSys

#3383 Sync eng/common directory with azure-sdk-tools for PR 2830
  eng/common/pipelines/templates/steps/cosmos-emulator.yml
  eng/common/scripts/Cosmos-Emulator.ps1
Labels: EngSys, Central-EngSys

#3389 Sync eng/common directory with azure-sdk-tools for PR 2824
  eng/common/scripts/git-diff-changes.ps1
Labels: EngSys, Central-EngSys

#3390 Azure Core change log for March release
  sdk/core/azure-core/CHANGELOG.md
  sdk/core/azure-core/src/private/package_version.hpp
Labels: Docs, Azure.Core

#3396 Sync eng/common directory with azure-sdk-tools for PR 2875
  eng/common/pipelines/templates/steps/detect-api-changes.yml
  eng/common/scripts/Detect-Api-Changes.ps1
Labels: EngSys, Central-EngSys

#3399 SAS token version related change
  sdk/storage/azure-storage-common/inc/azure/storage/common/internal/constants.hpp
  sdk/storage/azure-storage-queues/CHANGELOG.md
  sdk/storage/azure-storage-queues/src/queue_sas_builder.cpp
Labels: Client, Storage

#3386 Readme and dependency version updates for stable Identity release
  sdk/identity/azure-identity/CHANGELOG.md
  sdk/identity/azure-identity/vcpkg/Config.cmake.in
  sdk/identity/azure-identity/vcpkg/vcpkg.json
Labels: Azure.Identity

#3400 Storage Mar. Release
  cmake-modules/FolderList.cmake
  eng/vcpkg-commit.txt
  sdk/storage/azure-storage-blobs/CHANGELOG.md
  sdk/storage/azure-storage-blobs/CMakeLists.txt
  sdk/storage/azure-storage-blobs/vcpkg/Config.cmake.in
  sdk/storage/azure-storage-blobs/vcpkg/vcpkg.json
  sdk/storage/azure-storage-common/CHANGELOG.md
  sdk/storage/azure-storage-common/src/private/package_version.hpp
  sdk/storage/azure-storage-files-datalake/CHANGELOG.md
  sdk/storage/azure-storage-files-datalake/src/private/package_version.hpp
  sdk/storage/azure-storage-files-shares/CHANGELOG.md
  sdk/storage/azure-storage-files-shares/CMakeLists.txt
  sdk/storage/azure-storage-files-shares/src/private/package_version.hpp
  sdk/storage/azure-storage-files-shares/vcpkg/Config.cmake.in
  sdk/storage/azure-storage-files-shares/vcpkg/vcpkg.json
  sdk/storage/azure-storage-queues/CHANGELOG.md
  sdk/storage/azure-storage-queues/CMakeLists.txt
  sdk/storage/azure-storage-queues/vcpkg/Config.cmake.in
  sdk/storage/azure-storage-queues/vcpkg/vcpkg.json
Labels: Client, Storage

#3373 Sync eng/common directory with azure-sdk-tools for PR 2810
  eng/common/TestResources/New-TestResources.ps1
  eng/common/TestResources/SubConfig-Helpers.ps1
Labels: EngSys, Central-EngSys

#3408 Sync eng/common directory with azure-sdk-tools for PR 2889
  eng/common/TestResources/New-TestResources.ps1
Labels: EngSys, Central-EngSys

#3416 Sync eng/common directory with azure-sdk-tools for PR 2892
  eng/common/scripts/stress-testing/deploy-stress-tests.ps1
  eng/common/scripts/stress-testing/find-all-stress-packages.ps1
  eng/common/scripts/stress-testing/stress-test-deployment-lib.ps1
Labels: EngSys, Central-EngSys

#3391 Increment version for core releases
  sdk/core/azure-core/CHANGELOG.md
  sdk/core/azure-core/src/private/package_version.hpp
Labels: Azure.Core

#3388 Sync eng/common directory with azure-sdk-tools for PR 2836
  eng/common/scripts/ChangeLog-Operations.ps1
Labels: EngSys, Central-EngSys

#3415 Increment version for storage releases
  sdk/storage/azure-storage-blobs/CHANGELOG.md
  sdk/storage/azure-storage-blobs/src/private/package_version.hpp
Labels: Storage

#3412 Increment version for identity releases
  sdk/identity/azure-identity/CHANGELOG.md
  sdk/identity/azure-identity/src/private/package_version.hpp
Labels: Azure.Identity

#3406 Increment version for keyvault releases
  sdk/keyvault/azure-security-keyvault-certificates/CHANGELOG.md
  sdk/keyvault/azure-security-keyvault-certificates/src/private/package_version.hpp
  sdk/keyvault/azure-security-keyvault-secrets/CHANGELOG.md
  sdk/keyvault/azure-security-keyvault-secrets/src/private/package_version.hpp
Labels: KeyVault

#3413 Increment version for storage releases
  sdk/storage/azure-storage-common/CHANGELOG.md
  sdk/storage/azure-storage-common/src/private/package_version.hpp
  sdk/storage/azure-storage-files-datalake/CHANGELOG.md
  sdk/storage/azure-storage-files-datalake/src/private/package_version.hpp
  sdk/storage/azure-storage-files-shares/CHANGELOG.md
  sdk/storage/azure-storage-files-shares/src/private/package_version.hpp
  sdk/storage/azure-storage-queues/CHANGELOG.md
  sdk/storage/azure-storage-queues/src/private/package_version.hpp
Labels: Storage

#3419 Sync eng/common directory with azure-sdk-tools for PR 2899
  eng/common/scripts/ChangeLog-Operations.ps1
Labels: EngSys, Central-EngSys

#3420 Add missing header
  sdk/storage/azure-storage-blobs/inc/azure/storage/blobs/blob_responses.hpp
  sdk/storage/azure-storage-files-shares/inc/azure/storage/files/shares/share_responses.hpp
Labels: Client, Storage

#3421 Create Extendable Enumeration base class
  sdk/attestation/azure-security-attestation/inc/azure/attestation/attestation_client_models.hpp
  sdk/attestation/azure-security-attestation/test/samples/policy/policy.cpp
  sdk/attestation/azure-security-attestation/test/ut/policygetset_test.cpp
  sdk/core/azure-core/CMakeLists.txt
  sdk/core/azure-core/inc/azure/core/internal/extendable_enumeration.hpp
  sdk/core/azure-core/test/ut/CMakeLists.txt
  sdk/core/azure-core/test/ut/extendable_enumeration_test.cpp
Labels: Azure.Core

#3397 RequestFailedException includes error information #3398
  sdk/core/azure-core/CHANGELOG.md
  sdk/core/azure-core/inc/azure/core/exception.hpp
  sdk/core/azure-core/src/exception.cpp
  sdk/core/azure-core/test/ut/exception_test.cpp
Labels: Azure.Core

#3257 Adding Test-Proxy support to [Perf Fw] tests
  sdk/core/perf/CMakeLists.txt
  sdk/core/perf/inc/azure/perf/base_test.hpp
  sdk/core/perf/inc/azure/perf/options.hpp
  sdk/core/perf/inc/azure/perf/test.hpp
  sdk/core/perf/inc/azure/perf/test_options.hpp
  sdk/core/perf/src/arg_parser.cpp
  sdk/core/perf/src/base_test.cpp
  sdk/core/perf/src/options.cpp
  sdk/core/perf/src/program.cpp
  sdk/identity/azure-identity/test/perf/inc/azure/identity/test/secret_credential_test.hpp
  sdk/keyvault/azure-security-keyvault-keys/test/perf/inc/azure/keyvault/keys/test/get_key_test.hpp
  sdk/storage/azure-storage-blobs/test/perf/inc/azure/storage/blobs/test/blob_base_test.hpp
Labels: pillar-performance

#3423 Sync eng/common directory with azure-sdk-tools for PR 2910
  eng/common/scripts/Update-DocsMsMetadata.ps1
Labels: EngSys, Central-EngSys

#3433 Sync eng/common directory with azure-sdk-tools for PR 2913
  eng/common/pipelines/templates/jobs/archetype-sdk-tests-generate.yml
  eng/common/scripts/job-matrix/README.md
Labels: EngSys, Central-EngSys

#3435 Sync eng/common directory with azure-sdk-tools for PR 2870
  eng/common/pipelines/templates/jobs/archetype-sdk-tests-generate.yml
Labels: EngSys, Central-EngSys

#3436 Sync eng/common directory with azure-sdk-tools for PR 2866
  eng/common/TestResources/New-TestResources.ps1
Labels: EngSys, Central-EngSys

#3437 Sync eng/common directory with azure-sdk-tools for PR 2901
  eng/common/pipelines/templates/steps/credscan.yml
Labels: EngSys, Central-EngSys

#3441 Sync eng/common directory with azure-sdk-tools for PR 2922
  eng/common/scripts/Update-DocsMsToc.ps1
Labels: EngSys, Central-EngSys

#3455 Sync eng/common directory with azure-sdk-tools for PR 2847
  eng/common/scripts/Helpers/Metadata-Helpers.ps1
  eng/common/scripts/Import-AzModules.ps1
  eng/common/scripts/Update-DocsMsMetadata.ps1
Labels: EngSys, Central-EngSys

#3456 Improve the Transport exception from Libcurl adapter
  sdk/core/azure-core/CHANGELOG.md
  sdk/core/azure-core/src/http/curl/curl.cpp
  sdk/core/azure-core/test/ut/curl_connection_pool_test.cpp
Labels: Azure.Core

#3434 [PERF FW] Insecure cert libcurl
  sdk/core/azure-core/CHANGELOG.md
  sdk/core/azure-core/inc/azure/core/http/win_http_transport.hpp
  sdk/core/azure-core/src/http/winhttp/win_http_transport.cpp
  sdk/core/perf/inc/azure/perf/base_test.hpp
  sdk/core/perf/src/arg_parser.cpp
  sdk/core/perf/src/base_test.cpp
  sdk/core/perf/src/options.cpp
  sdk/core/perf/src/program.cpp
Labels: pillar-performance

#3451 Update release mode windows + samples
  cmake-modules/AzureBuildTargetForCI.cmake
  eng/pipelines/templates/jobs/archetype-sdk-tests.yml
  samples/integration/vcpkg-all-smoke/CMakeLists.txt
  sdk/attestation/azure-security-attestation/CMakeLists.txt
  sdk/attestation/azure-security-attestation/test/samples/attestation/CMakeLists.txt
  sdk/attestation/azure-security-attestation/test/samples/basic-operations/CMakeLists.txt
  sdk/attestation/azure-security-attestation/test/samples/policy/CMakeLists.txt
  sdk/attestation/azure-security-attestation/test/ut/CMakeLists.txt
  sdk/identity/azure-identity/CMakeLists.txt
  sdk/identity/azure-identity/samples/CMakeLists.txt
  sdk/identity/azure-identity/test/e2e/CMakeLists.txt
  sdk/identity/azure-identity/test/perf/CMakeLists.txt
  sdk/identity/azure-identity/test/ut/CMakeLists.txt
  sdk/keyvault/azure-security-keyvault-certificates/CMakeLists.txt
  sdk/keyvault/azure-security-keyvault-certificates/test/samples/certificate-basic-operations/CMakeLists.txt
  sdk/keyvault/azure-security-keyvault-certificates/test/samples/certificate-get-certificates/CMakeLists.txt
  sdk/keyvault/azure-security-keyvault-certificates/test/samples/certificate-import-certificate/CMakeLists.txt
  sdk/keyvault/azure-security-keyvault-certificates/test/ut/CMakeLists.txt
  sdk/keyvault/azure-security-keyvault-keys/CMakeLists.txt
  sdk/keyvault/azure-security-keyvault-keys/test/perf/CMakeLists.txt
  sdk/keyvault/azure-security-keyvault-keys/test/samples/sample1-hello-world/CMakeLists.txt
  sdk/keyvault/azure-security-keyvault-keys/test/samples/sample2-backup-and-restore/CMakeLists.txt
  sdk/keyvault/azure-security-keyvault-keys/test/samples/sample3-get-keys/CMakeLists.txt
  sdk/keyvault/azure-security-keyvault-keys/test/samples/sample4-encrypt-decrypt/CMakeLists.txt
  sdk/keyvault/azure-security-keyvault-keys/test/samples/sample5-sign-verify/CMakeLists.txt
  sdk/keyvault/azure-security-keyvault-keys/test/samples/sample6-wrap-unwrap/CMakeLists.txt
  sdk/keyvault/azure-security-keyvault-keys/test/ut/CMakeLists.txt
  sdk/keyvault/azure-security-keyvault-secrets/CMakeLists.txt
  sdk/keyvault/azure-security-keyvault-secrets/test/samples/sample1-basic-operations/CMakeLists.txt
  sdk/keyvault/azure-security-keyvault-secrets/test/samples/sample2-backup-restore/CMakeLists.txt
  sdk/keyvault/azure-security-keyvault-secrets/test/samples/sample3-delete-recover/CMakeLists.txt
  sdk/keyvault/azure-security-keyvault-secrets/test/samples/sample4-get-secrets-deleted/CMakeLists.txt
  sdk/keyvault/azure-security-keyvault-secrets/test/test-app/CMakeLists.txt
  sdk/keyvault/azure-security-keyvault-secrets/test/ut/CMakeLists.txt
  sdk/storage/azure-storage-blobs/CMakeLists.txt
  sdk/storage/azure-storage-blobs/samples/CMakeLists.txt
  sdk/storage/azure-storage-blobs/test/fault-injector/CMakeLists.txt
  sdk/storage/azure-storage-blobs/test/perf/CMakeLists.txt
  sdk/storage/azure-storage-blobs/test/ut/CMakeLists.txt
  sdk/storage/azure-storage-common/CMakeLists.txt
  sdk/storage/azure-storage-common/test/ut/CMakeLists.txt
  sdk/storage/azure-storage-files-datalake/CMakeLists.txt
  sdk/storage/azure-storage-files-datalake/samples/CMakeLists.txt
  sdk/storage/azure-storage-files-datalake/samples/datalake_getting_started.cpp
  sdk/storage/azure-storage-files-datalake/test/ut/CMakeLists.txt
  sdk/storage/azure-storage-files-shares/CMakeLists.txt
  sdk/storage/azure-storage-files-shares/samples/CMakeLists.txt
  sdk/storage/azure-storage-files-shares/test/ut/CMakeLists.txt
  sdk/storage/azure-storage-queues/CMakeLists.txt
  sdk/storage/azure-storage-queues/samples/CMakeLists.txt
  sdk/storage/azure-storage-queues/test/ut/CMakeLists.txt
  sdk/storage/test-resources.json
  sdk/template/azure-template/CMakeLists.txt
  sdk/template/azure-template/test/CMakeLists.txt
Labels: Azure.Core, Client, EngSys

#3458 Sync eng/common directory with azure-sdk-tools for PR 2928
  eng/common/scripts/Update-DocsMsToc.ps1
Labels: EngSys, Central-EngSys

#3463 [Perf ] Only set `insecure mode` when option insecure is true
  sdk/core/perf/src/base_test.cpp
Labels: pillar-performance

#3460 Enforce TLS 1.2 for libcurl and winHttp
  doc/HttpTransportAdapter.md
  sdk/core/azure-core/CHANGELOG.md
  sdk/core/azure-core/src/http/curl/curl.cpp
  sdk/core/azure-core/src/http/winhttp/win_http_transport.cpp
Labels: Azure.Core, Client

#3468 Sync eng/common directory with azure-sdk-tools for PR 2939
  eng/common/scripts/Update-DocsMsToc.ps1
Labels: EngSys, Central-EngSys

#3472 Sync eng/common directory with azure-sdk-tools for PR 2938
  eng/common/scripts/Update-DocsMsToc.ps1
Labels: EngSys, Central-EngSys

#3425 Sync eng/common directory with azure-sdk-tools for PR 2861
  eng/common/pipelines/templates/steps/credscan.yml
  eng/common/pipelines/templates/steps/eng-common-workflow-enforcer.yml
  eng/common/scripts/Detect-Api-Changes.ps1
  eng/common/scripts/Helpers/git-helpers.ps1
  eng/common/scripts/check-spelling-in-changed-files.ps1
  eng/common/scripts/common.ps1
  eng/common/scripts/get-changedfiles.ps1
  eng/common/scripts/get-markdown-files-from-changed-files.ps1
  eng/common/scripts/git-diff-changes.ps1
Labels: EngSys, Central-EngSys

#3469 Update migration guide, add sample for wraping sync into async
  sdk/storage/MigrationGuide.md
Labels: Client, Storage

#3474 Sync eng/common directory with azure-sdk-tools for PR 2972
  eng/common/pipelines/templates/steps/eng-common-workflow-enforcer.yml
  eng/common/scripts/Helpers/git-helpers.ps1
Labels: EngSys, Central-EngSys

#3467 remove amalgamate form CGManifest
  sdk/storage/azure-storage-blobs/NOTICE.txt
  sdk/storage/azure-storage-blobs/cgmanifest.json
  sdk/storage/azure-storage-common/NOTICE.txt
  sdk/storage/azure-storage-common/cgmanifest.json
  sdk/storage/azure-storage-files-datalake/NOTICE.txt
  sdk/storage/azure-storage-files-datalake/cgmanifest.json
  sdk/storage/azure-storage-files-shares/NOTICE.txt
  sdk/storage/azure-storage-files-shares/cgmanifest.json
  sdk/storage/azure-storage-queues/NOTICE.txt
  sdk/storage/azure-storage-queues/cgmanifest.json
Labels: Client, Storage

#3487 Sync eng/common directory with azure-sdk-tools for PR 2979
  eng/common/pipelines/templates/steps/check-spelling.yml
  eng/common/scripts/check-spelling-in-changed-files.ps1
Labels: EngSys, Central-EngSys

#3488 Rename winhttp transport option
  sdk/core/azure-core/CHANGELOG.md
  sdk/core/azure-core/inc/azure/core/http/win_http_transport.hpp
  sdk/core/azure-core/src/http/winhttp/win_http_transport.cpp
  sdk/core/perf/src/base_test.cpp
Labels: Azure.Core

#3491 azure-core, changelog for Apr2022 release
  sdk/core/azure-core/CHANGELOG.md
  sdk/core/azure-core/src/private/package_version.hpp
Labels: Azure.Core

#3494 Updated cmakelists to include core 1.5 requirement
  sdk/attestation/azure-security-attestation/CMakeLists.txt
Labels: Attestation
