Repository Azure/azure-sdk-for-cpp, pull requests merged in 2022-09, with the labels that each got.

#3915 Sync eng/common directory with azure-sdk-tools for PR 4041
  eng/common/pipelines/templates/steps/update-docsms-metadata.yml
Labels: EngSys, Central-EngSys

#3916 Sync eng/common directory with azure-sdk-tools for PR 4042
  eng/common/pipelines/templates/steps/docs-metadata-release.yml
  eng/common/pipelines/templates/steps/sparse-checkout.yml
  eng/common/pipelines/templates/steps/update-docsms-metadata.yml
Labels: EngSys, Central-EngSys

#3914 Storage Sept Release
  cmake-modules/FolderList.cmake
  sdk/storage/azure-storage-blobs/CHANGELOG.md
  sdk/storage/azure-storage-blobs/CMakeLists.txt
  sdk/storage/azure-storage-blobs/src/private/package_version.hpp
  sdk/storage/azure-storage-blobs/vcpkg.json
  sdk/storage/azure-storage-blobs/vcpkg/Config.cmake.in
  sdk/storage/azure-storage-blobs/vcpkg/vcpkg.json
  sdk/storage/azure-storage-common/CHANGELOG.md
  sdk/storage/azure-storage-common/src/private/package_version.hpp
  sdk/storage/azure-storage-common/vcpkg.json
  sdk/storage/azure-storage-files-shares/CHANGELOG.md
  sdk/storage/azure-storage-files-shares/CMakeLists.txt
  sdk/storage/azure-storage-files-shares/vcpkg.json
  sdk/storage/azure-storage-files-shares/vcpkg/Config.cmake.in
  sdk/storage/azure-storage-files-shares/vcpkg/vcpkg.json
Labels: Client, Storage

#3922 Add github actions based check enforcer
  .github/workflows/event.yml
Labels: Central-EngSys

#3930 Sync eng/common directory with azure-sdk-tools for PR 4128
  eng/common/pipelines/templates/steps/sparse-checkout.yml
Labels: EngSys, Central-EngSys

#3931 Sync eng/common directory with azure-sdk-tools for PR 4098
  eng/common/testproxy/test-proxy-docker.yml
  eng/common/testproxy/test-proxy-tool.yml
Labels: EngSys, Central-EngSys

#3934 Storage ad-hoc release
  sdk/storage/azure-storage-blobs/CHANGELOG.md
  sdk/storage/azure-storage-blobs/src/private/package_version.hpp
  sdk/storage/azure-storage-blobs/vcpkg.json
Labels: Client, Storage

#3928 Update `AttestationClient::AttestTpm` API to match existing `AttestOpenEnclave` and `AttestSgxmEnclave`
  CONTRIBUTING.md
  sdk/attestation/azure-security-attestation/CHANGELOG.md
  sdk/attestation/azure-security-attestation/inc/azure/attestation/attestation_client.hpp
  sdk/attestation/azure-security-attestation/inc/azure/attestation/attestation_client_models.hpp
  sdk/attestation/azure-security-attestation/inc/azure/attestation/attestation_client_options.hpp
  sdk/attestation/azure-security-attestation/src/attestation_client.cpp
  sdk/attestation/azure-security-attestation/src/private/attestation_deserializers_private.cpp
  sdk/attestation/azure-security-attestation/src/private/attestation_deserializers_private.hpp
  sdk/attestation/azure-security-attestation/test/ut/tpmattestation_test.cpp
Labels: customer-reported

#3944 Update check enforcer yaml permissions and name
  .github/workflows/event.yml
Labels: Central-EngSys

#3949 Sync eng/common directory with azure-sdk-tools for PR 4141
  eng/common/scripts/Helpers/DevOps-WorkItem-Helpers.ps1
  eng/common/scripts/Update-DevOps-Release-WorkItem.ps1
Labels: EngSys, Central-EngSys

#3950 Sync eng/common directory with azure-sdk-tools for PR 4169
  eng/common/testproxy/target_version.txt
Labels: EngSys, Central-EngSys

#3960 Enable Query() test in blob SDK
  sdk/storage/azure-storage-blobs/test/ut/blob_query_test.cpp
Labels: Client, Storage

#3962 Sync eng/common directory with azure-sdk-tools for PR 4212
  eng/common/testproxy/target_version.txt
Labels: EngSys, Central-EngSys

#3967 Win32FileTimeConverter in Storage SDK
  sdk/storage/azure-storage-files-datalake/src/private/datalake_utilities.hpp
Labels: Storage

#3965 Sync eng/common directory with azure-sdk-tools for PR 4240
  eng/common/testproxy/target_version.txt
Labels: EngSys, Central-EngSys

#3970 add test case for batch options on snapshots and versions
  sdk/storage/azure-storage-blobs/test/ut/blob_batch_client_test.cpp
  sdk/storage/azure-storage-blobs/test/ut/recordings/BlobBatchClientTest.snapshotversion.json
Labels: Client, Storage

#3973 Merge feature/datalakestg82
  sdk/storage/azure-storage-blobs/inc/azure/storage/blobs/blob_container_client.hpp
  sdk/storage/azure-storage-blobs/inc/azure/storage/blobs/rest_client.hpp
  sdk/storage/azure-storage-blobs/src/rest_client.cpp
  sdk/storage/azure-storage-blobs/swagger/README.md
  sdk/storage/azure-storage-files-datalake/inc/azure/storage/files/datalake/datalake_directory_client.hpp
  sdk/storage/azure-storage-files-datalake/inc/azure/storage/files/datalake/datalake_file_client.hpp
  sdk/storage/azure-storage-files-datalake/inc/azure/storage/files/datalake/datalake_file_system_client.hpp
  sdk/storage/azure-storage-files-datalake/inc/azure/storage/files/datalake/datalake_options.hpp
  sdk/storage/azure-storage-files-datalake/inc/azure/storage/files/datalake/datalake_path_client.hpp
  sdk/storage/azure-storage-files-datalake/inc/azure/storage/files/datalake/datalake_responses.hpp
  sdk/storage/azure-storage-files-datalake/inc/azure/storage/files/datalake/datalake_sas_builder.hpp
  sdk/storage/azure-storage-files-datalake/inc/azure/storage/files/datalake/datalake_service_client.hpp
  sdk/storage/azure-storage-files-datalake/inc/azure/storage/files/datalake/rest_client.hpp
  sdk/storage/azure-storage-files-datalake/src/datalake_directory_client.cpp
  sdk/storage/azure-storage-files-datalake/src/datalake_file_client.cpp
  sdk/storage/azure-storage-files-datalake/src/datalake_file_system_client.cpp
  sdk/storage/azure-storage-files-datalake/src/datalake_path_client.cpp
  sdk/storage/azure-storage-files-datalake/src/datalake_responses.cpp
  sdk/storage/azure-storage-files-datalake/src/datalake_sas_builder.cpp
  sdk/storage/azure-storage-files-datalake/src/datalake_service_client.cpp
  sdk/storage/azure-storage-files-datalake/src/datalake_utilities.cpp
  sdk/storage/azure-storage-files-datalake/src/rest_client.cpp
  sdk/storage/azure-storage-files-datalake/swagger/README.md
  sdk/storage/azure-storage-files-datalake/test/ut/CMakeLists.txt
  sdk/storage/azure-storage-files-datalake/test/ut/datalake_file_client_test.cpp
  sdk/storage/azure-storage-files-datalake/test/ut/datalake_file_query_test.cpp
  sdk/storage/azure-storage-files-datalake/test/ut/datalake_file_system_client_test.cpp
  sdk/storage/azure-storage-files-datalake/test/ut/datalake_path_client_test.cpp
  sdk/storage/azure-storage-files-datalake/test/ut/datalake_sas_test.cpp
  sdk/storage/azure-storage-files-datalake/test/ut/datalake_service_client_test.cpp
  sdk/storage/azure-storage-files-datalake/test/ut/recordings/DataLakeFileClientTest.AppendFileWithFlush.json
  sdk/storage/azure-storage-files-datalake/test/ut/recordings/DataLakeFileSystemClientTest.ListDeletedPaths.json
  sdk/storage/azure-storage-files-datalake/test/ut/recordings/DataLakeFileSystemClientTest.ListPaths.json
  sdk/storage/azure-storage-files-datalake/test/ut/recordings/DataLakeFileSystemClientTest.Undelete.json
  sdk/storage/azure-storage-files-datalake/test/ut/recordings/DataLakePathClientTest.CreateWithOptions.json
  sdk/storage/azure-storage-files-datalake/test/ut/recordings/DataLakeServiceClientTest.GetProperties.json
  sdk/storage/azure-storage-files-datalake/test/ut/recordings/DataLakeServiceClientTest.ListFileSystemsSegment.json
  sdk/storage/azure-storage-files-datalake/test/ut/recordings/DataLakeServiceClientTest.ListSystemFileSystems.json
  sdk/storage/azure-storage-files-datalake/test/ut/recordings/DataLakeServiceClientTest.SetProperties.json
  sdk/storage/test-resources-post.ps1
  sdk/storage/test-resources.json
Labels: Client, Storage

#3976 Build subscription configuration from cloud config values
  eng/pipelines/templates/jobs/live.tests.yml
Labels: Central-EngSys
