Repository Azure/azure-sdk-for-cpp, pull requests merged in 2022-02, with the labels that each got.

#3296 diable uwp CI gates
  eng/pipelines/templates/stages/platform-matrix.json
Labels: EngSys

#3303 Sync eng/common directory with azure-sdk-tools for PR 2608
  eng/common/pipelines/templates/steps/update-docsms-metadata.yml
  eng/common/scripts/Helpers/Metadata-Helpers.ps1
  eng/common/scripts/Update-DocsMsMetadata.ps1
Labels: EngSys, Central-EngSys

#3302 Sync eng/common directory with azure-sdk-tools for PR 2605
  eng/common/scripts/Update-DocsMsMetadata.ps1
Labels: EngSys, Central-EngSys

#3306 Update README with SDK Beta Vcpkg Registry information
  README.md
Labels: Docs

#3310 Sync eng/common directory with azure-sdk-tools for PR 2673
  eng/common/scripts/Helpers/Metadata-Helpers.ps1
  eng/common/scripts/Update-DocsMsMetadata.ps1
Labels: EngSys, Central-EngSys

#3314 Fix the SDK Beta Vcpkg Registry information to use stable instead of GA
  README.md
Labels: Docs

#3311 Add back azure_assert.hpp to core CMakeLists
  sdk/core/azure-core/CMakeLists.txt
Labels: Azure.Core

#3215 Removing the two param RFE ctor, there should be no callers
  sdk/core/azure-core/CHANGELOG.md
  sdk/core/azure-core/inc/azure/core/exception.hpp
  sdk/core/azure-core/src/exception.cpp
  sdk/core/azure-core/test/ut/exception_test.cpp
Labels: Azure.Core

#3309 Sync eng/common directory with azure-sdk-tools for PR 2668
  eng/common/scripts/artifact-metadata-parsing.ps1
Labels: EngSys, Central-EngSys

#3316 Sync eng/common directory with azure-sdk-tools for PR 2682
  eng/common/scripts/stress-testing/find-all-stress-packages.ps1
Labels: EngSys, Central-EngSys

#3317 Sync eng/common directory with azure-sdk-tools for PR 2685
  eng/common/scripts/Helpers/Metadata-Helpers.ps1
  eng/common/scripts/Update-DocsMsMetadata.ps1
Labels: EngSys, Central-EngSys

#3315 Delegate to RFE string ctor and move impl from header to src.
  sdk/core/azure-core/inc/azure/core/exception.hpp
  sdk/core/azure-core/src/exception.cpp
Labels: Azure.Core

#3307 Azure Core Feb2022 release changelog
  sdk/core/azure-core/CHANGELOG.md
Labels: Docs

#3324 Sync eng/common directory with azure-sdk-tools for PR 2691
  eng/common/scripts/Helpers/DevOps-WorkItem-Helpers.ps1
  eng/common/scripts/Prepare-Release.ps1
Labels: EngSys, Central-EngSys

#3305 Base64::Decode throws std::runtime_error on failure.
  sdk/core/azure-core/CHANGELOG.md
  sdk/core/azure-core/src/base64.cpp
  sdk/core/azure-core/test/ut/base64_test.cpp
  sdk/core/azure-core/test/ut/simplified_header_test.cpp
Labels: Azure.Core

#3323 Increment version for core releases
  sdk/core/azure-core/CHANGELOG.md
  sdk/core/azure-core/src/private/package_version.hpp
Labels: Azure.Core

#3331 Sync eng/common directory with azure-sdk-tools for PR 2686
  eng/common/pipelines/templates/steps/credscan.yml
Labels: EngSys, Central-EngSys

#3332 Sync eng/common directory with azure-sdk-tools for PR 2720
  eng/common/scripts/stress-testing/stress-test-deployment-lib.ps1
Labels: EngSys, Central-EngSys

#3333 Increment version for identity releases
  sdk/identity/azure-identity/CHANGELOG.md
  sdk/identity/azure-identity/src/private/package_version.hpp
Labels: Azure.Identity

#3327 Sync eng/common directory with azure-sdk-tools for PR 2679
  eng/common/TestResources/New-TestResources.ps1
  eng/common/TestResources/Update-TestResources.ps1
Labels: EngSys, Central-EngSys

#3334 Sync eng/common directory with azure-sdk-tools for PR 2721
  eng/common/TestResources/New-TestResources.ps1
Labels: EngSys, Central-EngSys

#3337 Sync eng/common directory with azure-sdk-tools for PR 2733
  eng/common/pipelines/templates/steps/credscan.yml
Labels: EngSys, Central-EngSys

#3338 Sync eng/common directory with azure-sdk-tools for PR 2739
  eng/common/pipelines/templates/steps/credscan.yml
Labels: EngSys, Central-EngSys

#3339 Remove CopyFromUri
  sdk/storage/azure-storage-blobs/CHANGELOG.md
  sdk/storage/azure-storage-blobs/inc/azure/storage/blobs/blob_client.hpp
  sdk/storage/azure-storage-blobs/inc/azure/storage/blobs/blob_options.hpp
  sdk/storage/azure-storage-blobs/inc/azure/storage/blobs/rest_client.hpp
  sdk/storage/azure-storage-blobs/src/blob_client.cpp
  sdk/storage/azure-storage-blobs/src/rest_client.cpp
  sdk/storage/azure-storage-blobs/test/ut/blob_container_client_test.cpp
  sdk/storage/azure-storage-blobs/test/ut/block_blob_client_test.cpp
  sdk/storage/azure-storage-blobs/test/ut/recordings/BlobContainerClientTest.AccessConditionTags.json
  sdk/storage/azure-storage-blobs/test/ut/recordings/BlobContainerClientTest.SourceBlobAccessConditions.json
  sdk/storage/azure-storage-blobs/test/ut/recordings/BlockBlobClientTest.CopyWithTagsMetadataTier.json
  sdk/storage/azure-storage-blobs/test/ut/recordings/BlockBlobClientTest.SyncCopyFromUri.json
Labels: Client, Storage

#3341 Sync eng/common directory with azure-sdk-tools for PR 2740
  eng/common/pipelines/templates/steps/credscan.yml
Labels: EngSys, Central-EngSys

#3340 Storage Feb. Release
  cmake-modules/FolderList.cmake
  sdk/storage/azure-storage-blobs/CHANGELOG.md
  sdk/storage/azure-storage-blobs/CMakeLists.txt
  sdk/storage/azure-storage-blobs/src/private/package_version.hpp
  sdk/storage/azure-storage-blobs/vcpkg/Config.cmake.in
  sdk/storage/azure-storage-blobs/vcpkg/vcpkg.json
  sdk/storage/azure-storage-common/CHANGELOG.md
  sdk/storage/azure-storage-common/CMakeLists.txt
  sdk/storage/azure-storage-common/src/private/package_version.hpp
  sdk/storage/azure-storage-files-datalake/CHANGELOG.md
  sdk/storage/azure-storage-files-datalake/CMakeLists.txt
  sdk/storage/azure-storage-files-datalake/src/private/package_version.hpp
  sdk/storage/azure-storage-files-datalake/vcpkg/Config.cmake.in
  sdk/storage/azure-storage-files-datalake/vcpkg/vcpkg.json
  sdk/storage/azure-storage-queues/CHANGELOG.md
  sdk/storage/azure-storage-queues/CMakeLists.txt
  sdk/storage/azure-storage-queues/vcpkg/Config.cmake.in
  sdk/storage/azure-storage-queues/vcpkg/vcpkg.json
Labels: Client, Storage

#3346 Sync eng/common directory with azure-sdk-tools for PR 2754
  eng/common/pipelines/templates/steps/credscan.yml
Labels: EngSys, Central-EngSys

#3343 Sync eng/common directory with azure-sdk-tools for PR 2741
  eng/common/TestResources/New-TestResources.ps1
Labels: EngSys, Central-EngSys

#3345 Sync eng/common directory with azure-sdk-tools for PR 2758
  eng/common/testproxy/docker-start-proxy.ps1
  eng/common/testproxy/test-proxy-tool.yml
Labels: EngSys, Central-EngSys

#3351 Increment gTest version to get rid of warning during cmake-configure
  cmake-modules/AddGoogleTest.cmake
  sdk/core/azure-core/cgmanifest.json
  sdk/storage/azure-storage-files-shares/test/ut/share_file_client_test.cpp
Labels: Azure.Core, Client

#3348 Sync eng/common directory with azure-sdk-tools for PR 2759
  eng/common/scripts/Update-DocsMsToc.ps1
  eng/common/scripts/common.ps1
Labels: EngSys, Central-EngSys, auto-merge

#3360 Sync eng/common directory with azure-sdk-tools for PR 2775
  eng/common/pipelines/templates/steps/credscan.yml
Labels: EngSys, Central-EngSys

#3361 Sync eng/common directory with azure-sdk-tools for PR 2768
  eng/common/scripts/Verify-Links.ps1
Labels: EngSys, Central-EngSys

#3354 Sync eng/common directory with azure-sdk-tools for PR 2765
  eng/common/pipelines/templates/steps/install-pipeline-generation.yml
Labels: EngSys, Central-EngSys

#3363 CODEOWNERS: Adding automation section
  .github/CODEOWNERS
Labels: EngSys

#3370 Sync eng/common directory with azure-sdk-tools for PR 2805
  eng/common/scripts/Update-DocsMsToc.ps1
Labels: EngSys, Central-EngSys

#3369 Update CodeOwners
  .github/CODEOWNERS
Labels: auto-merge

#3372 Sync eng/common directory with azure-sdk-tools for PR 2808
  eng/common/scripts/Detect-Api-Changes.ps1
Labels: EngSys, Central-EngSys

#3377 Sync eng/common directory with azure-sdk-tools for PR 2771
  eng/common/scripts/copy-from-blobstorage.ps1
Labels: EngSys, Central-EngSys

#3367 Blob STG 75 76 77 features
  sdk/storage/azure-storage-blobs/CHANGELOG.md
  sdk/storage/azure-storage-blobs/inc/azure/storage/blobs/blob_client.hpp
  sdk/storage/azure-storage-blobs/inc/azure/storage/blobs/blob_options.hpp
  sdk/storage/azure-storage-blobs/inc/azure/storage/blobs/blob_sas_builder.hpp
  sdk/storage/azure-storage-blobs/inc/azure/storage/blobs/blob_service_client.hpp
  sdk/storage/azure-storage-blobs/inc/azure/storage/blobs/block_blob_client.hpp
  sdk/storage/azure-storage-blobs/inc/azure/storage/blobs/rest_client.hpp
  sdk/storage/azure-storage-blobs/src/append_blob_client.cpp
  sdk/storage/azure-storage-blobs/src/blob_client.cpp
  sdk/storage/azure-storage-blobs/src/blob_sas_builder.cpp
  sdk/storage/azure-storage-blobs/src/blob_service_client.cpp
  sdk/storage/azure-storage-blobs/src/block_blob_client.cpp
  sdk/storage/azure-storage-blobs/src/page_blob_client.cpp
  sdk/storage/azure-storage-blobs/src/rest_client.cpp
  sdk/storage/azure-storage-blobs/swagger/README.md
  sdk/storage/azure-storage-blobs/test/ut/append_blob_client_test.cpp
  sdk/storage/azure-storage-blobs/test/ut/append_blob_client_test.hpp
  sdk/storage/azure-storage-blobs/test/ut/blob_container_client_test.cpp
  sdk/storage/azure-storage-blobs/test/ut/blob_sas_test.cpp
  sdk/storage/azure-storage-blobs/test/ut/blob_service_client_test.cpp
  sdk/storage/azure-storage-blobs/test/ut/block_blob_client_test.cpp
  sdk/storage/azure-storage-blobs/test/ut/block_blob_client_test.hpp
  sdk/storage/azure-storage-blobs/test/ut/page_blob_client_test.cpp
  sdk/storage/azure-storage-blobs/test/ut/page_blob_client_test.hpp
  sdk/storage/azure-storage-blobs/test/ut/recordings/AppendBlobClientTest.ContentHash.json
  sdk/storage/azure-storage-blobs/test/ut/recordings/BlobContainerClientTest.AccessConditionTags.json
  sdk/storage/azure-storage-blobs/test/ut/recordings/BlobContainerClientTest.SourceBlobAccessConditions.json
  sdk/storage/azure-storage-blobs/test/ut/recordings/BlobContainerClientTest.Tags.json
  sdk/storage/azure-storage-blobs/test/ut/recordings/BlobServiceClientTest.SetProperties.json
  sdk/storage/azure-storage-blobs/test/ut/recordings/BlockBlobClientTest.ContentHash.json
  sdk/storage/azure-storage-blobs/test/ut/recordings/BlockBlobClientTest.CopyWithTagsMetadataTier.json
  sdk/storage/azure-storage-blobs/test/ut/recordings/BlockBlobClientTest.SetGetTagsWithLeaseId.json
  sdk/storage/azure-storage-blobs/test/ut/recordings/BlockBlobClientTest.SyncCopyFromUri.json
  sdk/storage/azure-storage-blobs/test/ut/recordings/BlockBlobClientTest.UploadFromUri.json
  sdk/storage/azure-storage-blobs/test/ut/recordings/PageBlobClientTest.ContentHash.json
  sdk/storage/azure-storage-common/CHANGELOG.md
  sdk/storage/azure-storage-common/inc/azure/storage/common/account_sas_builder.hpp
  sdk/storage/azure-storage-common/inc/azure/storage/common/internal/constants.hpp
  sdk/storage/azure-storage-common/inc/azure/storage/common/internal/storage_service_version_policy.hpp
  sdk/storage/azure-storage-common/src/account_sas_builder.cpp
  sdk/storage/azure-storage-files-datalake/inc/azure/storage/files/datalake.hpp
  sdk/storage/azure-storage-files-datalake/inc/azure/storage/files/datalake/datalake_options.hpp
  sdk/storage/azure-storage-files-datalake/src/rest_client.cpp
  sdk/storage/azure-storage-files-datalake/swagger/README.md
  sdk/storage/azure-storage-files-shares/inc/azure/storage/files/shares/share_options.hpp
Labels: Client, Storage

#3371 New protocol layer for File Share service
  sdk/storage/azure-storage-files-shares/CHANGELOG.md
  sdk/storage/azure-storage-files-shares/CMakeLists.txt
  sdk/storage/azure-storage-files-shares/inc/azure/storage/files/shares.hpp
  sdk/storage/azure-storage-files-shares/inc/azure/storage/files/shares/protocol/share_rest_client.hpp
  sdk/storage/azure-storage-files-shares/inc/azure/storage/files/shares/rest_client.hpp
  sdk/storage/azure-storage-files-shares/inc/azure/storage/files/shares/share_client.hpp
  sdk/storage/azure-storage-files-shares/inc/azure/storage/files/shares/share_directory_client.hpp
  sdk/storage/azure-storage-files-shares/inc/azure/storage/files/shares/share_file_attributes.hpp
  sdk/storage/azure-storage-files-shares/inc/azure/storage/files/shares/share_file_client.hpp
  sdk/storage/azure-storage-files-shares/inc/azure/storage/files/shares/share_options.hpp
  sdk/storage/azure-storage-files-shares/inc/azure/storage/files/shares/share_responses.hpp
  sdk/storage/azure-storage-files-shares/inc/azure/storage/files/shares/share_service_client.hpp
  sdk/storage/azure-storage-files-shares/src/rest_client.cpp
  sdk/storage/azure-storage-files-shares/src/share_client.cpp
  sdk/storage/azure-storage-files-shares/src/share_directory_client.cpp
  sdk/storage/azure-storage-files-shares/src/share_file_attributes.cpp
  sdk/storage/azure-storage-files-shares/src/share_file_client.cpp
  sdk/storage/azure-storage-files-shares/src/share_lease_client.cpp
  sdk/storage/azure-storage-files-shares/src/share_rest_client.cpp
  sdk/storage/azure-storage-files-shares/src/share_service_client.cpp
  sdk/storage/azure-storage-files-shares/swagger/README.md
  sdk/storage/azure-storage-files-shares/test/ut/recordings/FileShareClientTest.PremiumShare.json
  sdk/storage/azure-storage-files-shares/test/ut/recordings/FileShareClientTest.ShareMetadata.json
  sdk/storage/azure-storage-files-shares/test/ut/recordings/FileShareClientTest.ShareProperties.json
  sdk/storage/azure-storage-files-shares/test/ut/share_client_test.cpp
  sdk/storage/azure-storage-files-shares/test/ut/share_file_attributes_test.cpp
Labels: Client, Storage

#3380 Different storage service has its own sas version(sv)
  sdk/storage/azure-storage-blobs/CHANGELOG.md
  sdk/storage/azure-storage-blobs/src/blob_sas_builder.cpp
  sdk/storage/azure-storage-common/inc/azure/storage/common/internal/constants.hpp
  sdk/storage/azure-storage-common/src/account_sas_builder.cpp
  sdk/storage/azure-storage-files-datalake/src/datalake_sas_builder.cpp
  sdk/storage/azure-storage-files-shares/src/share_sas_builder.cpp
  sdk/storage/azure-storage-queues/src/queue_sas_builder.cpp
Labels: Client, Storage
