Repository Azure/azure-sdk-for-cpp, pull requests merged in 2022-01, with the labels that each got.

#3206 Sync eng/common directory with azure-sdk-tools for PR 2464
  eng/common/TestResources/New-TestResources.ps1
Labels: EngSys, Central-EngSys

#3213 Sync eng/common directory with azure-sdk-tools for PR 2484
  eng/common/pipelines/templates/steps/prepare-pipelines.yml
Labels: EngSys, Central-EngSys

#3186 Macro rename compatibility layer
  sdk/core/azure-core/inc/azure/core/azure_assert.hpp
Labels: Azure.Core

#3227 Sync eng/common directory with azure-sdk-tools for PR 2500
  eng/common/pipelines/templates/steps/install-pipeline-generation.yml
Labels: EngSys, Central-EngSys

#3229 Upload map files to specific artifact locations
  eng/pipelines/templates/jobs/ci.tests.yml
Labels: EngSys

#3226 Sync eng/common directory with azure-sdk-tools for PR 2513
  eng/common/TestResources/New-TestResources.ps1
Labels: EngSys, Central-EngSys

#3220 Updates to readme files
  README.md
  sdk/core/azure-core/README.md
  sdk/identity/azure-identity/README.md
  sdk/keyvault/azure-security-keyvault-certificates/README.md
  sdk/keyvault/azure-security-keyvault-certificates/samples/certificate_basic_operations.md
  sdk/keyvault/azure-security-keyvault-certificates/samples/certificate_get_certificates.md
  sdk/keyvault/azure-security-keyvault-certificates/samples/certificate_import_certificate.md
  sdk/keyvault/azure-security-keyvault-keys/README.md
  sdk/keyvault/azure-security-keyvault-secrets/README.md
  sdk/keyvault/azure-security-keyvault-secrets/samples/sample1_basic_operations.md
  sdk/keyvault/azure-security-keyvault-secrets/samples/sample2_backup_restore.md
  sdk/keyvault/azure-security-keyvault-secrets/samples/sample3_delete_recover.md
  sdk/keyvault/azure-security-keyvault-secrets/samples/sample4_get_secrets_deleted.md
Labels: Docs, KeyVault

#3216 Bump dependency on azure core for all upstream SDKs and client libraries to the latest shipped version
  sdk/identity/azure-identity/vcpkg/Config.cmake.in
  sdk/identity/azure-identity/vcpkg/vcpkg.json
  sdk/storage/azure-storage-common/vcpkg/Config.cmake.in
  sdk/storage/azure-storage-common/vcpkg/vcpkg.json
  sdk/template/azure-template/vcpkg/Config.cmake.in
  sdk/template/azure-template/vcpkg/vcpkg.json
Labels: Client

#3221 Identity 1.1.1 change log
  sdk/identity/azure-identity/CHANGELOG.md
  sdk/identity/azure-identity/src/private/package_version.hpp
Labels: Client, Azure.Identity

#3219 Remove Logging from the LibcurlConnectionPool - cleaning routine
  eng/pipelines/templates/jobs/archetype-sdk-tests.yml
  eng/pipelines/templates/jobs/ci.tests.yml
  sdk/core/azure-core/CHANGELOG.md
  sdk/core/azure-core/src/http/curl/curl.cpp
Labels: bug, Client

#3243 Sync eng/common directory with azure-sdk-tools for PR 2554
  eng/common/testproxy/docker-start-proxy.ps1
  eng/common/testproxy/test-proxy-tool.yml
Labels: EngSys, Central-EngSys

#3249 Sync eng/common directory with azure-sdk-tools for PR 2545
  eng/common/scripts/artifact-metadata-parsing.ps1
Labels: EngSys, Central-EngSys

#3256 Fix BOM artifact upload failure on failed cmake
  eng/pipelines/templates/jobs/archetype-sdk-client.yml
  eng/pipelines/templates/jobs/ci.tests.yml
Labels: Central-EngSys

#3255 Fix up the Azure Core changelog for breaking change and new line
  sdk/core/azure-core/CHANGELOG.md
Labels: Docs, Azure.Core

#3262 fixed typo in MigrationGuide.md
  sdk/storage/MigrationGuide.md
Labels: customer-reported, Storage

#3259 Remove old copy of storage TestEnv Value with fake end point in core ci.yml
  sdk/core/ci.yml
Labels: Azure.Core, EngSys

#3266 Sync eng/common directory with azure-sdk-tools for PR 2592
  eng/common/TestResources/New-TestResources.ps1
Labels: EngSys, Central-EngSys

#3265 Sync eng/common directory with azure-sdk-tools for PR 2585
  eng/common/testproxy/docker-start-proxy.ps1
  eng/common/testproxy/test-proxy-tool.yml
Labels: EngSys, Central-EngSys

#3267 Sync eng/common directory with azure-sdk-tools for PR 2596
  eng/common/pipelines/templates/steps/retain-run.yml
  eng/common/scripts/Add-RetentionLease.ps1
  eng/common/scripts/Invoke-DevOpsAPI.ps1
Labels: EngSys, Central-EngSys

#3268 Sync eng/common directory with azure-sdk-tools for PR 2578
  eng/common/scripts/stress-testing/stress-test-deployment-lib.ps1
Labels: EngSys, Central-EngSys

#3272 Sync eng/common directory with azure-sdk-tools for PR 2581
  eng/common/scripts/Get-AADIdentityFromGithubUser.ps1
Labels: EngSys, Central-EngSys

#3271 Sync eng/common directory with azure-sdk-tools for PR 2599
  eng/common/scripts/stress-testing/find-all-stress-packages.ps1
  eng/common/scripts/stress-testing/stress-test-deployment-lib.ps1
Labels: EngSys, Central-EngSys

#3250 secrets build from source
  cmake-modules/FolderList.cmake
  sdk/keyvault/azure-security-keyvault-secrets/CMakeLists.txt
  sdk/keyvault/ci.yml
Labels: EngSys

#3251 keys source build
  cmake-modules/FolderList.cmake
  sdk/keyvault/azure-security-keyvault-certificates/CMakeLists.txt
  sdk/keyvault/azure-security-keyvault-keys/CMakeLists.txt
  sdk/keyvault/ci.yml
Labels: EngSys

#3274 Sync eng/common directory with azure-sdk-tools for PR 2604
  eng/common/docgeneration/Generate-DocIndex.ps1
Labels: EngSys, Central-EngSys

#3276 Sync eng/common directory with azure-sdk-tools for PR 2617
  eng/common/pipelines/templates/steps/verify-links.yml
Labels: EngSys, Central-EngSys

#3292 Sync eng/common directory with azure-sdk-tools for PR 2641
  eng/common/scripts/job-matrix/README.md
Labels: EngSys, Central-EngSys
