Repository Azure/azure-sdk-for-cpp, pull requests merged in 2022-11, with the labels that each got.

#4076 fix typo in PerformanceTesting.md
  doc/PerformanceTesting.md
Labels: Docs

#4080 Sync eng/common directory with azure-sdk-tools for PR 4544
  eng/common/scripts/job-matrix/Create-JobMatrix.ps1
  eng/common/scripts/stress-testing/find-all-stress-packages.ps1
  eng/common/scripts/stress-testing/generate-scenario-matrix.ps1
  eng/common/scripts/stress-testing/stress-test-deployment-lib.ps1
Labels: EngSys, Central-EngSys

#4079 Sync eng/common directory with azure-sdk-tools for PR 4574
  eng/common/testproxy/target_version.txt
Labels: EngSys, Central-EngSys

#4085 Sync eng/common directory with azure-sdk-tools for PR 4591
  eng/common/scripts/stress-testing/find-all-stress-packages.ps1
Labels: EngSys, Central-EngSys

#4081 Sync eng/common directory with azure-sdk-tools for PR 4586
  eng/common/scripts/Update-DocsMsToc.ps1
Labels: EngSys, Central-EngSys

#4086 Sync eng/common directory with azure-sdk-tools for PR 4603
  eng/common/pipelines/templates/steps/check-spelling.yml
  eng/common/spelling/Invoke-Cspell.ps1
Labels: EngSys, Central-EngSys

#4067 DMLib page blob download support
  sdk/storage/azure-storage-datamovement/CMakeLists.txt
  sdk/storage/azure-storage-datamovement/inc/azure/storage/datamovement/job_engine.hpp
  sdk/storage/azure-storage-datamovement/inc/azure/storage/datamovement/tasks/download_page_blob_to_file_task.hpp
  sdk/storage/azure-storage-datamovement/src/job_engine_serialization.cpp
  sdk/storage/azure-storage-datamovement/src/job_engine_task_generation.cpp
  sdk/storage/azure-storage-datamovement/src/tasks/download_page_blob_to_file_task.cpp
  sdk/storage/azure-storage-datamovement/test/ut/blob_transfer_manager_download_test.cpp
Labels: Client, Storage

#4089 Sync eng/common directory with azure-sdk-tools for PR 4606
  eng/common/testproxy/target_version.txt
Labels: EngSys, Central-EngSys

#4082 Core November release
  sdk/core/azure-core/CHANGELOG.md
Labels: Azure.Core

#4091 Sync eng/common directory with azure-sdk-tools for PR 4622
  eng/common/TestResources/clouds/AzureCloud.json
Labels: EngSys, Central-EngSys

#4092 Sync eng/common directory with azure-sdk-tools for PR 4629
  eng/common/scripts/stress-testing/stress-test-deployment-lib.ps1
Labels: EngSys, Central-EngSys

#4083 Identity November release
  sdk/identity/azure-identity/CHANGELOG.md
Labels: Azure.Identity

#4103 Updating check enforcer permissions to enable writing comments
  .github/workflows/event.yml
Labels: Central-EngSys

#4105 Sync eng/common directory with azure-sdk-tools for PR 4623
  eng/common/TestResources/New-TestResources.ps1
Labels: EngSys, Central-EngSys

#4106 Sync eng/common directory with azure-sdk-tools for PR 4666
  eng/common/scripts/stress-testing/stress-test-deployment-lib.ps1
Labels: EngSys, Central-EngSys

#4107 Sync eng/common directory with azure-sdk-tools for PR 4631
  eng/common/scripts/stress-testing/stress-test-deployment-lib.ps1
Labels: EngSys, Central-EngSys

#4108 Fix typo for llong -> long in doc comment for Key Vault Certificates
  sdk/keyvault/azure-security-keyvault-certificates/inc/azure/keyvault/certificates/certificate_client_operations.hpp
Labels: KeyVault

#4112 Sync eng/common directory with azure-sdk-tools for PR 4687
  eng/common/testproxy/target_version.txt
Labels: EngSys, Central-EngSys

#4117 Sync eng/common directory with azure-sdk-tools for PR 4632
  eng/common/scripts/Helpers/Metadata-Helpers.ps1
  eng/common/scripts/Helpers/Service-Level-Readme-Automation-Helpers.ps1
  eng/common/scripts/Service-Level-Readme-Automation.ps1
Labels: EngSys, Central-EngSys

#4119 Sync eng/common directory with azure-sdk-tools for PR 4701
  eng/common/scripts/Queue-Pipeline.ps1
Labels: EngSys, Central-EngSys

#4122 Sync eng/common directory with azure-sdk-tools for PR 4726
  eng/common/scripts/stress-testing/stress-test-deployment-lib.ps1
Labels: EngSys, Central-EngSys

#4111 Sync eng/common directory with azure-sdk-tools for PR 4628
  eng/common/scripts/Create-APIReview.ps1
  eng/common/scripts/Helpers/ApiView-Helpers.ps1
  eng/common/scripts/Prepare-Release.ps1
Labels: EngSys, Central-EngSys

#4124 Sync eng/common directory with azure-sdk-tools for PR 4728
  eng/common/scripts/Helpers/Metadata-Helpers.ps1
Labels: EngSys, Central-EngSys

#4125 Sync eng/common directory with azure-sdk-tools for PR 4746
  eng/common/scripts/git-branch-push.ps1
Labels: EngSys, Central-EngSys

#4100 Update vcpkg baseline to latest released tags/2022.10.19
  cmake-modules/AzureVcpkg.cmake
  vcpkg.json
Labels: Azure.Core, EngSys

#4132 Disable warning C6387 coming from wil in win_http_transport due to SAL annotation
  sdk/core/azure-core/src/http/winhttp/win_http_request.hpp
  sdk/core/azure-core/src/http/winhttp/win_http_transport.cpp
Labels: Azure.Core

#4130 Correct invalid UTF-8 in comment in share_options.hpp
  sdk/storage/azure-storage-files-shares/inc/azure/storage/files/shares/share_options.hpp
Labels: customer-reported

#4135 Sync eng/common directory with azure-sdk-tools for PR 4713
  eng/common/scripts/stress-testing/stress-test-deployment-lib.ps1
Labels: EngSys, Central-EngSys
