Repository Azure/azure-sdk-for-cpp, pull requests merged in 2022-04, with the labels that each got.

#3498 Removed one more Azure Core 1.2.0 dependency
  sdk/attestation/azure-security-attestation/vcpkg/Config.cmake.in
Labels: Attestation

#3499 Sync eng/common directory with azure-sdk-tools for PR 2967
  eng/common/scripts/job-matrix/Create-JobMatrix.ps1
  eng/common/scripts/job-matrix/job-matrix-functions.ps1
  eng/common/scripts/job-matrix/tests/job-matrix-functions.tests.ps1
Labels: EngSys, Central-EngSys

#3500 Sync eng/common directory with azure-sdk-tools for PR 2966
  eng/common/TestResources/New-TestResources.ps1
Labels: EngSys, Central-EngSys

#3482 Vcpkg Binary Cache Cleanup
  eng/pipelines/templates/steps/vcpkg.yml
  eng/scripts/Set-VcpkgWriteModeCache.ps1
Labels: Central-EngSys

#3502 fix a bug where the xml body cannot be too big
  sdk/storage/azure-storage-blobs/test/ut/block_blob_client_test.cpp
  sdk/storage/azure-storage-blobs/test/ut/recordings/BlockBlobClientTest.MaximumBlocks.json
  sdk/storage/azure-storage-common/CHANGELOG.md
  sdk/storage/azure-storage-common/src/xml_wrapper.cpp
Labels: Client, Storage

#3483 Identity 1.3.0-beta.1 (April) Release
  sdk/identity/azure-identity/CHANGELOG.md
Labels: Azure.Identity

#3478 Storage April Release
  cmake-modules/FolderList.cmake
  sdk/storage/azure-storage-blobs/CHANGELOG.md
  sdk/storage/azure-storage-blobs/CMakeLists.txt
  sdk/storage/azure-storage-blobs/src/private/package_version.hpp
  sdk/storage/azure-storage-blobs/vcpkg.json
  sdk/storage/azure-storage-blobs/vcpkg/Config.cmake.in
  sdk/storage/azure-storage-blobs/vcpkg/vcpkg.json
  sdk/storage/azure-storage-common/CHANGELOG.md
  sdk/storage/azure-storage-common/CMakeLists.txt
  sdk/storage/azure-storage-common/src/private/package_version.hpp
  sdk/storage/azure-storage-common/vcpkg.json
  sdk/storage/azure-storage-common/vcpkg/Config.cmake.in
  sdk/storage/azure-storage-common/vcpkg/vcpkg.json
  sdk/storage/azure-storage-queues/CHANGELOG.md
  sdk/storage/azure-storage-queues/CMakeLists.txt
  sdk/storage/azure-storage-queues/src/private/package_version.hpp
  sdk/storage/azure-storage-queues/vcpkg.json
  sdk/storage/azure-storage-queues/vcpkg/Config.cmake.in
  sdk/storage/azure-storage-queues/vcpkg/vcpkg.json
Labels: Client, Storage

#3532 Sync eng/common directory with azure-sdk-tools for PR 3092
  eng/common/testproxy/test-proxy-tool.yml
Labels: EngSys, Central-EngSys

#3529 Sync eng/common directory with azure-sdk-tools for PR 3067
  eng/common/TestResources/New-TestResources.ps1
  eng/common/TestResources/Remove-TestResources.ps1
  eng/common/TestResources/Remove-TestResources.ps1.md
  eng/common/TestResources/SubConfig-Helpers.ps1
  eng/common/TestResources/Update-TestResources.ps1
  eng/common/TestResources/remove-test-resources.yml
Labels: EngSys, Central-EngSys

#3534 Remove `DefaultSasVersion`
  sdk/storage/azure-storage-common/inc/azure/storage/common/internal/constants.hpp
Labels: Client, Storage

#3536 Update outdated doc for customizing transport
  doc/HttpTransportAdapter.md
Labels: Docs, Azure.Core, Client

#3542 Sync eng/common directory with azure-sdk-tools for PR 2963
  eng/common/scripts/ChangeLog-Operations.ps1
Labels: EngSys, Central-EngSys

#3535 Fix a typo extendable enumeration
  sdk/core/azure-core/inc/azure/core/internal/extendable_enumeration.hpp
Labels: Docs, Azure.Core, Client

#3545 Sync eng/common directory with azure-sdk-tools for PR 2942
  eng/common/pipelines/templates/steps/install-pipeline-generation.yml
  eng/common/pipelines/templates/steps/prepare-pipelines.yml
Labels: EngSys, Central-EngSys

#3547 Sync eng/common directory with azure-sdk-tools for PR 3123
  eng/common/pipelines/templates/steps/credscan.yml
Labels: EngSys, Central-EngSys

#3546 Sync eng/common directory with azure-sdk-tools for PR 3124
  eng/common/TestResources/Remove-TestResources.ps1
  eng/common/TestResources/SubConfig-Helpers.ps1
Labels: EngSys, Central-EngSys

#3485 Sync eng/common directory with azure-sdk-tools for PR 3000
  eng/common/docgeneration/Generate-DocIndex.ps1
Labels: EngSys, Central-EngSys

#3559 Sync eng/common directory with azure-sdk-tools for PR 3145
  eng/common/TestResources/New-TestResources.ps1
Labels: EngSys, Central-EngSys

#3562 Sync eng/common directory with azure-sdk-tools for PR 3153
  eng/common/TestResources/New-TestResources.ps1
  eng/common/TestResources/New-TestResources.ps1.md
  eng/common/TestResources/deploy-test-resources.yml
Labels: EngSys, Central-EngSys

#3570 Sync eng/common directory with azure-sdk-tools for PR 3160
  eng/common/docgeneration/Generate-DocIndex.ps1
Labels: EngSys, Central-EngSys

#3572 Sync eng/common directory with azure-sdk-tools for PR 3169
  eng/common/scripts/Update-DocsMsMetadata.ps1
Labels: EngSys, Central-EngSys

#3484 [Tech Docs] Libcurl transport adapter
  doc/LibcurlTransportAdapter.md
Labels: Azure.Core

#3560 Key vault work - RNG and rotation policy
  sdk/keyvault/azure-security-keyvault-keys/CMakeLists.txt
  sdk/keyvault/azure-security-keyvault-keys/inc/azure/keyvault/keys/key_client.hpp
  sdk/keyvault/azure-security-keyvault-keys/inc/azure/keyvault/keys/key_client_models.hpp
  sdk/keyvault/azure-security-keyvault-keys/inc/azure/keyvault/keys/key_client_options.hpp
  sdk/keyvault/azure-security-keyvault-keys/src/key_client.cpp
  sdk/keyvault/azure-security-keyvault-keys/src/key_get_random_bytes.cpp
  sdk/keyvault/azure-security-keyvault-keys/src/key_rotation_policy.cpp
  sdk/keyvault/azure-security-keyvault-keys/src/private/key_constants.hpp
  sdk/keyvault/azure-security-keyvault-keys/src/private/key_serializers.hpp
  sdk/keyvault/azure-security-keyvault-keys/test/ut/CMakeLists.txt
  sdk/keyvault/azure-security-keyvault-keys/test/ut/key_client_base_test.hpp
  sdk/keyvault/azure-security-keyvault-keys/test/ut/key_rotation_policy_test_live.cpp
  sdk/keyvault/azure-security-keyvault-keys/test/ut/recordings/KeyVaultKeyClient.GetKeyRotationPolicy.json
  sdk/keyvault/azure-security-keyvault-keys/test/ut/recordings/KeyVaultKeyClient.GetRandomBytes.json
Labels: feature-request, Client, KeyVault

#3576 Sync eng/common directory with azure-sdk-tools for PR 3188
  eng/common/pipelines/templates/steps/publish-blobs.yml
Labels: EngSys, Central-EngSys

#3583 Fix typo in win http source: tcp_false_start -> tls_false_start
  sdk/core/azure-core/src/http/winhttp/win_http_transport.cpp
Labels: Azure.Core

#3564 update curl transport options to support ignore proxy from system
  sdk/core/azure-core/CHANGELOG.md
  sdk/core/azure-core/inc/azure/core/http/curl_transport.hpp
  sdk/core/azure-core/src/http/curl/curl.cpp
Labels: Azure.Core, Client

#3586 update log level from Retry policy
  sdk/core/azure-core/CHANGELOG.md
  sdk/core/azure-core/src/http/retry_policy.cpp
  sdk/core/azure-core/test/ut/retry_policy_test.cpp
Labels: Azure.Core, Client

#3580 Add batch protocol layer
  sdk/core/azure-core/CHANGELOG.md
  sdk/core/azure-core/inc/azure/core/http/http.hpp
  sdk/storage/azure-storage-blobs/inc/azure/storage/blobs/rest_client.hpp
  sdk/storage/azure-storage-blobs/src/rest_client.cpp
  sdk/storage/azure-storage-blobs/swagger/README.md
Labels: Client, Storage

#3588 some small fixes on Storage cmakefiles
  cmake-modules/FolderList.cmake
  sdk/storage/azure-storage-blobs/CMakeLists.txt
  sdk/storage/azure-storage-common/CMakeLists.txt
  sdk/storage/azure-storage-files-datalake/CMakeLists.txt
  sdk/storage/azure-storage-files-shares/CMakeLists.txt
  sdk/storage/azure-storage-queues/CMakeLists.txt
Labels: Client, Storage

#3587 Sync eng/common directory with azure-sdk-tools for PR 3212
  eng/common/testproxy/docker-start-proxy.ps1
  eng/common/testproxy/target_version.txt
Labels: EngSys, Central-EngSys

#3591 Sync eng/common directory with azure-sdk-tools for PR 3221
  eng/common/scripts/Update-DocsMsMetadata.ps1
Labels: EngSys, Central-EngSys

#3593 Sync eng/common directory with azure-sdk-tools for PR 3061
  eng/common/scripts/Delete-RemoteBranches.ps1
  eng/common/scripts/Invoke-GitHubAPI.ps1
Labels: EngSys, Central-EngSys

#3595 Sync eng/common directory with azure-sdk-tools for PR 3250
  eng/common/scripts/Delete-RemoteBranches.ps1
  eng/common/scripts/Invoke-GitHubAPI.ps1
Labels: EngSys, Central-EngSys

#3585 Create a session handle once in the transport ctor and reuse it for all requests rather than creating a new one each time.
  sdk/core/azure-core/CHANGELOG.md
  sdk/core/azure-core/inc/azure/core/http/win_http_transport.hpp
  sdk/core/azure-core/src/http/winhttp/win_http_transport.cpp
Labels: Azure.Core

#3598 Fix-up the changelog entry link for the curtransportoption bug fix
  sdk/core/azure-core/CHANGELOG.md
Labels: Docs, Azure.Core

#3601 Remove extra period at ends of exception messages in winhttp transport
  sdk/core/azure-core/src/http/winhttp/win_http_transport.cpp
Labels: Azure.Core

#3604 fix cmake in storage
  sdk/storage/azure-storage-blobs/CMakeLists.txt
  sdk/storage/azure-storage-common/CMakeLists.txt
  sdk/storage/azure-storage-files-datalake/CMakeLists.txt
  sdk/storage/azure-storage-files-shares/CMakeLists.txt
  sdk/storage/azure-storage-queues/CMakeLists.txt
Labels: Client, Storage
