Repository Azure/azure-sdk-for-cpp, pull requests merged in 2023-03, with the labels that each got.

#4391 Sync eng/common directory with azure-sdk-tools for PR 5581
  eng/common/testproxy/target_version.txt
Labels: EngSys, Central-EngSys

#4396 Sync eng/common directory with azure-sdk-tools for PR 5540
  eng/common/scripts/Cadl-Project-Generate.ps1
Labels: EngSys, Central-EngSys

#4400 Sync eng/common directory with azure-sdk-tools for PR 5595
  eng/common/spelling/Invoke-Cspell.ps1
Labels: EngSys, Central-EngSys

#4410 Storage March Release
  cmake-modules/FolderList.cmake
  sdk/storage/assets.json
  sdk/storage/azure-storage-blobs/CHANGELOG.md
  sdk/storage/azure-storage-blobs/CMakeLists.txt
  sdk/storage/azure-storage-blobs/src/private/package_version.hpp
  sdk/storage/azure-storage-blobs/vcpkg.json
  sdk/storage/azure-storage-blobs/vcpkg/Config.cmake.in
  sdk/storage/azure-storage-blobs/vcpkg/vcpkg.json
  sdk/storage/azure-storage-common/CHANGELOG.md
  sdk/storage/azure-storage-common/CMakeLists.txt
  sdk/storage/azure-storage-common/src/account_sas_builder.cpp
  sdk/storage/azure-storage-common/src/private/package_version.hpp
  sdk/storage/azure-storage-common/vcpkg.json
  sdk/storage/azure-storage-common/vcpkg/Config.cmake.in
  sdk/storage/azure-storage-common/vcpkg/vcpkg.json
  sdk/storage/azure-storage-files-shares/CHANGELOG.md
  sdk/storage/azure-storage-files-shares/CMakeLists.txt
  sdk/storage/azure-storage-files-shares/src/private/package_version.hpp
  sdk/storage/azure-storage-files-shares/src/share_sas_builder.cpp
  sdk/storage/azure-storage-files-shares/vcpkg.json
  sdk/storage/azure-storage-files-shares/vcpkg/Config.cmake.in
  sdk/storage/azure-storage-files-shares/vcpkg/vcpkg.json
Labels: Storage

#4415 Sync eng/common directory with azure-sdk-tools for PR 5627
  eng/common/scripts/Test-SampleMetadata.ps1
Labels: EngSys, Central-EngSys

#4414 Update CHANGELOG.md
  sdk/storage/azure-storage-files-shares/CHANGELOG.md
Labels: Client, Storage

#4409 Add DefaultAzureCredential
  sdk/identity/azure-identity/CHANGELOG.md
  sdk/identity/azure-identity/CMakeLists.txt
  sdk/identity/azure-identity/README.md
  sdk/identity/azure-identity/inc/azure/identity.hpp
  sdk/identity/azure-identity/inc/azure/identity/chained_token_credential.hpp
  sdk/identity/azure-identity/inc/azure/identity/default_azure_credential.hpp
  sdk/identity/azure-identity/samples/CMakeLists.txt
  sdk/identity/azure-identity/samples/default_azure_credential.cpp
  sdk/identity/azure-identity/src/azure_cli_credential.cpp
  sdk/identity/azure-identity/src/chained_token_credential.cpp
  sdk/identity/azure-identity/src/default_azure_credential.cpp
  sdk/identity/azure-identity/src/environment_credential.cpp
  sdk/identity/azure-identity/src/managed_identity_source.cpp
  sdk/identity/azure-identity/src/private/managed_identity_source.hpp
  sdk/identity/azure-identity/test/ut/CMakeLists.txt
  sdk/identity/azure-identity/test/ut/azure_cli_credential_test.cpp
  sdk/identity/azure-identity/test/ut/chained_token_credential_test.cpp
  sdk/identity/azure-identity/test/ut/default_azure_credential_test.cpp
  sdk/identity/azure-identity/test/ut/environment_credential_test.cpp
  sdk/identity/azure-identity/test/ut/managed_identity_credential_test.cpp
  sdk/identity/azure-identity/test/ut/simplified_header_test.cpp
  sdk/identity/ci.yml
Labels: Azure.Identity

#4425 Update vcpkg release manifest templates per vcpkg team recommendation
  sdk/attestation/azure-security-attestation/vcpkg/portfile.cmake
  sdk/core/azure-core-tracing-opentelemetry/vcpkg/portfile.cmake
  sdk/core/azure-core/vcpkg/portfile.cmake
  sdk/identity/azure-identity/vcpkg/portfile.cmake
  sdk/keyvault/azure-security-keyvault-administration/vcpkg/portfile.cmake
  sdk/keyvault/azure-security-keyvault-certificates/vcpkg/portfile.cmake
  sdk/keyvault/azure-security-keyvault-keys/vcpkg/portfile.cmake
  sdk/keyvault/azure-security-keyvault-secrets/vcpkg/portfile.cmake
  sdk/storage/azure-storage-blobs/vcpkg/portfile.cmake
  sdk/storage/azure-storage-common/vcpkg/portfile.cmake
  sdk/storage/azure-storage-files-datalake/vcpkg/portfile.cmake
  sdk/storage/azure-storage-files-shares/vcpkg/portfile.cmake
  sdk/storage/azure-storage-queues/vcpkg/portfile.cmake
  sdk/template/azure-template/vcpkg/portfile.cmake
Labels: EngSys

#4440 Sync eng/common directory with azure-sdk-tools for PR 5613
  eng/common/testproxy/override-proxy-version.ps1
  eng/common/testproxy/test-proxy-docker.yml
  eng/common/testproxy/test-proxy-tool.yml
Labels: EngSys, Central-EngSys

#4428 Add GetCredentialName()
  sdk/core/azure-core-test/inc/azure/core/test/test_proxy_manager.hpp
  sdk/core/azure-core/CHANGELOG.md
  sdk/core/azure-core/inc/azure/core/credentials/credentials.hpp
  sdk/core/azure-core/test/ut/bearer_token_authentication_policy_test.cpp
  sdk/identity/azure-identity/CHANGELOG.md
  sdk/identity/azure-identity/inc/azure/identity/azure_cli_credential.hpp
  sdk/identity/azure-identity/inc/azure/identity/chained_token_credential.hpp
  sdk/identity/azure-identity/src/azure_cli_credential.cpp
  sdk/identity/azure-identity/src/chained_token_credential.cpp
  sdk/identity/azure-identity/src/client_certificate_credential.cpp
  sdk/identity/azure-identity/src/client_secret_credential.cpp
  sdk/identity/azure-identity/src/default_azure_credential.cpp
  sdk/identity/azure-identity/src/environment_credential.cpp
  sdk/identity/azure-identity/src/managed_identity_credential.cpp
  sdk/identity/azure-identity/src/managed_identity_source.cpp
  sdk/identity/azure-identity/src/private/managed_identity_source.hpp
  sdk/identity/azure-identity/test/ut/azure_cli_credential_test.cpp
  sdk/identity/azure-identity/test/ut/chained_token_credential_test.cpp
  sdk/identity/azure-identity/test/ut/client_certificate_credential_test.cpp
  sdk/identity/azure-identity/test/ut/client_secret_credential_test.cpp
  sdk/identity/azure-identity/test/ut/default_azure_credential_test.cpp
  sdk/identity/azure-identity/test/ut/environment_credential_test.cpp
  sdk/identity/azure-identity/test/ut/managed_identity_credential_test.cpp
  sdk/identity/azure-identity/test/ut/token_credential_impl_test.cpp
Labels: Azure.Core, Azure.Identity

#4453 Sync eng/common directory with azure-sdk-tools for PR 5702
  eng/common/scripts/Test-SampleMetadata.ps1
Labels: EngSys, Central-EngSys

#4449 Use aka.ms link to Identity troubleshooting
  sdk/identity/azure-identity/samples/default_azure_credential.cpp
  sdk/identity/azure-identity/src/default_azure_credential.cpp
Labels: Azure.Identity

#4447 Undocument ChainedCred usage by DefaultAzCred & remove friend and private ctor
  sdk/identity/azure-identity/CMakeLists.txt
  sdk/identity/azure-identity/README.md
  sdk/identity/azure-identity/inc/azure/identity/chained_token_credential.hpp
  sdk/identity/azure-identity/inc/azure/identity/default_azure_credential.hpp
  sdk/identity/azure-identity/src/chained_token_credential.cpp
  sdk/identity/azure-identity/src/default_azure_credential.cpp
  sdk/identity/azure-identity/src/private/chained_token_credential_impl.hpp
  sdk/identity/azure-identity/test/ut/default_azure_credential_test.cpp
Labels: Azure.Identity

#4450 Sync eng/common directory with azure-sdk-tools for PR 5691
  eng/common/scripts/TypeSpec-Project-Generate.ps1
  eng/common/scripts/TypeSpec-Project-Sync.ps1
Labels: EngSys, Central-EngSys

#4455 Simpler identity logging
  sdk/identity/azure-identity/src/azure_cli_credential.cpp
  sdk/identity/azure-identity/src/chained_token_credential.cpp
  sdk/identity/azure-identity/src/default_azure_credential.cpp
  sdk/identity/azure-identity/src/environment_credential.cpp
  sdk/identity/azure-identity/src/managed_identity_source.cpp
  sdk/identity/azure-identity/test/ut/default_azure_credential_test.cpp
  sdk/identity/azure-identity/test/ut/environment_credential_test.cpp
Labels: Azure.Identity

#4458 Update changelog with issue link
  sdk/core/azure-core/CHANGELOG.md
Labels: Docs, Azure.Core

#4457 Tests: replace most `EXPECT_TRUE(a OP b)` with `EXPECT_OP(a, b)`
  sdk/attestation/azure-security-attestation/test/ut/token_test.cpp
  sdk/core/azure-core-tracing-opentelemetry/test/ut/service_support_test.cpp
  sdk/core/azure-core/test/ut/context_test.cpp
  sdk/core/azure-core/test/ut/nullable_test.cpp
  sdk/core/azure-core/test/ut/operation_test.cpp
  sdk/core/azure-core/test/ut/string_test.cpp
  sdk/core/azure-core/test/ut/transport_adapter_base_test.cpp
  sdk/core/azure-core/test/ut/uuid_test.cpp
  sdk/keyvault/azure-security-keyvault-keys/test/ut/key_cryptographic_client_test_live.cpp
  sdk/storage/azure-storage-files-shares/test/ut/share_client_test.cpp
  sdk/storage/azure-storage-files-shares/test/ut/share_file_client_test.cpp
Labels: test-enhancement

#4456 Sync eng/common directory with azure-sdk-tools for PR 5722
  eng/common/pipelines/templates/steps/check-spelling.yml
Labels: EngSys, Central-EngSys

#4465 Sync eng/common directory with azure-sdk-tools for PR 5742
  eng/common/scripts/trust-proxy-certificate.ps1
Labels: EngSys, Central-EngSys

#4459 Organize applying Identity log prefix
  sdk/identity/azure-identity/CMakeLists.txt
  sdk/identity/azure-identity/src/azure_cli_credential.cpp
  sdk/identity/azure-identity/src/chained_token_credential.cpp
  sdk/identity/azure-identity/src/default_azure_credential.cpp
  sdk/identity/azure-identity/src/environment_credential.cpp
  sdk/identity/azure-identity/src/managed_identity_source.cpp
  sdk/identity/azure-identity/src/private/identity_log.hpp
Labels: Azure.Identity

#4481 Sync eng/common directory with azure-sdk-tools for PR 5794
  eng/common/scripts/git-branch-push.ps1
Labels: EngSys, Central-EngSys

#4482 Fix unmatched parenthesis in doc
  sdk/storage/MigrationGuide.md
Labels: Storage

#4484 fix concurrent upload test failures
  sdk/storage/azure-storage-blobs/test/ut/block_blob_client_test.cpp
  sdk/storage/azure-storage-files-datalake/test/ut/datalake_file_client_test.cpp
  sdk/storage/azure-storage-files-shares/test/ut/share_file_client_test.cpp
Labels: Client, Storage, test-enhancement

#4488 Sync eng/common directory with azure-sdk-tools for PR 5726
  eng/common/scripts/stress-testing/deploy-stress-tests.ps1
  eng/common/scripts/stress-testing/stress-test-deployment-lib.ps1
Labels: EngSys, Central-EngSys

#4467 Fixed the user-agent string sent to the service to include the "keys" suffix in the value, when using `CryptographyClient`.
  sdk/keyvault/azure-security-keyvault-keys/CHANGELOG.md
  sdk/keyvault/azure-security-keyvault-keys/src/cryptography/cryptography_client.cpp
  sdk/keyvault/azure-security-keyvault-keys/src/key_client.cpp
  sdk/keyvault/azure-security-keyvault-keys/src/private/key_constants.hpp
Labels: KeyVault

#4493 Temporarily update platform-matrix.json to remove openssl_111n configuration
  eng/pipelines/templates/stages/platform-matrix.json
Labels: EngSys

#4411 Sync eng/common directory with azure-sdk-tools for PR 5608
  eng/common/pipelines/templates/stages/archetype-sdk-tool-pwsh.yml
  eng/common/pipelines/templates/steps/run-pester-tests.yml
  eng/common/scripts/get-codeowners.lib.ps1
  eng/common/scripts/get-codeowners.ps1
  eng/pipelines/templates/stages/archetype-cpp-release.yml
Labels: EngSys, Central-EngSys
