Repository Azure/azure-sdk-for-cpp, pull requests merged in 2023-02, with the labels that each got.

#4303 Policies do not overwrite HTTP headers if they are already set
  sdk/core/azure-core/inc/azure/core/http/policies/policy.hpp
  sdk/core/azure-core/src/http/telemetry_policy.cpp
  sdk/core/azure-core/test/ut/request_id_policy_test.cpp
  sdk/core/azure-core/test/ut/telemetry_policy_test.cpp
Labels: Azure.Core

#4311 Move cspell exceptions in markdown file to metadata that isn't visible using html comment syntax
  sdk/core/azure-core/test/ut/proxy_tests/readme.md
Labels: Docs, auto-merge

#4316 Sync eng/common directory with azure-sdk-tools for PR 4812
  eng/common/pipelines/templates/steps/cosmos-emulator.yml
  eng/common/scripts/Cosmos-Emulator.ps1
Labels: EngSys, Central-EngSys

#4308 Sync eng/common directory with azure-sdk-tools for PR 5291
  eng/common/testproxy/transition-scripts/README.md
  eng/common/testproxy/transition-scripts/generate-assets-json.ps1
  eng/ignore-links.txt
Labels: EngSys, Central-EngSys

#4307 move cleanup tool.
  sdk/keyvault/tools/cleanup/CMakeLists.txt
  sdk/keyvault/tools/cleanup/LICENSE
  sdk/keyvault/tools/cleanup/README.md
  sdk/keyvault/tools/cleanup/src/cleanup.cpp
Labels: KeyVault

#4321 Sync eng/common directory with azure-sdk-tools for PR 5313
  eng/common/TestResources/New-TestResources.ps1
Labels: EngSys, Central-EngSys

#4320 Prepare OpenTelemetry for beta release
  doc/DistributedTracing.md
  sdk/core/azure-core-tracing-opentelemetry/CHANGELOG.md
  sdk/core/azure-core-tracing-opentelemetry/vcpkg/Config.cmake.in
  sdk/core/azure-core-tracing-opentelemetry/vcpkg/vcpkg.json
Labels: Azure.Core, OpenTelemetry

#4325 Sync eng/common directory with azure-sdk-tools for PR 5318
  eng/common/testproxy/target_version.txt
Labels: EngSys, Central-EngSys

#4322 Sync eng/common directory with azure-sdk-tools for PR 5309
  eng/common/scripts/stress-testing/deploy-stress-tests.ps1
  eng/common/scripts/stress-testing/stress-test-deployment-lib.ps1
Labels: EngSys, Central-EngSys

#4323 Make sure PRs modifying markdown files within the repo get CI triggered
  sdk/core/ci.yml
Labels: EngSys, MQ

#4329 Sync eng/common directory with azure-sdk-tools for PR 5316
  eng/common/scripts/Helpers/Resource-Helpers.ps1
Labels: EngSys, Central-EngSys

#4331 Remove mention of testing related changes from telemetry changelog
  sdk/core/azure-core-tracing-opentelemetry/CHANGELOG.md
Labels: Docs, OpenTelemetry

#4335 Compilation fixes for UWP
  sdk/attestation/azure-security-attestation/vcpkg/vcpkg.json
  sdk/core/azure-core/vcpkg/Config.cmake.in
  sdk/core/azure-core/vcpkg/vcpkg.json
  sdk/identity/azure-identity/src/azure_cli_credential.cpp
  sdk/identity/azure-identity/test/ut/azure_cli_credential_test.cpp
  sdk/identity/azure-identity/vcpkg/vcpkg.json
Labels: Azure.Core, Azure.Identity

#4183 update storage README
  sdk/storage/README.md
  sdk/storage/azure-storage-blobs/README.md
  sdk/storage/azure-storage-common/README.md
  sdk/storage/azure-storage-files-datalake/README.md
  sdk/storage/azure-storage-files-shares/README.md
  sdk/storage/azure-storage-queues/README.md
Labels: Storage

#4315 Core February Release
  sdk/core/azure-core/CHANGELOG.md
  sdk/core/azure-core/src/private/package_version.hpp
Labels: Azure.Core

#4330 Update artifacts for ci.yml
  cmake-modules/FolderList.cmake
  sdk/keyvault/azure-security-keyvault-administration/vcpkg.json
  sdk/keyvault/ci.yml
Labels: EngSys, KeyVault

#4318 update storage README(datalake&shares&queues)
  sdk/storage/azure-storage-files-datalake/README.md
  sdk/storage/azure-storage-files-shares/README.md
  sdk/storage/azure-storage-queues/README.md
Labels: Storage

#4115 Modify files by adding an extra space to trigger spell check on all files and fix any remaining issues to get the repo green
  sdk/core/azure-core/test/ut/response_t_test.cpp
Labels: EngSys, MQ

#4319 Feb key vault release
  sdk/keyvault/azure-security-keyvault-administration/CHANGELOG.md
  sdk/keyvault/azure-security-keyvault-administration/CMakeLists.txt
  sdk/keyvault/azure-security-keyvault-administration/vcpkg/Config.cmake.in
  sdk/keyvault/azure-security-keyvault-administration/vcpkg/vcpkg.json
  sdk/keyvault/azure-security-keyvault-certificates/CMakeSettings.json
Labels: KeyVault

#4317 Identity February Release
  sdk/identity/azure-identity/CHANGELOG.md
  sdk/identity/azure-identity/CMakeLists.txt
  sdk/identity/azure-identity/src/private/package_version.hpp
  sdk/identity/azure-identity/vcpkg/Config.cmake.in
  sdk/identity/azure-identity/vcpkg/vcpkg.json
Labels: Azure.Identity

#4326 Attestation February Release
  sdk/attestation/azure-security-attestation/CHANGELOG.md
  sdk/attestation/azure-security-attestation/CMakeLists.txt
  sdk/attestation/azure-security-attestation/src/private/package_version.hpp
  sdk/attestation/azure-security-attestation/vcpkg/Config.cmake.in
  sdk/attestation/azure-security-attestation/vcpkg/vcpkg.json
Labels: Attestation

#4348 Sync eng/common directory with azure-sdk-tools for PR 5083
  eng/common/pipelines/templates/jobs/perf.yml
Labels: EngSys, Central-EngSys

#4349 Update `CODEOWNERS` paths: fix invalid paths
  .github/CODEOWNERS
Labels: Central-EngSys

#4351 Sync eng/common directory with azure-sdk-tools for PR 5412
  eng/common/scripts/copy-docs-to-blobstorage.ps1
Labels: EngSys, Central-EngSys

#4352 Fix compilation on Visual Studio 2017
  sdk/core/azure-core/src/http/request.cpp
Labels: customer-reported

#4355 Update changelog to reflect community contribution
  sdk/core/azure-core/CHANGELOG.md
Labels: Azure.Core

#4356 Sync eng/common directory with azure-sdk-tools for PR 5427
  eng/common/scripts/Cadl-Project-Sync.ps1
Labels: EngSys, Central-EngSys

#4357 Sync eng/common directory with azure-sdk-tools for PR 5437
  eng/common/scripts/get-codeowners.ps1
Labels: EngSys, Central-EngSys

#4362 Sync eng/common directory with azure-sdk-tools for PR 5456
  eng/common/pipelines/templates/jobs/perf.yml
Labels: EngSys, Central-EngSys

#4367 Sync eng/common directory with azure-sdk-tools for PR 5103
  eng/common/scripts/get-codeowners.ps1
Labels: EngSys, Central-EngSys

#4368 Sync eng/common directory with azure-sdk-tools for PR 5493
  eng/common/pipelines/templates/stages/archetype-sdk-tool-pwsh.yml
Labels: EngSys, Central-EngSys

#4360 Where applicable, update Windows pools used to `azsdk-pool-mms-win-2022-general` and rename `vmImage` to the `windows-20xx` format
  eng/pipelines/daily-verification.yml
  eng/pipelines/templates/jobs/archetype-sdk-client.yml
  eng/pipelines/templates/stages/archetype-cpp-release.yml
  eng/pipelines/templates/stages/platform-matrix-cmakegenerate.json
  eng/pipelines/templates/stages/platform-matrix-cmakesourcegenerate.json
  eng/pipelines/templates/stages/platform-matrix-live.json
  eng/pipelines/templates/stages/platform-matrix.json
  eng/scripts/Get-BinarySizes.ps1
Labels: Central-EngSys

#4343 Trigger`keyvault` on proxy changes
  sdk/keyvault/ci.yml
  sdk/storage/ci.yml
Labels: Central-EngSys

#4302 Generate API review for C++ using new parser
  eng/pipelines/templates/jobs/archetype-sdk-client.yml
  eng/scripts/Create-APIReview.ps1
  eng/scripts/Language-Settings.ps1
  sdk/template/azure-template/inc/ApiViewSettings.json
Labels: Central-EngSys

#4376 Sync eng/common directory with azure-sdk-tools for PR 5531
  eng/common/pipelines/templates/jobs/perf.yml
Labels: EngSys, Central-EngSys

#4241 Test proxy & storage tests improvements
  sdk/attestation/assets.json
  sdk/attestation/azure-security-attestation/test/ut/policycertmgmt_test.cpp
  sdk/core/azure-core-test/inc/azure/core/test/network_models.hpp
  sdk/core/azure-core-test/inc/azure/core/test/test_base.hpp
  sdk/core/azure-core-test/inc/azure/core/test/test_proxy_manager.hpp
  sdk/core/azure-core-test/src/test_base.cpp
  sdk/core/azure-core-test/src/test_proxy_manager.cpp
  sdk/core/azure-core-test/src/test_proxy_policy.cpp
  sdk/core/azure-core/CHANGELOG.md
  sdk/core/azure-core/src/http/curl/curl.cpp
  sdk/storage/assets.json
  sdk/storage/azure-storage-blobs/inc/azure/storage/blobs/blob_options.hpp
  sdk/storage/azure-storage-blobs/test/ut/CMakeLists.txt
  sdk/storage/azure-storage-blobs/test/ut/append_blob_client_test.cpp
  sdk/storage/azure-storage-blobs/test/ut/append_blob_client_test.hpp
  sdk/storage/azure-storage-blobs/test/ut/blob_batch_client_test.cpp
  sdk/storage/azure-storage-blobs/test/ut/blob_container_client_test.cpp
  sdk/storage/azure-storage-blobs/test/ut/blob_container_client_test.hpp
  sdk/storage/azure-storage-blobs/test/ut/blob_query_test.cpp
  sdk/storage/azure-storage-blobs/test/ut/blob_sas_test.cpp
  sdk/storage/azure-storage-blobs/test/ut/blob_service_client_test.cpp
  sdk/storage/azure-storage-blobs/test/ut/blob_service_client_test.hpp
  sdk/storage/azure-storage-blobs/test/ut/block_blob_client_test.cpp
  sdk/storage/azure-storage-blobs/test/ut/block_blob_client_test.hpp
  sdk/storage/azure-storage-blobs/test/ut/page_blob_client_test.cpp
  sdk/storage/azure-storage-blobs/test/ut/page_blob_client_test.hpp
  sdk/storage/azure-storage-common/test/ut/bearer_token_test.cpp
  sdk/storage/azure-storage-common/test/ut/crypt_functions_test.cpp
  sdk/storage/azure-storage-common/test/ut/test_base.cpp
  sdk/storage/azure-storage-common/test/ut/test_base.hpp
  sdk/storage/azure-storage-files-datalake/test/ut/datalake_directory_client_test.cpp
  sdk/storage/azure-storage-files-datalake/test/ut/datalake_directory_client_test.hpp
  sdk/storage/azure-storage-files-datalake/test/ut/datalake_file_client_test.cpp
  sdk/storage/azure-storage-files-datalake/test/ut/datalake_file_client_test.hpp
  sdk/storage/azure-storage-files-datalake/test/ut/datalake_file_query_test.cpp
  sdk/storage/azure-storage-files-datalake/test/ut/datalake_file_system_client_test.cpp
  sdk/storage/azure-storage-files-datalake/test/ut/datalake_file_system_client_test.hpp
  sdk/storage/azure-storage-files-datalake/test/ut/datalake_path_client_test.cpp
  sdk/storage/azure-storage-files-datalake/test/ut/datalake_path_client_test.hpp
  sdk/storage/azure-storage-files-datalake/test/ut/datalake_sas_test.cpp
  sdk/storage/azure-storage-files-datalake/test/ut/datalake_service_client_test.cpp
  sdk/storage/azure-storage-files-datalake/test/ut/datalake_service_client_test.hpp
  sdk/storage/azure-storage-files-shares/test/ut/share_client_test.cpp
  sdk/storage/azure-storage-files-shares/test/ut/share_client_test.hpp
  sdk/storage/azure-storage-files-shares/test/ut/share_directory_client_test.cpp
  sdk/storage/azure-storage-files-shares/test/ut/share_directory_client_test.hpp
  sdk/storage/azure-storage-files-shares/test/ut/share_file_client_test.cpp
  sdk/storage/azure-storage-files-shares/test/ut/share_file_client_test.hpp
  sdk/storage/azure-storage-files-shares/test/ut/share_service_client_test.cpp
  sdk/storage/azure-storage-files-shares/test/ut/share_service_client_test.hpp
  sdk/storage/azure-storage-queues/test/ut/queue_client_messages_test.cpp
  sdk/storage/azure-storage-queues/test/ut/queue_client_test.cpp
  sdk/storage/azure-storage-queues/test/ut/queue_client_test.hpp
  sdk/storage/azure-storage-queues/test/ut/queue_service_client_test.cpp
Labels: Client, Storage, test-enhancement

#4378 Sync eng/common directory with azure-sdk-tools for PR 5537
  eng/common/pipelines/templates/steps/check-spelling.yml
Labels: EngSys, Central-EngSys

#4382 Storage tests improvement
  sdk/storage/assets.json
  sdk/storage/azure-storage-blobs/test/ut/append_blob_client_test.cpp
  sdk/storage/azure-storage-blobs/test/ut/blob_container_client_test.cpp
  sdk/storage/azure-storage-blobs/test/ut/block_blob_client_test.cpp
  sdk/storage/azure-storage-blobs/test/ut/page_blob_client_test.cpp
  sdk/storage/azure-storage-blobs/test/ut/storage_timeout_test.cpp
  sdk/storage/azure-storage-files-datalake/test/ut/datalake_file_client_test.cpp
  sdk/storage/azure-storage-queues/test/ut/queue_service_client_test.cpp
Labels: Storage, test-enhancement

#4379 show headers and query parameters in storage CI pipeline
  sdk/storage/azure-storage-blobs/test/ut/append_blob_client_test.cpp
  sdk/storage/azure-storage-blobs/test/ut/blob_batch_client_test.cpp
  sdk/storage/azure-storage-blobs/test/ut/blob_container_client_test.cpp
  sdk/storage/azure-storage-blobs/test/ut/blob_service_client_test.cpp
  sdk/storage/azure-storage-blobs/test/ut/blob_service_client_test.hpp
  sdk/storage/azure-storage-blobs/test/ut/block_blob_client_test.cpp
  sdk/storage/azure-storage-blobs/test/ut/page_blob_client_test.cpp
  sdk/storage/azure-storage-blobs/test/ut/storage_timeout_test.cpp
  sdk/storage/azure-storage-common/test/ut/bearer_token_test.cpp
  sdk/storage/azure-storage-common/test/ut/test_base.cpp
  sdk/storage/azure-storage-common/test/ut/test_base.hpp
  sdk/storage/azure-storage-files-datalake/test/ut/datalake_directory_client_test.cpp
  sdk/storage/azure-storage-files-datalake/test/ut/datalake_file_system_client_test.cpp
  sdk/storage/azure-storage-files-datalake/test/ut/datalake_path_client_test.cpp
  sdk/storage/azure-storage-files-datalake/test/ut/datalake_service_client_test.cpp
  sdk/storage/azure-storage-files-datalake/test/ut/datalake_service_client_test.hpp
  sdk/storage/azure-storage-files-shares/test/ut/share_client_test.cpp
  sdk/storage/azure-storage-files-shares/test/ut/share_file_client_test.cpp
  sdk/storage/azure-storage-files-shares/test/ut/share_service_client_test.cpp
  sdk/storage/azure-storage-queues/test/ut/queue_client_test.cpp
  sdk/storage/azure-storage-queues/test/ut/queue_service_client_test.cpp
Labels: Storage, test-enhancement

#4354 Sync eng/common directory with azure-sdk-tools for PR 5431
  eng/common/scripts/get-codeowners.ps1
Labels: EngSys, Central-EngSys

#4384 Sync eng/common directory with azure-sdk-tools for PR 5562
  eng/common/scripts/get-codeowners.ps1
Labels: EngSys, Central-EngSys

#4381 Fix Share Client failure #4377
  sdk/storage/assets.json
  sdk/storage/azure-storage-files-shares/src/rest_client.cpp
  sdk/storage/azure-storage-files-shares/swagger/README.md
  sdk/storage/azure-storage-files-shares/test/ut/share_client_test.cpp
Labels: Storage

#4385 Fix storage CI failures
  sdk/storage/azure-storage-blobs/test/ut/block_blob_client_test.cpp
  sdk/storage/azure-storage-files-datalake/test/ut/datalake_file_client_test.cpp
  sdk/storage/azure-storage-files-shares/test/ut/share_file_client_test.cpp
Labels: Client, Storage, test-enhancement

#4387 Sync eng/common directory with azure-sdk-tools for PR 5568
  eng/common/testproxy/transition-scripts/README.md
  eng/common/testproxy/transition-scripts/generate-assets-json.ps1
Labels: EngSys, Central-EngSys

#4361 Added support to ignore invalid cert common name
  sdk/core/azure-core/CHANGELOG.md
  sdk/core/azure-core/inc/azure/core/http/policies/policy.hpp
  sdk/core/azure-core/inc/azure/core/http/win_http_transport.hpp
  sdk/core/azure-core/src/http/curl/curl.cpp
  sdk/core/azure-core/src/http/transport_policy.cpp
  sdk/core/azure-core/src/http/winhttp/win_http_transport.cpp
Labels: Azure.Core, Client
