Repository Azure/azure-sdk-for-cpp, pull requests merged in 2023-01, with the labels that each got.

#4197 Audit string comparisons
  samples/helpers/get-env/src/get_env.cpp
  sdk/attestation/azure-security-attestation/samples/policy-certificates/cryptohelpers.hpp
  sdk/core/azure-core-test/inc/azure/core/test/test_base.hpp
  sdk/core/azure-core/CMakeLists.txt
  sdk/core/azure-core/inc/azure/core/http/http.hpp
  sdk/core/azure-core/inc/azure/core/internal/strings.hpp
  sdk/core/azure-core/inc/azure/core/url.hpp
  sdk/core/azure-core/src/datetime.cpp
  sdk/core/azure-core/src/environment_log_level_listener.cpp
  sdk/core/azure-core/src/http/curl/curl.cpp
  sdk/core/azure-core/src/http/http.cpp
  sdk/core/azure-core/src/http/raw_response.cpp
  sdk/core/azure-core/src/http/request.cpp
  sdk/core/azure-core/src/http/url.cpp
  sdk/core/azure-core/src/http/user_agent.cpp
  sdk/core/azure-core/src/strings.cpp
  sdk/core/azure-core/src/tracing/tracing.cpp
  sdk/core/azure-core/test/ut/string_test.cpp
  sdk/identity/azure-identity/src/azure_cli_credential.cpp
  sdk/keyvault/azure-security-keyvault-keys/src/key_rotation_policy.cpp
  sdk/storage/azure-storage-blobs/inc/azure/storage/blobs/rest_client.hpp
  sdk/storage/azure-storage-common/src/shared_key_policy.cpp
  sdk/storage/azure-storage-common/test/ut/test_base.cpp
  sdk/storage/azure-storage-files-shares/inc/azure/storage/files/shares/rest_client.hpp
  sdk/storage/azure-storage-queues/inc/azure/storage/queues/rest_client.hpp
Labels: Azure.Core, MQ

#4198 Remove noexcept specification from Azure::DateTime::clock::now()
  sdk/core/azure-core/CHANGELOG.md
  sdk/core/azure-core/inc/azure/core/datetime.hpp
Labels: Azure.Core, MQ

#4199 More accurate argument type for the ExtendableEnumeration == and !=
  sdk/core/azure-core/inc/azure/core/internal/extendable_enumeration.hpp
Labels: Azure.Core, MQ

#4200 noexcept adjustments
  sdk/core/azure-core/inc/azure/core/nullable.hpp
  sdk/core/azure-core/inc/azure/core/operation.hpp
  sdk/core/azure-core/src/http/winhttp/win_http_request.hpp
  sdk/core/azure-core/src/http/winhttp/win_http_transport.cpp
Labels: Azure.Core, MQ

#4201 PR follow-ups
  sdk/core/azure-core/CHANGELOG.md
  sdk/identity/azure-identity/CHANGELOG.md
  sdk/identity/azure-identity/inc/azure/identity/detail/token_cache.hpp
  sdk/identity/azure-identity/src/client_credential_core.cpp
  sdk/identity/azure-identity/test/ut/token_cache_test.cpp
Labels: Azure.Core, Azure.Identity

#4195 Move Request ctor impl to the request.cpp file instead of http.cpp
  sdk/core/azure-core/src/http/http.cpp
  sdk/core/azure-core/src/http/request.cpp
Labels: Azure.Core

#4218 Sync eng/common directory with azure-sdk-tools for PR 5005
  eng/common/pipelines/templates/jobs/archetype-sdk-tests-generate.yml
  eng/common/pipelines/templates/jobs/perf.yml
  eng/common/pipelines/templates/jobs/prepare-pipelines.yml
Labels: EngSys, Central-EngSys

#4225 Sync eng/common directory with azure-sdk-tools for PR 5054
  eng/common/pipelines/templates/jobs/perf.yml
Labels: EngSys, Central-EngSys

#4228 Sync eng/common directory with azure-sdk-tools for PR 5040
  eng/common/pipelines/templates/stages/archetype-sdk-tool-pwsh.yml
  eng/common/pipelines/templates/steps/run-pester-tests.yml
Labels: EngSys, Central-EngSys

#4229 Sync eng/common directory with azure-sdk-tools for PR 5085
  eng/common/scripts/get-codeowners.ps1
Labels: EngSys, Central-EngSys

#4231 Sync eng/common directory with azure-sdk-tools for PR 5095
  eng/common/scripts/job-matrix/job-matrix-functions.ps1
Labels: EngSys, Central-EngSys

#4243 Sync eng/common directory with azure-sdk-tools for PR 5121
  eng/common/scripts/Helpers/Service-Level-Readme-Automation-Helpers.ps1
Labels: EngSys, Central-EngSys

#4232 Nullable::Reset() hardening
  sdk/core/azure-core/inc/azure/core/nullable.hpp
Labels: Azure.Core

#4247 Sync eng/common directory with azure-sdk-tools for PR 5113
  eng/common/scripts/Update-DocsMsMetadata.ps1
Labels: EngSys, Central-EngSys

#4249 Sync eng/common directory with azure-sdk-tools for PR 5134
  eng/common/scripts/get-codeowners.ps1
Labels: EngSys, Central-EngSys

#4255 Fix spelling in doc comments within Certificate client models.
  .vscode/cspell.json
  sdk/keyvault/azure-security-keyvault-certificates/inc/azure/keyvault/certificates/certificate_client_models.hpp
Labels: KeyVault, auto-merge

#4267 Remove CHECKENFORCER file
  eng/CHECKENFORCER
Labels: Central-EngSys

#4261 Sync eng/common directory with azure-sdk-tools for PR 5169
  eng/common/TestResources/New-TestResources.ps1
Labels: EngSys, Central-EngSys

#4273 Updated link in the contributing markdown to fix link verification issue
  CONTRIBUTING.md
Labels: Docs, auto-merge

#4134 Add CI pipeline step and script that validates all files in the repo contain ASCII-only bytes and no UTF-8 BOM
  CMakeSettings.json
  doc/LibcurlTransportAdapter.md
  eng/pipelines/templates/jobs/ci.tests.yml
  eng/pipelines/templates/stages/platform-matrix.json
  sdk/core/azure-core/test/ut/proxy_tests/readme.md
  sdk/keyvault/azure-security-keyvault-administration/inc/azure/keyvault/administration/settings_client.hpp
  sdk/keyvault/azure-security-keyvault-administration/inc/azure/keyvault/administration/settings_client_options.hpp
  sdk/keyvault/azure-security-keyvault-administration/src/keyvault_settings_common_request.cpp
  sdk/keyvault/azure-security-keyvault-administration/src/private/administration_constants.hpp
  sdk/keyvault/azure-security-keyvault-administration/src/private/keyvault_settings_common_request.hpp
  sdk/keyvault/azure-security-keyvault-administration/test/ut/settings_client_base_test.hpp
  sdk/keyvault/azure-security-keyvault-administration/test/ut/settings_client_test.cpp
  sdk/keyvault/azure-security-keyvault-certificates/CMakeSettings.json
  sdk/keyvault/azure-security-keyvault-certificates/inc/azure/keyvault/certificates.hpp
  sdk/keyvault/azure-security-keyvault-certificates/inc/azure/keyvault/certificates/certificate_client.hpp
  sdk/keyvault/azure-security-keyvault-certificates/inc/azure/keyvault/certificates/certificate_client_models.hpp
  sdk/keyvault/azure-security-keyvault-certificates/inc/azure/keyvault/certificates/certificate_client_operations.hpp
  sdk/keyvault/azure-security-keyvault-certificates/inc/azure/keyvault/certificates/certificate_client_options.hpp
  sdk/keyvault/azure-security-keyvault-certificates/src/certificate_client.cpp
  sdk/keyvault/azure-security-keyvault-certificates/src/certificate_client_operations.cpp
  sdk/keyvault/azure-security-keyvault-certificates/src/certificate_serializers.cpp
  sdk/keyvault/azure-security-keyvault-certificates/src/keyvault_certificates_common_request.cpp
  sdk/keyvault/azure-security-keyvault-certificates/src/private/certificate_constants.hpp
  sdk/keyvault/azure-security-keyvault-certificates/src/private/certificate_serializers.hpp
  sdk/keyvault/azure-security-keyvault-certificates/src/private/keyvault_certificates_common_request.hpp
  sdk/keyvault/azure-security-keyvault-certificates/test/ut/certificate_client_base_test.hpp
  sdk/keyvault/azure-security-keyvault-certificates/test/ut/certificate_client_test.cpp
  sdk/keyvault/azure-security-keyvault-secrets/src/keyvault_secrets_common_request.cpp
  sdk/keyvault/azure-security-keyvault-secrets/src/private/keyvault_secrets_common_request.hpp
  sdk/keyvault/azure-security-keyvault-secrets/test/samples/sample2-backup-restore/sample2_backup_restore.cpp
  sdk/keyvault/azure-security-keyvault-secrets/test/samples/sample3-delete-recover/sample3_delete_recover.cpp
  sdk/storage/azure-storage-files-datalake/test/ut/datalake_path_client_test.cpp
Labels: EngSys, MQ

#4252 Ignore warning C4100 on Windows for unused parameter in OpenTelemetry headers.
  sdk/core/azure-core-tracing-opentelemetry/test/ut/service_support_test.cpp
Labels: OpenTelemetry

#4274 Sync eng/common directory with azure-sdk-tools for PR 5224
  eng/common/testproxy/publish-proxy-logs.yml
  eng/common/testproxy/test-proxy-tool.yml
  eng/pipelines/templates/jobs/ci.tests.yml
Labels: EngSys, Central-EngSys

#4294 Sync eng/common directory with azure-sdk-tools for PR 5242
  eng/common/TestResources/New-TestResources.ps1
  eng/common/TestResources/Remove-TestResources.ps1
  eng/common/TestResources/SubConfig-Helpers.ps1
  eng/common/TestResources/Update-TestResources.ps1
Labels: EngSys, Central-EngSys

#4288 Sync eng/common directory with azure-sdk-tools for PR 5231
  eng/common/scripts/Cadl-Project-Generate.ps1
  eng/common/scripts/Cadl-Project-Sync.ps1
  eng/common/scripts/common.ps1
Labels: EngSys, Central-EngSys

#4309 Sync eng/common directory with azure-sdk-tools for PR 5272
  eng/common/scripts/Cadl-Project-Generate.ps1
  eng/common/scripts/Cadl-Project-Sync.ps1
Labels: EngSys, Central-EngSys
