Repository Azure/azure-sdk-for-cpp, pull requests merged in 2024-09, with the labels that each got.

#5956 Sync eng/common directory with azure-sdk-tools for PR 8912
  eng/common/scripts/Package-Properties.ps1
Labels: EngSys, Central-EngSys

#5957 Sync eng/common directory with azure-sdk-tools for PR 8887
  eng/common/scripts/Verify-Links.ps1
Labels: EngSys, Central-EngSys

#5961 Sync eng/common directory with azure-sdk-tools for PR 8928
  eng/common/spelling/package-lock.json
Labels: EngSys, Central-EngSys

#5940 Tables readme update
  sdk/tables/azure-data-tables/README.md
Labels: Tables

#5946 Kv doc update
  sdk/keyvault/azure-security-keyvault-administration/README.md
  sdk/keyvault/azure-security-keyvault-certificates/README.md
  sdk/keyvault/azure-security-keyvault-keys/README.md
  sdk/keyvault/azure-security-keyvault-secrets/README.md
Labels: KeyVault

#5968 Sync .github/workflows directory with azure-sdk-tools for PR 8942
  .github/workflows/event-processor.yml
  .github/workflows/scheduled-event-processor.yml
Labels: EngSys, Central-EngSys

#5966 Sync eng/common directory with azure-sdk-tools for PR 8929
  eng/common/pipelines/templates/jobs/prepare-pipelines.yml
Labels: EngSys, Central-EngSys

#5965 Sync eng/common directory with azure-sdk-tools for PR 8902
  eng/common/TestResources/SubConfig-Helpers.ps1
  eng/common/TestResources/deploy-test-resources.yml
Labels: EngSys, Central-EngSys

#5927 Fix input validation check for TimeFractionFormat in the DateTime ToString method
  sdk/core/azure-core/CHANGELOG.md
  sdk/core/azure-core/src/datetime.cpp
  sdk/core/azure-core/test/ut/datetime_test.cpp
Labels: Azure.Core

#5976 Update CHANGELOG.md for September release
  sdk/core/azure-core-amqp/CHANGELOG.md
Labels: Azure.Core

#5975 Azure Core September Releases
  sdk/core/azure-core-amqp/CHANGELOG.md
  sdk/core/azure-core/CHANGELOG.md
Labels: Azure.Core

#5980 Increment version for core releases
  sdk/core/azure-core-amqp/CHANGELOG.md
  sdk/core/azure-core-amqp/src/private/package_version.hpp
  sdk/core/azure-core/CHANGELOG.md
  sdk/core/azure-core/src/private/package_version.hpp
Labels: Azure.Core

#5979 Add auto-baseline main pipeline config for core
  eng/pipelines/templates/stages/archetype-sdk-client.yml
Labels: Central-EngSys

#5982 Sync eng/common directory with azure-sdk-tools for PR 8959
  eng/common/pipelines/templates/steps/publish-1es-artifact.yml
Labels: EngSys, Central-EngSys

#5987 Sync eng/common directory with azure-sdk-tools for PR 8963
  eng/common/pipelines/templates/steps/run-pester-tests.yml
Labels: EngSys, Central-EngSys

#5988 Add support for sending an x5c parameter in the JWT token header for `ClientCertificateCredential`.
  sdk/identity/azure-identity/CHANGELOG.md
  sdk/identity/azure-identity/inc/azure/identity/client_certificate_credential.hpp
  sdk/identity/azure-identity/src/client_certificate_credential.cpp
  sdk/identity/azure-identity/test/ut/client_certificate_credential_test.cpp
Labels: Azure.Identity

#5989 Add support for passing in the x509 certificate and its corresponding private key directly to ClientCertificateCredential, rather than reading from a pem file.
  sdk/identity/azure-identity/CHANGELOG.md
  sdk/identity/azure-identity/inc/azure/identity/client_certificate_credential.hpp
  sdk/identity/azure-identity/src/client_certificate_credential.cpp
  sdk/identity/azure-identity/test/ut/client_certificate_credential_test.cpp
Labels: Azure.Identity

#5991 Accept base64 (PEM) encoded certificate as std::string instead of vector<uint8_t>
  sdk/identity/azure-identity/inc/azure/identity/client_certificate_credential.hpp
  sdk/identity/azure-identity/src/client_certificate_credential.cpp
  sdk/identity/azure-identity/test/ut/client_certificate_credential_test.cpp
Labels: Azure.Identity

#5994 Sync eng/common directory with azure-sdk-tools for PR 8974
  eng/common/scripts/Package-Properties.ps1
Labels: EngSys, Central-EngSys

#5977 Prepare for Azure Identity September Beta Release
  sdk/identity/azure-identity/CHANGELOG.md
Labels: Azure.Identity

#5998 Sync eng/common directory with azure-sdk-tools for PR 8994
  eng/common/pipelines/codeowners-linter.yml
Labels: EngSys, Central-EngSys

#5995 Pin windows image version
  eng/pipelines/templates/stages/platform-matrix-live.json
Labels: EngSys

#5993 Add const& to input std::string params in ClientCertificateCredential.
  sdk/identity/azure-identity/inc/azure/identity/client_certificate_credential.hpp
  sdk/identity/azure-identity/src/client_certificate_credential.cpp
Labels: Azure.Identity

#5999 Increment version for identity releases
  sdk/identity/azure-identity/CHANGELOG.md
  sdk/identity/azure-identity/src/private/package_version.hpp
Labels: Azure.Identity

#5967 Storage September Release
  cmake-modules/FolderList.cmake
  sdk/storage/azure-storage-blobs/CHANGELOG.md
  sdk/storage/azure-storage-blobs/src/private/package_version.hpp
  sdk/storage/azure-storage-blobs/vcpkg.json
  sdk/storage/azure-storage-blobs/vcpkg/vcpkg.json
  sdk/storage/azure-storage-common/CHANGELOG.md
  sdk/storage/azure-storage-common/src/private/package_version.hpp
  sdk/storage/azure-storage-common/vcpkg.json
  sdk/storage/azure-storage-common/vcpkg/vcpkg.json
  sdk/storage/azure-storage-files-datalake/CHANGELOG.md
  sdk/storage/azure-storage-files-datalake/src/private/package_version.hpp
  sdk/storage/azure-storage-files-datalake/vcpkg.json
  sdk/storage/azure-storage-files-datalake/vcpkg/vcpkg.json
  sdk/storage/azure-storage-files-shares/CHANGELOG.md
  sdk/storage/azure-storage-files-shares/src/private/package_version.hpp
  sdk/storage/azure-storage-files-shares/vcpkg.json
  sdk/storage/azure-storage-files-shares/vcpkg/vcpkg.json
  sdk/storage/azure-storage-queues/CHANGELOG.md
  sdk/storage/azure-storage-queues/src/private/package_version.hpp
  sdk/storage/azure-storage-queues/vcpkg.json
  sdk/storage/azure-storage-queues/vcpkg/vcpkg.json
Labels: Storage

#6003 Sync .github/workflows directory with azure-sdk-tools for PR 8995
  .github/workflows/event-processor.yml
  .github/workflows/scheduled-event-processor.yml
Labels: EngSys, Central-EngSys

#6004 Sync eng/common directory with azure-sdk-tools for PR 9000
  eng/common/pipelines/templates/jobs/perf.yml
Labels: EngSys, Central-EngSys

#6006 Sync eng/common directory with azure-sdk-tools for PR 9004
  eng/common/scripts/Helpers/Metadata-Helpers.ps1
Labels: EngSys, Central-EngSys

#6000 Address archboard review feedback for new Azure Identity features - renames
  sdk/identity/azure-identity/inc/azure/identity/managed_identity_credential.hpp
  sdk/identity/azure-identity/src/managed_identity_credential.cpp
  sdk/identity/azure-identity/test/ut/managed_identity_credential_test.cpp
Labels: Azure.Identity

#6009 Revert "Update PublishCodeCoverateResults task"
  eng/pipelines/templates/jobs/ci.tests.yml
  eng/pipelines/templates/jobs/live.tests.yml
Labels: EngSys

#6005 Sync eng/common directory with azure-sdk-tools for PR 8998
  eng/common/pipelines/templates/steps/verify-readmes.yml
Labels: EngSys, Central-EngSys

#6011 Sync eng/common directory with azure-sdk-tools for PR 9008
  eng/common/scripts/Package-Properties.ps1
Labels: EngSys, Central-EngSys

#6012 Sync eng/common directory with azure-sdk-tools for PR 9016
  eng/common/testproxy/target_version.txt
Labels: EngSys, Central-EngSys

#6014 Fix etag.hpp comment that breaks Doxygen 1.12.0
  sdk/core/azure-core/inc/azure/core/etag.hpp
Labels: Azure.Core, customer-reported, Community Contribution

#6015 Sync eng/common directory with azure-sdk-tools for PR 9022
  eng/common/pipelines/templates/jobs/prepare-pipelines.yml
Labels: EngSys, Central-EngSys

#6001 Allow x-vss-e2eid response header to be logged in AzurePipelinesCredential for diagnostics.
  .vscode/cspell.json
  sdk/identity/azure-identity/CHANGELOG.md
  sdk/identity/azure-identity/inc/azure/identity/azure_pipelines_credential.hpp
  sdk/identity/azure-identity/src/azure_pipelines_credential.cpp
  sdk/identity/azure-identity/test/ut/azure_pipelines_credential_test.cpp
Labels: Azure.Identity

#6019 Updated the request header sent to the OIDC endpoint in so it doesn't result in a redirect response when an invalid system access token is provided.
  sdk/identity/azure-identity/CHANGELOG.md
  sdk/identity/azure-identity/TROUBLESHOOTING.md
  sdk/identity/azure-identity/src/azure_pipelines_credential.cpp
  sdk/identity/azure-identity/test/ut/azure_pipelines_credential_test.cpp
Labels: Azure.Identity

#5838 Add a readme section for user and system assigned managed identity for ManagedIdentityCredential.
  sdk/identity/azure-identity/README.md
Labels: Docs, Azure.Identity

#6024 Disable static analysis for live test pipelines.
  eng/pipelines/templates/jobs/live.tests.yml
Labels: EngSys

#6021 Storage/STG96 Add ShareAccessTier.Premium
  sdk/storage/azure-storage-files-shares/swagger/README.md
Labels: Storage

#6013 Sync eng/common directory with azure-sdk-tools for PR 9013
  eng/common/scripts/check-spelling-in-changed-files.ps1
  eng/common/spelling/Invoke-Cspell.ps1
Labels: EngSys, Central-EngSys

#6018 Make the HTTP transport behavior consistent between WinHTTP and libcurl by disabling automatically following redirects on Windows.
  sdk/core/azure-core/CHANGELOG.md
  sdk/core/azure-core/src/http/curl/curl_connection_private.hpp
  sdk/core/azure-core/src/http/winhttp/win_http_transport.cpp
  sdk/core/azure-core/test/ut/transport_adapter_base_test.cpp
  sdk/core/azure-core/test/ut/transport_adapter_base_test.hpp
Labels: Azure.Core

#6027 Storage/STG96 File Ace for Copy
  sdk/storage/assets.json
  sdk/storage/azure-storage-files-shares/inc/azure/storage/files/shares/rest_client.hpp
  sdk/storage/azure-storage-files-shares/inc/azure/storage/files/shares/share_options.hpp
  sdk/storage/azure-storage-files-shares/src/rest_client.cpp
  sdk/storage/azure-storage-files-shares/src/share_file_client.cpp
  sdk/storage/azure-storage-files-shares/swagger/README.md
  sdk/storage/azure-storage-files-shares/test/ut/share_file_client_test.cpp
Labels: Storage

#6029 Increment version for storage releases
  sdk/storage/azure-storage-blobs/CHANGELOG.md
  sdk/storage/azure-storage-blobs/src/private/package_version.hpp
  sdk/storage/azure-storage-common/CHANGELOG.md
  sdk/storage/azure-storage-common/src/private/package_version.hpp
  sdk/storage/azure-storage-files-datalake/CHANGELOG.md
  sdk/storage/azure-storage-files-datalake/src/private/package_version.hpp
  sdk/storage/azure-storage-files-shares/CHANGELOG.md
  sdk/storage/azure-storage-files-shares/src/private/package_version.hpp
  sdk/storage/azure-storage-queues/CHANGELOG.md
  sdk/storage/azure-storage-queues/src/private/package_version.hpp
Labels: Storage

#6032 Sync eng/common directory with azure-sdk-tools for PR 9035
  eng/common/scripts/Verify-ChangeLogs.ps1
Labels: EngSys, Central-EngSys

#6033 Implement AMQP Session APIs in Rust.
  sdk/core/azure-core-amqp/inc/azure/core/amqp/internal/connection.hpp
  sdk/core/azure-core-amqp/inc/azure/core/amqp/internal/session.hpp
  sdk/core/azure-core-amqp/src/amqp/connection.cpp
  sdk/core/azure-core-amqp/src/impl/rust_amqp/amqp/connection.cpp
  sdk/core/azure-core-amqp/src/impl/rust_amqp/amqp/private/connection_impl.hpp
  sdk/core/azure-core-amqp/src/impl/rust_amqp/amqp/private/session_impl.hpp
  sdk/core/azure-core-amqp/src/impl/rust_amqp/amqp/session.cpp
  sdk/core/azure-core-amqp/src/impl/rust_amqp/rust_amqp/azure_core_amqp/src/fe2o3/session.rs
  sdk/core/azure-core-amqp/src/impl/rust_amqp/rust_amqp/azure_core_amqp/src/lib.rs
  sdk/core/azure-core-amqp/src/impl/rust_amqp/rust_amqp/azure_core_amqp/src/session.rs
  sdk/core/azure-core-amqp/src/impl/rust_amqp/rust_amqp/rust_wrapper/src/amqp/connection.rs
  sdk/core/azure-core-amqp/src/impl/rust_amqp/rust_amqp/rust_wrapper/src/amqp/mod.rs
  sdk/core/azure-core-amqp/src/impl/rust_amqp/rust_amqp/rust_wrapper/src/amqp/session.rs
  sdk/core/azure-core-amqp/src/impl/rust_amqp/rust_amqp/rust_wrapper/src/runtime_context.rs
  sdk/core/azure-core-amqp/src/impl/rust_amqp/rust_amqp/rust_wrapper/src/rust_error.rs
  sdk/core/azure-core-amqp/test/ut/session_tests.cpp
Labels: Azure.Core

#6023 Updating CODEOWNERS for 1espt config
  .github/CODEOWNERS
Labels: Central-EngSys

#6042 Remove unused included header from core within Identity that isn't available from the GA'd version of core
  sdk/identity/azure-identity/inc/azure/identity/managed_identity_credential.hpp
Labels: Azure.Identity

#6016 Fix building docs from subprojects by not using CMAKE_SOURCE_DIR
  cmake-modules/AzureDoxygen.cmake
Labels: Docs, customer-reported, Community Contribution

#6020 Use code snippets from managed identity credential samples in identity readme doc and fix minor generation issues
  doc/SnippetGeneration.md
  eng/scripts/Generate-Snippets.ps1
  sdk/core/azure-core-amqp/README.md
  sdk/core/azure-core-amqp/samples/README.md
  sdk/identity/azure-identity/README.md
  sdk/identity/azure-identity/samples/CMakeLists.txt
  sdk/identity/azure-identity/samples/managed_identity_credential.cpp
  sdk/keyvault/azure-security-keyvault-secrets/README.md
  sdk/keyvault/azure-security-keyvault-secrets/samples/sample1-basic-operations/sample1_basic_operations.cpp
Labels: Docs, EngSys, Azure.Identity, KeyVault

#6046 Sync eng/common directory with azure-sdk-tools for PR 9059
  eng/common/pipelines/codeowners-linter.yml
Labels: EngSys, Central-EngSys

#6045 Sync eng/common directory with azure-sdk-tools for PR 9057
  eng/common/scripts/Update-DocsMsPackages.ps1
Labels: EngSys, Central-EngSys

#6047 Acknowledge community contributions in Changelog
  .vscode/cspell.json
  sdk/core/azure-core/CHANGELOG.md
Labels: Docs, Azure.Core

#6030 Storage/STG96 Provisioned v2 billing model for Azure Files
  sdk/storage/assets.json
  sdk/storage/azure-storage-files-shares/inc/azure/storage/files/shares/rest_client.hpp
  sdk/storage/azure-storage-files-shares/inc/azure/storage/files/shares/share_options.hpp
  sdk/storage/azure-storage-files-shares/src/rest_client.cpp
  sdk/storage/azure-storage-files-shares/src/share_client.cpp
  sdk/storage/azure-storage-files-shares/swagger/README.md
  sdk/storage/azure-storage-files-shares/test/ut/share_client_test.cpp
  sdk/storage/azure-storage-files-shares/test/ut/share_service_client_test.cpp
Labels: Storage

#6048 Fix/unify links in CHANGELOG.md files
  sdk/core/azure-core/CHANGELOG.md
  sdk/eventhubs/azure-messaging-eventhubs/CHANGELOG.md
  sdk/identity/azure-identity/CHANGELOG.md
  sdk/keyvault/azure-security-keyvault-keys/CHANGELOG.md
Labels: Docs
