Repository Azure/azure-sdk-for-cpp, pull requests merged in 2024-03, with the labels that each got.

#5396 Make it clear that the BUILD_TESTING option is for testing purposes for contributors of the SDK and not supported for production use.
  CONTRIBUTING.md
  cmake-modules/FolderList.cmake
Labels: Docs

#5389 Use new macros in existing surface area, so that classes marked as final don't have virtual methods.
  cmake-modules/AzureDoxygen.cmake
  sdk/core/azure-core-amqp/CMakeLists.txt
  sdk/core/azure-core-tracing-opentelemetry/CMakeLists.txt
  sdk/core/azure-core/CMakeLists.txt
  sdk/core/azure-core/inc/azure/core/http/policies/policy.hpp
  sdk/core/azure-core/inc/azure/core/internal/test_hooks.hpp
  sdk/core/azure-core/test/ut/retry_policy_test.cpp
  sdk/identity/azure-identity/inc/azure/identity/azure_cli_credential.hpp
  sdk/identity/azure-identity/inc/azure/identity/detail/token_cache.hpp
  sdk/identity/azure-identity/inc/azure/identity/dll_import_export.hpp
  sdk/identity/azure-identity/test/ut/token_cache_test.cpp
  sdk/keyvault/CMakeLists.txt
  sdk/keyvault/azure-security-keyvault-certificates/CMakeLists.txt
  sdk/keyvault/azure-security-keyvault-certificates/inc/azure/keyvault/certificates/certificate_client.hpp
  sdk/keyvault/azure-security-keyvault-keys/inc/azure/keyvault/keys/key_client.hpp
  sdk/keyvault/azure-security-keyvault-secrets/inc/azure/keyvault/secrets/secret_client.hpp
Labels: Azure.Core, Azure.Identity, KeyVault

#5390 Rename the TESTING_BUILD macro to be _azure_TESTING_BUILD to highlight this is internal only and reduce chances of collision.
  sdk/core/azure-core-amqp/CMakeLists.txt
  sdk/core/azure-core-amqp/inc/azure/core/amqp/internal/claims_based_security.hpp
  sdk/core/azure-core-amqp/inc/azure/core/amqp/internal/connection.hpp
  sdk/core/azure-core-amqp/inc/azure/core/amqp/internal/link.hpp
  sdk/core/azure-core-amqp/inc/azure/core/amqp/internal/session.hpp
  sdk/core/azure-core-amqp/src/amqp/claim_based_security.cpp
  sdk/core/azure-core-amqp/src/amqp/link.cpp
  sdk/core/azure-core-tracing-opentelemetry/CMakeLists.txt
  sdk/core/azure-core/CMakeLists.txt
  sdk/core/azure-core/inc/azure/core/http/http.hpp
  sdk/core/azure-core/src/http/curl/curl_connection_pool_private.hpp
  sdk/core/azure-core/src/http/curl/curl_session_private.hpp
  sdk/identity/azure-identity/CMakeLists.txt
  sdk/identity/azure-identity/inc/azure/identity/default_azure_credential.hpp
  sdk/identity/azure-identity/src/private/chained_token_credential_impl.hpp
  sdk/identity/azure-identity/src/token_cache.cpp
  sdk/keyvault/CMakeLists.txt
  sdk/keyvault/azure-security-keyvault-certificates/CMakeLists.txt
  sdk/keyvault/azure-security-keyvault-certificates/inc/azure/keyvault/certificates/certificate_client.hpp
Labels: Azure.Core, Azure.Identity, KeyVault

#5406 Remove the use of ifdef for TESTING_BUILD in KeyVault clients, where they are not needed.
  sdk/keyvault/azure-security-keyvault-certificates/inc/azure/keyvault/certificates/certificate_client.hpp
  sdk/keyvault/azure-security-keyvault-secrets/inc/azure/keyvault/secrets/secret_client.hpp
Labels: KeyVault

#5355 Sync eng/common directory with azure-sdk-tools for PR 7686
  eng/common/scripts/job-matrix/job-matrix-functions.ps1
Labels: EngSys, Central-EngSys

#5409 Sync .github/workflows directory with azure-sdk-tools for PR 7808
  .github/workflows/scheduled-event-processor.yml
Labels: EngSys, Central-EngSys

#5410 Sync eng/common directory with azure-sdk-tools for PR 7758
  eng/common/pipelines/templates/jobs/generate-job-matrix.yml
  eng/common/pipelines/templates/steps/publish-1es-artifact.yml
Labels: EngSys, Central-EngSys

#5398 Fix warnings that block the Live CI pipeline
  sdk/core/azure-core-tracing-opentelemetry/inc/azure/core/tracing/opentelemetry/opentelemetry.hpp
  sdk/core/azure-core-tracing-opentelemetry/src/opentelemetry.cpp
  sdk/core/azure-core-tracing-opentelemetry/src/opentelemetry_private.hpp
  sdk/core/azure-core-tracing-opentelemetry/test/ut/azure_core_otel_test.cpp
  sdk/core/azure-core-tracing-opentelemetry/test/ut/service_support_test.cpp
  sdk/core/azure-core-tracing-opentelemetry/test/ut/test_exporter.hpp
  sdk/eventhubs/azure-messaging-eventhubs-checkpointstore-blob/test/ut/blob_checkpoint_store_test.cpp
  sdk/eventhubs/azure-messaging-eventhubs/test/CMakeLists.txt
  sdk/eventhubs/azure-messaging-eventhubs/test/eventhubs-stress-test/src/eventhubs_stress_test.cpp
  sdk/eventhubs/azure-messaging-eventhubs/test/eventhubs-stress-test/src/inc/argagg.hpp
  sdk/eventhubs/azure-messaging-eventhubs/test/eventhubs-stress-test/src/scenarios/inc/batch_stress_tests.hpp
  sdk/eventhubs/azure-messaging-eventhubs/test/eventhubs-stress-test/src/scenarios/inc/opentelemetry_helpers.hpp
  sdk/eventhubs/ci.yml
Labels: Azure.Core, Event Hubs

#5412 Sync eng/common directory with azure-sdk-tools for PR 7810
  eng/common/pipelines/templates/jobs/generate-job-matrix.yml
  eng/common/pipelines/templates/steps/publish-1es-artifact.yml
  eng/common/scripts/Verify-AgentOS.ps1
Labels: EngSys, Central-EngSys

#5413 Sync eng/common directory with azure-sdk-tools for PR 7823
  eng/common/TestResources/New-TestResources.ps1
Labels: EngSys, Central-EngSys

#5416 Revert commits related to `_azure_BUILD_FOR_TESTING` and `_azure_*_FOR_TESTS`
  cmake-modules/AzureDoxygen.cmake
  sdk/core/azure-core-amqp/CMakeLists.txt
  sdk/core/azure-core-amqp/inc/azure/core/amqp/internal/claims_based_security.hpp
  sdk/core/azure-core-amqp/inc/azure/core/amqp/internal/connection.hpp
  sdk/core/azure-core-amqp/inc/azure/core/amqp/internal/link.hpp
  sdk/core/azure-core-amqp/inc/azure/core/amqp/internal/session.hpp
  sdk/core/azure-core-amqp/src/amqp/claim_based_security.cpp
  sdk/core/azure-core-amqp/src/amqp/link.cpp
  sdk/core/azure-core-tracing-opentelemetry/CMakeLists.txt
  sdk/core/azure-core/CMakeLists.txt
  sdk/core/azure-core/inc/azure/core/http/http.hpp
  sdk/core/azure-core/inc/azure/core/http/policies/policy.hpp
  sdk/core/azure-core/inc/azure/core/internal/test_hooks.hpp
  sdk/core/azure-core/src/http/curl/curl_connection_pool_private.hpp
  sdk/core/azure-core/src/http/curl/curl_session_private.hpp
  sdk/core/azure-core/test/ut/retry_policy_test.cpp
  sdk/identity/azure-identity/CMakeLists.txt
  sdk/identity/azure-identity/inc/azure/identity/azure_cli_credential.hpp
  sdk/identity/azure-identity/inc/azure/identity/default_azure_credential.hpp
  sdk/identity/azure-identity/inc/azure/identity/detail/token_cache.hpp
  sdk/identity/azure-identity/src/private/chained_token_credential_impl.hpp
  sdk/identity/azure-identity/src/token_cache.cpp
  sdk/identity/azure-identity/test/ut/azure_cli_credential_test.cpp
  sdk/identity/azure-identity/test/ut/token_cache_test.cpp
  sdk/keyvault/CMakeLists.txt
  sdk/keyvault/azure-security-keyvault-certificates/CMakeLists.txt
  sdk/keyvault/azure-security-keyvault-certificates/inc/azure/keyvault/certificates/certificate_client.hpp
  sdk/keyvault/azure-security-keyvault-keys/inc/azure/keyvault/keys/key_client.hpp
  sdk/keyvault/azure-security-keyvault-secrets/inc/azure/keyvault/secrets/secret_client.hpp
Labels: Azure.Core, blocking-release, Azure.Identity, KeyVault

#5418 Remove the use of ifdef for TESTING_BUILD in KeyVault clients, where they are not needed.
  sdk/keyvault/azure-security-keyvault-certificates/inc/azure/keyvault/certificates/certificate_client.hpp
  sdk/keyvault/azure-security-keyvault-secrets/inc/azure/keyvault/secrets/secret_client.hpp
Labels: KeyVault

#5428 Sync eng/common directory with azure-sdk-tools for PR 7842
  eng/common/scripts/Test-SampleMetadata.ps1
Labels: EngSys, Central-EngSys

#5429 Sync eng/common directory with azure-sdk-tools for PR 7835
  eng/common/scripts/Prepare-Release.ps1
Labels: EngSys, Central-EngSys

#5430 Sync .github/workflows directory with azure-sdk-tools for PR 7845
  .github/workflows/event-processor.yml
Labels: EngSys, Central-EngSys

#5393 Fixing links in Event Hubs README.md
  sdk/eventhubs/azure-messaging-eventhubs-checkpointstore-blob/README.md
  sdk/eventhubs/azure-messaging-eventhubs/README.md
Labels: Event Hubs

#5433 Sync .github/workflows directory with azure-sdk-tools for PR 7848
  .github/workflows/event-processor.yml
  .github/workflows/scheduled-event-processor.yml
Labels: EngSys, Central-EngSys

#5434 Sync .github/workflows directory with azure-sdk-tools for PR 7853
  .github/workflows/event-processor.yml
  .github/workflows/scheduled-event-processor.yml
Labels: EngSys, Central-EngSys

#5435 Sync eng/common directory with azure-sdk-tools for PR 7854
  eng/common/scripts/job-matrix/job-matrix-functions.ps1
Labels: EngSys, Central-EngSys

#5441 `1ES Template` Refactor
  .vscode/cspell.json
  eng/pipelines/templates/jobs/archetype-sdk-client.yml
  eng/pipelines/templates/jobs/ci.tests.yml
  eng/pipelines/templates/jobs/cmake-generate-jobs.yml
  eng/pipelines/templates/jobs/cmake-generate.tests.yml
  eng/pipelines/templates/jobs/live.tests.yml
  eng/pipelines/templates/stages/archetype-cpp-release.yml
  eng/pipelines/templates/stages/archetype-sdk-client.yml
  eng/pipelines/templates/stages/archetype-sdk-tests.yml
  eng/pipelines/templates/stages/platform-matrix-cmakegenerate.json
  eng/pipelines/templates/stages/platform-matrix-cmakesourcegenerate.json
  eng/pipelines/templates/stages/platform-matrix-live.json
  eng/pipelines/templates/stages/platform-matrix-quick.json
  eng/pipelines/templates/stages/platform-matrix.json
  eng/pipelines/templates/variables/image.yml
  eng/scripts/Get-BinarySizes.ps1
  sdk/attestation/ci.yml
  sdk/core/ci.yml
  sdk/eventhubs/ci.yml
  sdk/identity/ci.yml
  sdk/keyvault/ci.yml
  sdk/storage/ci.yml
  sdk/tables/ci.yml
  sdk/template/ci.yml
Labels: Azure.Core, EngSys, Storage, Azure.Identity, KeyVault, Attestation, Event Hubs, Tables

#5439 Update README.md
  sdk/attestation/azure-security-attestation/samples/README.md
Labels: Attestation

#5444 Sync eng/common directory with azure-sdk-tools for PR 7821
  eng/common/scripts/Create-APIReview.ps1
Labels: EngSys, Central-EngSys

#5374 Added blocking Open for message sender
  CMakeLists.txt
  sdk/core/azure-core-amqp/inc/azure/core/amqp/internal/link.hpp
  sdk/core/azure-core-amqp/inc/azure/core/amqp/internal/management.hpp
  sdk/core/azure-core-amqp/inc/azure/core/amqp/internal/message_sender.hpp
  sdk/core/azure-core-amqp/samples/internal/eventhub_get_properties_sample/eventhub_get_eventhub_properties_sample.cpp
  sdk/core/azure-core-amqp/samples/internal/eventhub_sas_writer_sample/eventhub_sas_writer_sample.cpp
  sdk/core/azure-core-amqp/samples/internal/eventhub_token_writer_sample/eventhub_token_writer_sample.cpp
  sdk/core/azure-core-amqp/samples/internal/local_client_async_sample/local_client_async_sample.cpp
  sdk/core/azure-core-amqp/samples/internal/local_client_sample/local_client_sample.cpp
  sdk/core/azure-core-amqp/src/amqp/connection.cpp
  sdk/core/azure-core-amqp/src/amqp/link.cpp
  sdk/core/azure-core-amqp/src/amqp/management.cpp
  sdk/core/azure-core-amqp/src/amqp/message_sender.cpp
  sdk/core/azure-core-amqp/src/amqp/private/claims_based_security_impl.hpp
  sdk/core/azure-core-amqp/src/amqp/private/link_impl.hpp
  sdk/core/azure-core-amqp/src/amqp/private/message_sender_impl.hpp
  sdk/core/azure-core-amqp/test/ut/claim_based_security_tests.cpp
  sdk/core/azure-core-amqp/test/ut/management_tests.cpp
  sdk/core/azure-core-amqp/test/ut/message_sender_receiver.cpp
  sdk/core/azure-core-amqp/test/ut/mock_amqp_server.hpp
  sdk/core/azure-core-amqp/vendor/azure-uamqp-c/src/link.c
  sdk/core/azure-core-amqp/vendor/azure-uamqp-c/src/session.c
  sdk/core/azure-core/inc/azure/core/azure_assert.hpp
  sdk/core/azure-core/src/environment_log_level_listener.cpp
  sdk/eventhubs/azure-messaging-eventhubs/CHANGELOG.md
  sdk/eventhubs/azure-messaging-eventhubs/inc/azure/messaging/eventhubs/event_data_batch.hpp
  sdk/eventhubs/azure-messaging-eventhubs/samples/produce-events/produce_events.cpp
  sdk/eventhubs/azure-messaging-eventhubs/samples/produce-events/produce_events_aad.cpp
  sdk/eventhubs/azure-messaging-eventhubs/src/event_data.cpp
  sdk/eventhubs/azure-messaging-eventhubs/src/event_data_batch.cpp
  sdk/eventhubs/azure-messaging-eventhubs/src/private/eventhubs_utilities.hpp
  sdk/eventhubs/azure-messaging-eventhubs/src/producer_client.cpp
  sdk/eventhubs/azure-messaging-eventhubs/test/eventhubs-stress-test/src/CMakeLists.txt
  sdk/eventhubs/azure-messaging-eventhubs/test/eventhubs-stress-test/src/eventhubs_stress_test.cpp
  sdk/eventhubs/azure-messaging-eventhubs/test/eventhubs-stress-test/src/inc/argagg.hpp
  sdk/eventhubs/azure-messaging-eventhubs/test/eventhubs-stress-test/src/scenarios/inc/batch_stress_tests.hpp
  sdk/eventhubs/azure-messaging-eventhubs/test/eventhubs-stress-test/src/scenarios/inc/event_sender.hpp
  sdk/eventhubs/azure-messaging-eventhubs/test/eventhubs-stress-test/src/scenarios/inc/opentelemetry_helpers.hpp
  sdk/eventhubs/azure-messaging-eventhubs/test/eventhubs-stress-test/src/scenarios/inc/shared_functions.hpp
  sdk/eventhubs/azure-messaging-eventhubs/test/eventhubs-stress-test/src/scenarios/src/batch_stress_tests.cpp
  sdk/eventhubs/azure-messaging-eventhubs/test/eventhubs-stress-test/src/scenarios/src/opentelemetry_helpers.cpp
  sdk/eventhubs/azure-messaging-eventhubs/test/eventhubs-stress-test/src/scenarios/src/shared_functions.cpp
  sdk/eventhubs/azure-messaging-eventhubs/test/eventhubs-stress-test/stress-test-resources.bicep
  sdk/eventhubs/azure-messaging-eventhubs/test/eventhubs-stress-test/templates/deploy-job.yaml
  sdk/eventhubs/azure-messaging-eventhubs/test/perf/inc/azure/messaging/eventhubs/test/eventhubs_batch_perf_test.hpp
  sdk/eventhubs/azure-messaging-eventhubs/test/ut/consumer_client_test.cpp
  sdk/eventhubs/azure-messaging-eventhubs/test/ut/processor_test.cpp
  sdk/eventhubs/azure-messaging-eventhubs/test/ut/producer_client_test.cpp
  sdk/eventhubs/azure-messaging-eventhubs/test/ut/round_trip_test.cpp
  sdk/eventhubs/ci.yml
Labels: Azure.Core, Event Hubs

#5447 Storage/ Update test records
  sdk/storage/assets.json
Labels: Storage

#5449 Sync eng/common directory with azure-sdk-tools for PR 7877
  eng/common/testproxy/test-proxy-tool-shutdown.yml
  eng/common/testproxy/test-proxy-tool.yml
Labels: EngSys, Central-EngSys

#5445 Keyvault regen
  sdk/keyvault/assets.json
  sdk/keyvault/azure-security-keyvault-certificates/inc/azure/keyvault/certificates/certificate_client_options.hpp
  sdk/keyvault/azure-security-keyvault-certificates/test/ut/certificate_client_test.cpp
  sdk/keyvault/azure-security-keyvault-keys/inc/azure/keyvault/keys/cryptography/cryptography_client_options.hpp
  sdk/keyvault/azure-security-keyvault-keys/inc/azure/keyvault/keys/key_client_models.hpp
  sdk/keyvault/azure-security-keyvault-keys/inc/azure/keyvault/keys/key_client_options.hpp
  sdk/keyvault/azure-security-keyvault-keys/src/keyvault_key.cpp
  sdk/keyvault/azure-security-keyvault-keys/src/private/key_constants.hpp
  sdk/keyvault/azure-security-keyvault-keys/test/ut-hsm/key_client_test_hsm_live.cpp
  sdk/keyvault/azure-security-keyvault-keys/test/ut/key_client_test.cpp
  sdk/keyvault/azure-security-keyvault-secrets/inc/azure/keyvault/secrets/keyvault_options.hpp
  sdk/keyvault/azure-security-keyvault-secrets/test/ut/secret_client_test.cpp
  sdk/keyvault/ci.yml
Labels: KeyVault

#5448 Troublesooting guides 4742
  sdk/keyvault/TROUBLESHOOTING.md
  sdk/keyvault/azure-security-keyvault-administration/TROUBLESHOOTING.md
  sdk/keyvault/azure-security-keyvault-certificates/TROUBLESHOOTING.md
  sdk/keyvault/azure-security-keyvault-keys/TROUBLESHOOTING.md
  sdk/keyvault/azure-security-keyvault-secrets/TROUBLESHOOTING.md
Labels: KeyVault

#5440 Match doc comments to method names
  sdk/attestation/azure-security-attestation/inc/azure/attestation/attestation_client_models.hpp
  sdk/attestation/azure-security-attestation/inc/azure/attestation/attestation_client_options.hpp
  sdk/attestation/azure-security-attestation/samples/policy/set_policy.cpp
  sdk/attestation/azure-security-attestation/samples/policy/set_sealed_policy.cpp
  sdk/attestation/azure-security-attestation/src/private/attestation_client_models_private.hpp
  sdk/attestation/azure-security-attestation/test/ut/policygetset_test.cpp
Labels: Attestation

#5451 Sync eng/common directory with azure-sdk-tools for PR 7892
  eng/common/pipelines/templates/steps/bypass-local-dns.yml
  eng/common/pipelines/templates/steps/git-push-changes.yml
  eng/common/scripts/check-for-git-changes.ps1
  eng/common/testproxy/publish-proxy-logs.yml
Labels: EngSys, Central-EngSys

#5408 Api view comments
  sdk/core/azure-core/inc/azure/core/internal/strings.hpp
  sdk/core/azure-core/test/perf/inc/azure/core/test/pipeline_test.hpp
  sdk/core/azure-core/test/ut/string_test.cpp
  sdk/tables/assets.json
  sdk/tables/azure-data-tables/CMakeLists.txt
  sdk/tables/azure-data-tables/inc/azure/data/tables.hpp
  sdk/tables/azure-data-tables/inc/azure/data/tables/account_sas_builder.hpp
  sdk/tables/azure-data-tables/inc/azure/data/tables/credentials/azure_sas_credential.hpp
  sdk/tables/azure-data-tables/inc/azure/data/tables/credentials/shared_key_credential.hpp
  sdk/tables/azure-data-tables/inc/azure/data/tables/enum_operators.hpp
  sdk/tables/azure-data-tables/inc/azure/data/tables/internal/serializers.hpp
  sdk/tables/azure-data-tables/inc/azure/data/tables/models.hpp
  sdk/tables/azure-data-tables/inc/azure/data/tables/tables_clients.hpp
  sdk/tables/azure-data-tables/inc/azure/data/tables/tables_sas_builder.hpp
  sdk/tables/azure-data-tables/samples/tables_entity_operations.cpp
  sdk/tables/azure-data-tables/samples/tables_getting_started.cpp
  sdk/tables/azure-data-tables/samples/tables_service_operations.cpp
  sdk/tables/azure-data-tables/src/models.cpp
  sdk/tables/azure-data-tables/src/serializers.cpp
  sdk/tables/azure-data-tables/src/tables_clients.cpp
  sdk/tables/azure-data-tables/src/tables_sas_builder.cpp
  sdk/tables/azure-data-tables/test/ut/CMakeLists.txt
  sdk/tables/azure-data-tables/test/ut/enum_operators_test.cpp
  sdk/tables/azure-data-tables/test/ut/enum_operators_test.hpp
  sdk/tables/azure-data-tables/test/ut/sas_test.cpp
  sdk/tables/azure-data-tables/test/ut/sas_test.hpp
  sdk/tables/azure-data-tables/test/ut/table_client_test.cpp
  sdk/tables/azure-data-tables/test/ut/table_client_test.hpp
Labels: Tables

#5453 Sync eng/common directory with azure-sdk-tools for PR 7841
  eng/common/pipelines/templates/steps/create-apireview.yml
  eng/common/scripts/Create-APIReview.ps1
  eng/common/scripts/Helpers/ApiView-Helpers.ps1
Labels: EngSys, Central-EngSys

#5455 Sync eng/common directory with azure-sdk-tools for PR 7896
  eng/common/testproxy/onboarding/common-asset-functions.ps1
  eng/common/testproxy/onboarding/generate-assets-json.ps1
Labels: EngSys, Central-EngSys

#5456 Get entity api
  sdk/tables/assets.json
  sdk/tables/azure-data-tables/inc/azure/data/tables/tables_clients.hpp
  sdk/tables/azure-data-tables/src/tables_clients.cpp
  sdk/tables/azure-data-tables/test/ut/table_client_test.cpp
Labels: Tables

#5452 Sync eng/common directory with azure-sdk-tools for PR 7895
  eng/common/testproxy/target_version.txt
Labels: EngSys, Central-EngSys

#5458 Update pipeline step to remove deprecated params in API view script
  eng/pipelines/templates/jobs/archetype-sdk-client.yml
  eng/scripts/Create-APIReview.ps1
  eng/scripts/Language-Settings.ps1
Labels: Central-EngSys

#5461 Get entity
  sdk/tables/azure-data-tables/inc/azure/data/tables/tables_clients.hpp
Labels: Tables

#5468 Sync eng/common directory with azure-sdk-tools for PR 7951
  eng/common/scripts/Update-DocsMsMetadata.ps1
Labels: EngSys, Central-EngSys

#5459 Sync eng/common directory with azure-sdk-tools for PR 7855
  eng/common/pipelines/templates/steps/validate-all-packages.yml
  eng/common/scripts/ChangeLog-Operations.ps1
  eng/common/scripts/Helpers/ApiView-Helpers.ps1
  eng/common/scripts/Helpers/DevOps-WorkItem-Helpers.ps1
  eng/common/scripts/Update-DevOps-Release-WorkItem.ps1
  eng/common/scripts/Validate-All-Packages.ps1
  eng/common/scripts/Validate-Package.ps1
Labels: EngSys, Central-EngSys

#5470 Sync eng/common directory with azure-sdk-tools for PR 7977
  eng/common/scripts/Create-APIReview.ps1
Labels: EngSys, Central-EngSys
