Repository Azure/azure-sdk-for-cpp, pull requests merged in 2024-12, with the labels that each got.

#6272 Sync eng/common directory with azure-sdk-tools for PR 9440
  eng/common/scripts/Helpers/PSModule-Helpers.ps1
Labels: EngSys, Central-EngSys

#6279 Sync eng/common directory with azure-sdk-tools for PR 9471
  eng/common/scripts/Helpers/DevOps-WorkItem-Helpers.ps1
Labels: EngSys, Central-EngSys

#6280 Sync eng/common directory with azure-sdk-tools for PR 9466
  eng/common/pipelines/templates/jobs/prepare-pipelines.yml
  eng/common/pipelines/templates/steps/install-pipeline-generation.yml
Labels: EngSys, Central-EngSys

#6277 Split out paged response types into its own header and re-enable KeyLabel Entity field.
  sdk/appconfiguration/azure-data-appconfiguration/CMakeLists.txt
  sdk/appconfiguration/azure-data-appconfiguration/inc/azure/data/appconfiguration.hpp
  sdk/appconfiguration/azure-data-appconfiguration/inc/azure/data/appconfiguration/configuration_client.hpp
  sdk/appconfiguration/azure-data-appconfiguration/inc/azure/data/appconfiguration/configuration_client_models.hpp
  sdk/appconfiguration/azure-data-appconfiguration/inc/azure/data/appconfiguration/configuration_client_options.hpp
  sdk/appconfiguration/azure-data-appconfiguration/inc/azure/data/appconfiguration/configuration_client_paged_responses.hpp
  sdk/appconfiguration/azure-data-appconfiguration/src/configuration_client.cpp
Labels: App Configuration

#6275 Sync eng/common directory with azure-sdk-tools for PR 9460
  eng/common/testproxy/publish-proxy-logs.yml
  eng/common/testproxy/test-proxy-standalone-tool.yml
  eng/common/testproxy/test-proxy-tool.yml
Labels: EngSys, Central-EngSys

#6282 Sync .github/workflows directory with azure-sdk-tools for PR 9490
  .github/workflows/event-processor.yml
  .github/workflows/scheduled-event-processor.yml
Labels: EngSys, Central-EngSys

#6284 Sync eng/common directory with azure-sdk-tools for PR 9497
  eng/common/testproxy/target_version.txt
Labels: EngSys, Central-EngSys

#6285 Storage STG97/NFS REST Part2(Impl+test)
  sdk/core/azure-core-test/src/test_proxy_manager.cpp
  sdk/storage/assets.json
  sdk/storage/azure-storage-common/src/account_sas_builder.cpp
  sdk/storage/azure-storage-files-shares/inc/azure/storage/files/shares/rest_client.hpp
  sdk/storage/azure-storage-files-shares/inc/azure/storage/files/shares/share_options.hpp
  sdk/storage/azure-storage-files-shares/inc/azure/storage/files/shares/share_responses.hpp
  sdk/storage/azure-storage-files-shares/src/rest_client.cpp
  sdk/storage/azure-storage-files-shares/src/share_directory_client.cpp
  sdk/storage/azure-storage-files-shares/src/share_file_client.cpp
  sdk/storage/azure-storage-files-shares/src/share_options.cpp
  sdk/storage/azure-storage-files-shares/swagger/README.md
  sdk/storage/azure-storage-files-shares/test/ut/CMakeLists.txt
  sdk/storage/azure-storage-files-shares/test/ut/share_directory_client_test.cpp
  sdk/storage/azure-storage-files-shares/test/ut/share_file_client_test.cpp
  sdk/storage/azure-storage-files-shares/test/ut/share_utility_test.cpp
Labels: Storage

#6283 Sync eng/common directory with azure-sdk-tools for PR 9493
  eng/common/scripts/Helpers/PSModule-Helpers.ps1
  eng/common/scripts/Helpers/Package-Helpers.ps1
Labels: EngSys, Central-EngSys

#6286 Add samples for Get, Set, and Delete Configuration Settings with comparisons of what we'd expect the user experience to be.
  sdk/appconfiguration/azure-data-appconfiguration/samples/appconfig_basic_operation.cpp
Labels: App Configuration

#6304 Storage/STG97 Remove Create/Get SymbolicLink API
  sdk/storage/assets.json
  sdk/storage/azure-storage-files-shares/inc/azure/storage/files/shares/share_file_client.hpp
  sdk/storage/azure-storage-files-shares/inc/azure/storage/files/shares/share_options.hpp
  sdk/storage/azure-storage-files-shares/inc/azure/storage/files/shares/share_responses.hpp
  sdk/storage/azure-storage-files-shares/src/share_file_client.cpp
  sdk/storage/azure-storage-files-shares/test/ut/share_file_client_test.cpp
Labels: Storage

#6310 added missing link to identity readme
  sdk/identity/azure-identity/README.md
Labels: Azure.Identity
