Repository Azure/azure-sdk-for-cpp, pull requests merged in 2024-11, with the labels that each got.

#6163 Rename UserAgentGenerator
  sdk/core/azure-core/CHANGELOG.md
  sdk/core/azure-core/CMakeLists.txt
  sdk/core/azure-core/inc/azure/core/http/http.hpp
  sdk/core/azure-core/inc/azure/core/http/policies/policy.hpp
  sdk/core/azure-core/inc/azure/core/internal/http/user_agent.hpp
  sdk/core/azure-core/inc/azure/core/internal/tracing/service_tracing.hpp
  sdk/core/azure-core/src/http/user_agent.cpp
  sdk/core/azure-core/test/ut/telemetry_policy_test.cpp
  sdk/eventhubs/azure-messaging-eventhubs/CHANGELOG.md
  sdk/eventhubs/azure-messaging-eventhubs/src/private/eventhubs_utilities.hpp
Labels: Azure.Core, Event Hubs

#6168 Increment version for core releases
  sdk/core/azure-core/CHANGELOG.md
  sdk/core/azure-core/src/private/package_version.hpp
Labels: Azure.Core

#6167 Increment version for eventhubs releases
  sdk/eventhubs/azure-messaging-eventhubs/CHANGELOG.md
  sdk/eventhubs/azure-messaging-eventhubs/src/private/package_version.hpp
Labels: Event Hubs

#6169 Minor code cleanups
  sdk/core/azure-core/src/base64.cpp
  sdk/core/azure-core/src/datetime.cpp
  sdk/core/azure-core/src/http/curl/curl.cpp
  sdk/core/azure-core/src/http/http.cpp
  sdk/core/azure-core/src/http/log_policy.cpp
Labels: MQ

#6166 Sync eng/common directory with azure-sdk-tools for PR 9300
  eng/common/testproxy/target_version.txt
Labels: EngSys, Central-EngSys

#6172 Sync eng/common directory with azure-sdk-tools for PR 9308
  eng/common/scripts/Package-Properties.ps1
Labels: EngSys, Central-EngSys

#6165 Sync eng/common directory with azure-sdk-tools for PR 9277
  eng/common/scripts/stress-testing/stress-test-deployment-lib.ps1
Labels: EngSys, Central-EngSys

#6171 Minor code cleanups 2
  sdk/attestation/azure-security-attestation/src/attestation_administration_client.cpp
  sdk/attestation/azure-security-attestation/src/attestation_client.cpp
  sdk/attestation/ci.yml
  sdk/core/azure-core/inc/azure/core/azure_assert.hpp
  sdk/core/azure-core/inc/azure/core/exception.hpp
  sdk/core/azure-core/inc/azure/core/http/http.hpp
  sdk/core/azure-core/inc/azure/core/internal/http/pipeline.hpp
  sdk/core/azure-core/inc/azure/core/internal/tracing/service_tracing.hpp
  sdk/core/azure-core/inc/azure/core/io/body_stream.hpp
  sdk/core/azure-core/inc/azure/core/nullable.hpp
  sdk/core/azure-core/inc/azure/core/url.hpp
  sdk/core/azure-core/src/base64.cpp
  sdk/core/azure-core/src/cryptography/md5.cpp
  sdk/core/azure-core/src/environment_log_level_listener.cpp
  sdk/core/azure-core/src/http/request_activity_policy.cpp
  sdk/core/azure-core/src/http/user_agent.cpp
  sdk/core/azure-core/src/logger.cpp
  sdk/core/azure-core/src/tracing/tracing.cpp
  sdk/core/azure-core/src/uuid.cpp
  sdk/identity/azure-identity/src/client_assertion_credential.cpp
Labels: MQ

#6177 Sync eng/common directory with azure-sdk-tools for PR 9330
  eng/common/scripts/Package-Properties.ps1
Labels: EngSys, Central-EngSys

#6131 Implement mTLS support in WinHTTP transport.
  .vscode/cspell.json
  sdk/core/azure-core/CHANGELOG.md
  sdk/core/azure-core/inc/azure/core/http/win_http_transport.hpp
  sdk/core/azure-core/src/http/winhttp/private/win_http_transport_impl.hpp
  sdk/core/azure-core/src/http/winhttp/win_http_request.hpp
  sdk/core/azure-core/src/http/winhttp/win_http_transport.cpp
  sdk/core/azure-core/test/ut/transport_adapter_base_test.cpp
Labels: Azure.Core

#6190 Fix overflow issue in token cache.
  sdk/identity/azure-identity/CHANGELOG.md
  sdk/identity/azure-identity/src/token_cache.cpp
  sdk/identity/azure-identity/test/ut/token_cache_test.cpp
Labels: Azure.Identity

#6191 Fix KeyVaultChallengeBasedAuthenticationPolicy test MultipleTimes since the bearer token policy now invalidates the token cache on receiving a 401.
  sdk/keyvault/azure-security-keyvault-secrets/test/ut/challenge_based_authentication_policy_test.cpp
Labels: test-enhancement, KeyVault

#6188 Sync eng/common directory with azure-sdk-tools for PR 9333
  eng/common/scripts/Helpers/Resource-Helpers.ps1
Labels: EngSys, Central-EngSys

#6193 Sync eng/common directory with azure-sdk-tools for PR 9331
  eng/common/pipelines/templates/steps/docker-pull-image.yml
  eng/common/pipelines/templates/steps/update-docsms-metadata.yml
  eng/common/scripts/Update-DocsMsMetadata.ps1
  eng/common/scripts/Update-DocsMsPackages.ps1
Labels: EngSys, Central-EngSys

#6195 Sync eng/common directory with azure-sdk-tools for PR 9354
  eng/common/pipelines/templates/steps/emit-rate-limit-metrics.yml
  eng/common/pipelines/templates/steps/git-push-changes.yml
Labels: EngSys, Central-EngSys

#6197 Increment version for identity releases
  sdk/identity/azure-identity/CHANGELOG.md
  sdk/identity/azure-identity/src/private/package_version.hpp
Labels: Azure.Identity

#6176 Add project skeleton and check-in snapshot of generated SDK for Azure App Configuration.
  .github/CODEOWNERS
  .vscode/cspell.json
  CMakeLists.txt
  eng/pipelines/templates/jobs/archetype-sdk-client.yml
  eng/pipelines/templates/jobs/ci.tests.yml
  sdk/appconfiguration/CMakeLists.txt
  sdk/appconfiguration/azure-data-appconfiguration/CHANGELOG.md
  sdk/appconfiguration/azure-data-appconfiguration/CMakeLists.txt
  sdk/appconfiguration/azure-data-appconfiguration/NOTICE.txt
  sdk/appconfiguration/azure-data-appconfiguration/README.md
  sdk/appconfiguration/azure-data-appconfiguration/cgmanifest.json
  sdk/appconfiguration/azure-data-appconfiguration/inc/ApiViewSettings.json
  sdk/appconfiguration/azure-data-appconfiguration/inc/azure/data/appconfiguration.hpp
  sdk/appconfiguration/azure-data-appconfiguration/inc/azure/data/appconfiguration/configuration_client.hpp
  sdk/appconfiguration/azure-data-appconfiguration/inc/azure/data/appconfiguration/configuration_client_models.hpp
  sdk/appconfiguration/azure-data-appconfiguration/inc/azure/data/appconfiguration/configuration_client_options.hpp
  sdk/appconfiguration/azure-data-appconfiguration/inc/azure/data/appconfiguration/dll_import_export.hpp
  sdk/appconfiguration/azure-data-appconfiguration/inc/azure/data/appconfiguration/rtti.hpp
  sdk/appconfiguration/azure-data-appconfiguration/src/configuration_client.cpp
  sdk/appconfiguration/azure-data-appconfiguration/src/private/package_version.hpp
  sdk/appconfiguration/azure-data-appconfiguration/test/ut/CMakeLists.txt
  sdk/appconfiguration/azure-data-appconfiguration/test/ut/configuration_test.cpp
  sdk/appconfiguration/azure-data-appconfiguration/test/ut/macro_guard.cpp
  sdk/appconfiguration/azure-data-appconfiguration/vcpkg.json
  sdk/appconfiguration/azure-data-appconfiguration/vcpkg/Config.cmake.in
  sdk/appconfiguration/azure-data-appconfiguration/vcpkg/portfile.cmake
  sdk/appconfiguration/azure-data-appconfiguration/vcpkg/vcpkg.json
  sdk/appconfiguration/ci.yml
Labels: App Configuration

#6185 Remove unused HttpHeaderClientRequestId const within timeout policy used by Azure.Data.Tables.
  sdk/tables/azure-data-tables/src/private/policies/timeout_policy.hpp
Labels: MQ, Tables

#6203 Update test regex in ci.yml for Azure.Data.Tables to be more strict and avoid bringing in appconfiguration
  sdk/tables/ci.yml
Labels: Tables

#6206 Sync eng/common directory with azure-sdk-tools for PR 9358
  eng/common/pipelines/templates/jobs/docindex.yml
Labels: EngSys, Central-EngSys

#6179 Minor code cleanups (3)
  sdk/attestation/azure-security-attestation/inc/azure/attestation/attestation_administration_client.hpp
  sdk/attestation/azure-security-attestation/inc/azure/attestation/attestation_client.hpp
  sdk/attestation/azure-security-attestation/src/private/crypto/inc/crypto.hpp
  sdk/core/azure-core/inc/azure/core/etag.hpp
  sdk/core/azure-core/inc/azure/core/exception.hpp
  sdk/core/azure-core/inc/azure/core/http/http.hpp
  sdk/core/azure-core/src/cryptography/md5.cpp
  sdk/core/azure-core/src/environment.cpp
  sdk/core/azure-core/src/exception.cpp
  sdk/core/azure-core/src/logger.cpp
  sdk/eventhubs/azure-messaging-eventhubs/inc/azure/messaging/eventhubs/event_data_batch.hpp
  sdk/eventhubs/azure-messaging-eventhubs/inc/azure/messaging/eventhubs/models/event_data.hpp
  sdk/eventhubs/azure-messaging-eventhubs/src/event_data_batch.cpp
  sdk/eventhubs/azure-messaging-eventhubs/src/private/eventhubs_utilities.hpp
  sdk/identity/azure-identity/inc/azure/identity/managed_identity_credential.hpp
  sdk/identity/azure-identity/src/azure_cli_credential.cpp
  sdk/identity/azure-identity/src/environment_credential.cpp
  sdk/identity/azure-identity/src/managed_identity_source.cpp
  sdk/identity/azure-identity/src/private/managed_identity_source.hpp
  sdk/keyvault/azure-security-keyvault-administration/src/keyvault_settings_common_request.cpp
  sdk/keyvault/azure-security-keyvault-certificates/src/keyvault_certificates_common_request.cpp
  sdk/keyvault/azure-security-keyvault-keys/inc/azure/keyvault/keys/cryptography/cryptography_client.hpp
  sdk/keyvault/azure-security-keyvault-keys/inc/azure/keyvault/keys/cryptography/cryptography_client_models.hpp
  sdk/keyvault/azure-security-keyvault-keys/inc/azure/keyvault/keys/key_client.hpp
  sdk/keyvault/azure-security-keyvault-keys/inc/azure/keyvault/keys/key_client_models.hpp
  sdk/keyvault/azure-security-keyvault-keys/inc/azure/keyvault/keys/key_client_options.hpp
  sdk/keyvault/azure-security-keyvault-keys/src/cryptography/cryptography_client.cpp
  sdk/keyvault/azure-security-keyvault-keys/src/cryptography/decrypt_parameters.cpp
  sdk/keyvault/azure-security-keyvault-keys/src/cryptography/encrypt_parameters.cpp
  sdk/keyvault/azure-security-keyvault-keys/src/delete_key_operation.cpp
  sdk/keyvault/azure-security-keyvault-keys/src/json_web_key.cpp
  sdk/keyvault/azure-security-keyvault-keys/src/key_client.cpp
  sdk/keyvault/azure-security-keyvault-keys/src/key_release_options.cpp
  sdk/keyvault/azure-security-keyvault-keys/src/key_request_parameters.cpp
  sdk/keyvault/azure-security-keyvault-keys/src/key_rotation_policy.cpp
  sdk/keyvault/azure-security-keyvault-keys/src/keyvault_key.cpp
  sdk/keyvault/azure-security-keyvault-keys/src/keyvault_protocol.cpp
  sdk/keyvault/azure-security-keyvault-keys/src/private/cryptography_internal_access.hpp
  sdk/keyvault/azure-security-keyvault-keys/src/private/key_request_parameters.hpp
  sdk/keyvault/azure-security-keyvault-secrets/inc/azure/keyvault/secrets/keyvault_secret_paged_response.hpp
  sdk/keyvault/azure-security-keyvault-secrets/src/keyvault_operations.cpp
  sdk/keyvault/azure-security-keyvault-secrets/src/keyvault_protocol.cpp
  sdk/keyvault/azure-security-keyvault-secrets/src/keyvault_secrets_common_request.cpp
  sdk/keyvault/azure-security-keyvault-secrets/src/private/keyvault_protocol.hpp
  sdk/keyvault/azure-security-keyvault-shared/inc/azure/keyvault/shared/keyvault_challenge_based_auth.hpp
  sdk/tables/azure-data-tables/inc/azure/data/tables/models.hpp
  sdk/tables/azure-data-tables/src/account_sas_builder.cpp
  sdk/tables/azure-data-tables/src/cryptography/hmacsha256.cpp
Labels: MQ

#6174 Sync eng/common directory with azure-sdk-tools for PR 9328
  eng/common/pipelines/templates/steps/save-package-properties.yml
  eng/common/scripts/Generate-PR-Diff.ps1
Labels: EngSys, Central-EngSys

#6215 Sync eng/common directory with azure-sdk-tools for PR 9373
  eng/common/pipelines/templates/archetype-typespec-emitter.yml
Labels: EngSys, Central-EngSys

#6210 Sync eng/common directory with azure-sdk-tools for PR 9364
  eng/common/scripts/stress-testing/stress-test-deployment-lib.ps1
Labels: EngSys, Central-EngSys

#6181 Tables cleanup work
  sdk/tables/assets.json
  sdk/tables/azure-data-tables/README.md
  sdk/tables/azure-data-tables/inc/azure/data/tables/account_sas_builder.hpp
  sdk/tables/azure-data-tables/inc/azure/data/tables/table_client.hpp
  sdk/tables/azure-data-tables/inc/azure/data/tables/table_service_client.hpp
  sdk/tables/azure-data-tables/samples/CMakeLists.txt
  sdk/tables/azure-data-tables/samples/tables_entity_operations.cpp
  sdk/tables/azure-data-tables/samples/tables_getting_started.cpp
  sdk/tables/azure-data-tables/samples/tables_service_operations.cpp
  sdk/tables/azure-data-tables/samples/tables_transactions_fail.cpp
  sdk/tables/azure-data-tables/samples/tables_transactions_ok.cpp
  sdk/tables/azure-data-tables/src/table_clients.cpp
  sdk/tables/azure-data-tables/test/ut/table_client_test.cpp
  sdk/tables/azure-data-tables/test/ut/table_client_test.hpp
  sdk/tables/ci.yml
Labels: Azure.Core, Tables

#6217 Azure Core November Beta Release
  sdk/core/azure-core/CHANGELOG.md
Labels: Azure.Core

#6218 Increment version for core releases
  sdk/core/azure-core/CHANGELOG.md
  sdk/core/azure-core/src/private/package_version.hpp
Labels: Azure.Core

#6219 Increment version for storage releases
  sdk/storage/azure-storage-common/CHANGELOG.md
  sdk/storage/azure-storage-common/src/private/package_version.hpp
  sdk/storage/azure-storage-files-shares/CHANGELOG.md
  sdk/storage/azure-storage-files-shares/src/private/package_version.hpp
Labels: Storage

#6221 Update link to Azure API guidelines within Operation.md
  doc/Operation.md
Labels: Docs

#6209 Remove unused includes
  sdk/attestation/azure-security-attestation/src/attestation_administration_client.cpp
  sdk/attestation/azure-security-attestation/src/attestation_client.cpp
  sdk/attestation/azure-security-attestation/src/private/attestation_client_private.cpp
  sdk/attestation/azure-security-attestation/src/private/attestation_deserializers_private.cpp
  sdk/attestation/azure-security-attestation/src/private/jsonhelpers.cpp
  sdk/core/azure-core/src/http/transport_policy.cpp
  sdk/core/azure-core/src/resource_identifier.cpp
  sdk/eventhubs/azure-messaging-eventhubs/src/consumer_client.cpp
  sdk/eventhubs/azure-messaging-eventhubs/src/event_data.cpp
  sdk/keyvault/azure-security-keyvault-certificates/CMakeLists.txt
  sdk/keyvault/azure-security-keyvault-certificates/src/certificate_client.cpp
  sdk/keyvault/azure-security-keyvault-certificates/src/certificate_client_models.cpp
  sdk/keyvault/azure-security-keyvault-certificates/src/certificate_serializers.cpp
  sdk/keyvault/azure-security-keyvault-certificates/src/keyvault_certificates_common_request.cpp
  sdk/keyvault/azure-security-keyvault-certificates/src/private/certificate_key_usage.hpp
  sdk/keyvault/azure-security-keyvault-keys/src/cryptography/decrypt_parameters.cpp
  sdk/keyvault/azure-security-keyvault-keys/src/cryptography/decrypt_result.cpp
  sdk/keyvault/azure-security-keyvault-keys/src/cryptography/encrypt_parameters.cpp
  sdk/keyvault/azure-security-keyvault-keys/src/cryptography/key_sign_parameters.cpp
  sdk/keyvault/azure-security-keyvault-keys/src/cryptography/key_wrap_parameters.cpp
  sdk/keyvault/azure-security-keyvault-keys/src/cryptography/sign_result.cpp
  sdk/keyvault/azure-security-keyvault-keys/src/cryptography/wrap_result.cpp
  sdk/keyvault/azure-security-keyvault-keys/src/key_backup.cpp
  sdk/keyvault/azure-security-keyvault-keys/src/key_client_paged_responses.cpp
  sdk/keyvault/azure-security-keyvault-keys/src/key_get_random_bytes.cpp
  sdk/keyvault/azure-security-keyvault-keys/src/key_release_policy.cpp
  sdk/keyvault/azure-security-keyvault-keys/src/key_type.cpp
  sdk/keyvault/azure-security-keyvault-keys/src/keyvault_key.cpp
  sdk/keyvault/azure-security-keyvault-keys/src/recover_deleted_key_operation.cpp
Labels: MQ

#6228 Sync eng/common directory with azure-sdk-tools for PR 9389
  eng/common/scripts/logging.ps1
Labels: EngSys, Central-EngSys

#6234 Fix typos
  sdk/attestation/azure-security-attestation/src/attestation_administration_client.cpp
  sdk/attestation/azure-security-attestation/src/attestation_client.cpp
  sdk/core/azure-core/inc/azure/core/dll_import_export.hpp
  sdk/core/azure-core/src/http/curl/curl.cpp
  sdk/core/azure-core/src/http/curl/curl_connection_private.hpp
  sdk/eventhubs/azure-messaging-eventhubs/inc/azure/messaging/eventhubs/event_data_batch.hpp
  sdk/eventhubs/azure-messaging-eventhubs/src/processor_load_balancer.cpp
  sdk/eventhubs/azure-messaging-eventhubs/test/ut/eventhubs_admin_client.cpp
  sdk/eventhubs/azure-messaging-eventhubs/test/ut/processor_load_balancer_test.cpp
  sdk/identity/azure-identity/src/azure_cli_credential.cpp
  sdk/identity/azure-identity/src/client_credential_core.cpp
  sdk/identity/azure-identity/src/default_azure_credential.cpp
  sdk/identity/azure-identity/test/ut/default_azure_credential_test.cpp
  sdk/keyvault/azure-security-keyvault-administration/inc/azure/keyvault/administration/backup_operation.hpp
  sdk/keyvault/azure-security-keyvault-administration/src/backup_client.cpp
  sdk/keyvault/azure-security-keyvault-administration/src/settings_client.cpp
  sdk/keyvault/azure-security-keyvault-certificates/src/certificate_client.cpp
  sdk/keyvault/azure-security-keyvault-certificates/src/private/certificate_serializers.hpp
  sdk/keyvault/azure-security-keyvault-keys/inc/azure/keyvault/keys/key_client_models.hpp
  sdk/keyvault/azure-security-keyvault-keys/src/cryptography/cryptography_client.cpp
  sdk/keyvault/azure-security-keyvault-keys/src/cryptography/signature_algorithm.cpp
  sdk/keyvault/azure-security-keyvault-keys/src/delete_key_operation.cpp
  sdk/keyvault/azure-security-keyvault-keys/src/key_client.cpp
  sdk/keyvault/azure-security-keyvault-keys/src/recover_deleted_key_operation.cpp
  sdk/keyvault/azure-security-keyvault-keys/test/ut/mocked_transport_adapter_test.hpp
  sdk/keyvault/azure-security-keyvault-secrets/inc/azure/keyvault/secrets/keyvault_operations.hpp
  sdk/keyvault/azure-security-keyvault-secrets/src/secret_client.cpp
  sdk/tables/azure-data-tables/src/private/tables_constants.hpp
  sdk/tables/azure-data-tables/src/table_clients.cpp
Labels: MQ

#6238 Sync eng/common directory with azure-sdk-tools for PR 9393
  eng/common/scripts/job-matrix/Create-PrJobMatrix.ps1
  eng/common/scripts/job-matrix/job-matrix-functions.ps1
Labels: EngSys, Central-EngSys

#6239 Sync eng/common directory with azure-sdk-tools for PR 9381
  eng/common/scripts/Verify-ChangeLogs.ps1
Labels: EngSys, Central-EngSys

#6243 Make Uuid's default constructor implicit
  sdk/core/azure-core/inc/azure/core/uuid.hpp
Labels: Azure.Core

#6199 Update CODEOWNERS for /** to catch all for non-code project files and unowned files
  .github/CODEOWNERS
Labels: EngSys, MQ

#6242 Sync eng/common directory with azure-sdk-tools for PR 9390
  eng/common/scripts/Helpers/ApiView-Helpers.ps1
Labels: EngSys, Central-EngSys

#6232 Tables beta
  sdk/tables/azure-data-tables/CHANGELOG.md
  sdk/tables/azure-data-tables/test/ut/CMakeLists.txt
Labels: Tables

#6245 Storage STG97/NFS REST
  sdk/storage/azure-storage-files-shares/inc/azure/storage/files/shares/rest_client.hpp
  sdk/storage/azure-storage-files-shares/inc/azure/storage/files/shares/share_file_client.hpp
  sdk/storage/azure-storage-files-shares/inc/azure/storage/files/shares/share_options.hpp
  sdk/storage/azure-storage-files-shares/inc/azure/storage/files/shares/share_responses.hpp
  sdk/storage/azure-storage-files-shares/src/rest_client.cpp
  sdk/storage/azure-storage-files-shares/src/share_directory_client.cpp
  sdk/storage/azure-storage-files-shares/src/share_file_client.cpp
  sdk/storage/azure-storage-files-shares/src/share_options.cpp
  sdk/storage/azure-storage-files-shares/src/share_responses.cpp
  sdk/storage/azure-storage-files-shares/swagger/README.md
Labels: Storage

#6249 Remove trailing comma in the JSON array within vcpkg.json
  sdk/appconfiguration/azure-data-appconfiguration/vcpkg/vcpkg.json
Labels: EngSys, App Configuration

#6247 Sync eng/common directory with azure-sdk-tools for PR 9392
  eng/common/scripts/Helpers/PSModule-Helpers.ps1
Labels: EngSys, Central-EngSys

#6255 Tables release PR
  sdk/tables/azure-data-tables/CHANGELOG.md
Labels: Tables

#6257 Increment version for tables releases
  sdk/tables/azure-data-tables/CHANGELOG.md
  sdk/tables/azure-data-tables/src/private/package_version.hpp
Labels: Tables

#6254 Implement receiving messages; Changes to eventhubs so that all eventhubs tests pass
  CMakePresets.json
  sdk/core/azure-core-amqp/src/impl/rust_amqp/amqp/message_receiver.cpp
  sdk/core/azure-core-amqp/src/impl/rust_amqp/amqp/private/message_receiver_impl.hpp
  sdk/core/azure-core-amqp/src/impl/rust_amqp/rust_amqp/azure_core_amqp/src/fe2o3/receiver.rs
  sdk/core/azure-core-amqp/src/impl/rust_amqp/rust_amqp/azure_core_amqp/src/noop.rs
  sdk/core/azure-core-amqp/src/impl/rust_amqp/rust_amqp/azure_core_amqp/src/receiver.rs
  sdk/core/azure-core-amqp/src/impl/rust_amqp/rust_amqp/rust_wrapper/src/amqp/connection.rs
  sdk/core/azure-core-amqp/src/impl/rust_amqp/rust_amqp/rust_wrapper/src/amqp/management.rs
  sdk/core/azure-core-amqp/src/impl/rust_amqp/rust_amqp/rust_wrapper/src/amqp/message_receiver.rs
  sdk/core/azure-core-amqp/src/impl/rust_amqp/rust_amqp/rust_wrapper/src/amqp/message_sender.rs
  sdk/core/azure-core-amqp/src/impl/rust_amqp/rust_amqp/rust_wrapper/src/amqp/mod.rs
  sdk/core/azure-core-amqp/src/impl/rust_amqp/rust_amqp/rust_wrapper/src/model/message.rs
  sdk/core/azure-core-amqp/src/impl/rust_amqp/rust_amqp/rust_wrapper/src/model/properties.rs
  sdk/core/azure-core-amqp/test/ut/management_tests.cpp
  sdk/core/azure-core-amqp/test/ut/message_sender_receiver.cpp
  sdk/eventhubs/azure-messaging-eventhubs/inc/azure/messaging/eventhubs/consumer_client.hpp
  sdk/eventhubs/azure-messaging-eventhubs/src/consumer_client.cpp
  sdk/eventhubs/azure-messaging-eventhubs/src/partition_client.cpp
  sdk/eventhubs/azure-messaging-eventhubs/src/producer_client.cpp
  sdk/eventhubs/azure-messaging-eventhubs/test/ut/consumer_client_test.cpp
Labels: Azure.Core, Event Hubs

#6251 Add basic operation (GetKeyValue) sample for AppConfig.
  sdk/appconfiguration/azure-data-appconfiguration/CMakeLists.txt
  sdk/appconfiguration/azure-data-appconfiguration/samples/CMakeLists.txt
  sdk/appconfiguration/azure-data-appconfiguration/samples/appconfig_basic_operation.cpp
Labels: App Configuration

#6262 Sync eng/common directory with azure-sdk-tools for PR 9428
  eng/common/scripts/Cadl-Project-Generate.ps1
  eng/common/scripts/Cadl-Project-Sync.ps1
Labels: EngSys, Central-EngSys

#6268 Remove unused SharedKeyLitePolicy and connection string helpers in Tables.
  sdk/tables/azure-data-tables/CMakeLists.txt
  sdk/tables/azure-data-tables/inc/azure/data/tables/credentials/named_key_credential.hpp
  sdk/tables/azure-data-tables/src/credentials/named_key_credential.cpp
  sdk/tables/azure-data-tables/src/policies/shared_key_lite_policy.cpp
  sdk/tables/azure-data-tables/src/private/policies/shared_key_lite_policy.hpp
  sdk/tables/azure-data-tables/src/table_clients.cpp
  sdk/tables/azure-data-tables/test/ut/CMakeLists.txt
  sdk/tables/azure-data-tables/test/ut/shared_key_lite_policy_test.cpp
Labels: Tables
