Repository Azure/azure-sdk-for-cpp, pull requests merged in 2025-01, with the labels that each got.

#6316 Sync eng/common directory with azure-sdk-tools for PR 9580
  eng/common/pipelines/templates/jobs/prepare-pipelines.yml
Labels: EngSys, Central-EngSys

#6317 Sync eng/common directory with azure-sdk-tools for PR 9584
  eng/common/testproxy/target_version.txt
Labels: EngSys, Central-EngSys

#6311 Remove SAS and deps from tables
  sdk/tables/azure-data-tables/CMakeLists.txt
  sdk/tables/azure-data-tables/inc/azure/data/tables.hpp
  sdk/tables/azure-data-tables/inc/azure/data/tables/account_sas_builder.hpp
  sdk/tables/azure-data-tables/inc/azure/data/tables/credentials/azure_sas_credential.hpp
  sdk/tables/azure-data-tables/inc/azure/data/tables/credentials/named_key_credential.hpp
  sdk/tables/azure-data-tables/inc/azure/data/tables/enum_operators.hpp
  sdk/tables/azure-data-tables/inc/azure/data/tables/models.hpp
  sdk/tables/azure-data-tables/inc/azure/data/tables/table_client.hpp
  sdk/tables/azure-data-tables/inc/azure/data/tables/table_service_client.hpp
  sdk/tables/azure-data-tables/inc/azure/data/tables/tables_sas_builder.hpp
  sdk/tables/azure-data-tables/src/account_sas_builder.cpp
  sdk/tables/azure-data-tables/src/cryptography/hmacsha256.cpp
  sdk/tables/azure-data-tables/src/private/hmacsha256.hpp
  sdk/tables/azure-data-tables/src/table_clients.cpp
  sdk/tables/azure-data-tables/src/tables_sas_builder.cpp
  sdk/tables/azure-data-tables/test/ut/CMakeLists.txt
  sdk/tables/azure-data-tables/test/ut/enum_operators_test.cpp
  sdk/tables/azure-data-tables/test/ut/enum_operators_test.hpp
  sdk/tables/azure-data-tables/test/ut/sas_test.cpp
  sdk/tables/azure-data-tables/test/ut/sas_test.hpp
  sdk/tables/azure-data-tables/test/ut/table_client_test.cpp
  sdk/tables/azure-data-tables/test/ut/table_client_test.hpp
Labels: Tables

#6320 Update location of big test file
  sdk/core/azure-core/test/ut/transport_adapter_base_test.cpp
Labels: Azure.Core

#6318 Azure Core January Beta Release
  sdk/core/azure-core/CHANGELOG.md
Labels: Azure.Core

#6328 Mark all AppConfig SDK client methods as const, since clients are immutable.
  sdk/appconfiguration/azure-data-appconfiguration/inc/azure/data/appconfiguration/configuration_client.hpp
  sdk/appconfiguration/azure-data-appconfiguration/src/configuration_client.cpp
Labels: App Configuration

#6332 Increment version for core releases
  sdk/core/azure-core/CHANGELOG.md
  sdk/core/azure-core/src/private/package_version.hpp
Labels: Azure.Core

#6338 Add samples for AppConfig Pageable GetLabels with comparisons of what we'd expect the user experience to be.
  sdk/appconfiguration/azure-data-appconfiguration/samples/appconfig_basic_operation.cpp
Labels: App Configuration

#6346 Sync eng/common directory with azure-sdk-tools for PR 9614
  eng/common/scripts/Package-Properties.ps1
Labels: EngSys, Central-EngSys

#6350 Sync eng/common directory with azure-sdk-tools for PR 9635
  eng/common/scripts/Package-Properties.ps1
Labels: EngSys, Central-EngSys

#6349 Integrate Rust 2 step message receive code to C++
  sdk/core/azure-core-amqp/src/impl/rust_amqp/rust_amqp/azure_core_amqp/Cargo.toml
  sdk/core/azure-core-amqp/src/impl/rust_amqp/rust_amqp/azure_core_amqp/README.md
  sdk/core/azure-core-amqp/src/impl/rust_amqp/rust_amqp/azure_core_amqp/Test-Cleanup.ps1
  sdk/core/azure-core-amqp/src/impl/rust_amqp/rust_amqp/azure_core_amqp/Test-Setup.ps1
  sdk/core/azure-core-amqp/src/impl/rust_amqp/rust_amqp/azure_core_amqp/examples/connection.rs
  sdk/core/azure-core-amqp/src/impl/rust_amqp/rust_amqp/azure_core_amqp/src/connection.rs
  sdk/core/azure-core-amqp/src/impl/rust_amqp/rust_amqp/azure_core_amqp/src/fe2o3/connection.rs
  sdk/core/azure-core-amqp/src/impl/rust_amqp/rust_amqp/azure_core_amqp/src/fe2o3/messaging/messaging_types.rs
  sdk/core/azure-core-amqp/src/impl/rust_amqp/rust_amqp/azure_core_amqp/src/fe2o3/receiver.rs
  sdk/core/azure-core-amqp/src/impl/rust_amqp/rust_amqp/azure_core_amqp/src/lib.rs
  sdk/core/azure-core-amqp/src/impl/rust_amqp/rust_amqp/azure_core_amqp/src/messaging.rs
  sdk/core/azure-core-amqp/src/impl/rust_amqp/rust_amqp/azure_core_amqp/src/noop.rs
  sdk/core/azure-core-amqp/src/impl/rust_amqp/rust_amqp/azure_core_amqp/src/receiver.rs
  sdk/core/azure-core-amqp/src/impl/rust_amqp/rust_amqp/rust_wrapper/src/amqp/message_receiver.rs
Labels: Azure.Core

#6305 Sync eng/common directory with azure-sdk-tools for PR 9529
  eng/common/TestResources/New-TestResources.ps1
Labels: EngSys, Central-EngSys

#6341 Add samples for all AppConfig pager methods (GetSnapshots, GetConfigurationSettings, GetRevisions) with comparisons of what we'd expect the user experience to be.
  sdk/appconfiguration/azure-data-appconfiguration/samples/appconfig_basic_operation.cpp
Labels: App Configuration

#6342 Add samples for Lock and Unlock Configuration Settings with comparisons of what we'd expect the user experience to be.
  sdk/appconfiguration/azure-data-appconfiguration/samples/appconfig_basic_operation.cpp
Labels: App Configuration

#6344 Add samples for Get, Archive, and Recover Snapshots with comparisons of what we'd expect the user experience to be.
  sdk/appconfiguration/azure-data-appconfiguration/samples/appconfig_basic_operation.cpp
Labels: App Configuration

#6345 Add samples for AppConfig LRO CreateSnapshot with comparisons of what we'd expect the user experience to be.
  sdk/appconfiguration/azure-data-appconfiguration/samples/appconfig_basic_operation.cpp
Labels: App Configuration

#6355 Remove sovereign cloud testing references
  eng/pipelines/templates/stages/archetype-sdk-client.yml
Labels: Central-EngSys

#6356 Sync eng/common directory with azure-sdk-tools for PR 9577
  eng/common/pipelines/templates/jobs/archetype-spec-gen-sdk.yml
Labels: EngSys, Central-EngSys

#6352 Remove unused responseString local variables within the table_client.cpp implementations
  sdk/tables/azure-data-tables/src/table_clients.cpp
Labels: Tables

#6358 Sync eng/common directory with azure-sdk-tools for PR 9650
  eng/common/pipelines/templates/jobs/prepare-pipelines.yml
Labels: EngSys, Central-EngSys

#6351 Sync eng/common directory with azure-sdk-tools for PR 9601
  eng/common/pipelines/templates/jobs/generate-job-matrix.yml
  eng/common/pipelines/templates/steps/verify-readmes.yml
  eng/common/scripts/job-matrix/Create-PrJobMatrix.ps1
Labels: EngSys, Central-EngSys

#6347 Sync eng/common directory with azure-sdk-tools for PR 9620
  eng/common/scripts/Test-SampleMetadata.ps1
Labels: EngSys, Central-EngSys

#6223 Update LiveTestCtestRegex within the ci.yml to match the CtestRegex value set
  sdk/tables/ci.yml
Labels: EngSys, Tables

#6361 Sync eng/common directory with azure-sdk-tools for PR 9652
  eng/common/docgeneration/Generate-DocIndex.ps1
  eng/common/docgeneration/templates/matthews/styles/main.js
  eng/common/pipelines/templates/jobs/docindex.yml
  eng/common/scripts/copy-docs-to-blobstorage.ps1
Labels: EngSys, Central-EngSys

#6359 Sync eng/common directory with azure-sdk-tools for PR 9658
  eng/common/scripts/Generate-PR-Diff.ps1
  eng/common/scripts/Package-Properties.ps1
Labels: EngSys, Central-EngSys

#6339 update update approach v2
  sdk/tables/assets.json
  sdk/tables/azure-data-tables/inc/azure/data/tables/models.hpp
  sdk/tables/azure-data-tables/inc/azure/data/tables/table_client.hpp
  sdk/tables/azure-data-tables/inc/azure/data/tables/table_service_client.hpp
  sdk/tables/azure-data-tables/src/table_clients.cpp
  sdk/tables/azure-data-tables/test/ut/table_client_test.cpp
Labels: Tables

#6364 Sync eng/common directory with azure-sdk-tools for PR 9668
  eng/common/scripts/SemVer.ps1
Labels: EngSys, Central-EngSys

#6327 Tables january release
  sdk/tables/azure-data-tables/CHANGELOG.md
Labels: Tables

#6366 Sync eng/common directory with azure-sdk-tools for PR 9656
  eng/common/pipelines/templates/jobs/archetype-spec-gen-sdk.yml
  eng/common/scripts/Invoke-GitHubAPI.ps1
  eng/common/scripts/Remove-IssueLabel.ps1
Labels: EngSys, Central-EngSys

#6365 Increment version for tables releases
  sdk/tables/azure-data-tables/CHANGELOG.md
  sdk/tables/azure-data-tables/src/private/package_version.hpp
Labels: Tables

#6369 Sync eng/common directory with azure-sdk-tools for PR 9670
  eng/common/pipelines/templates/jobs/archetype-spec-gen-sdk.yml
Labels: EngSys, Central-EngSys

#6363 Remove unused AttestationServiceUrl() from KeyVault Keys tests
  sdk/keyvault/azure-security-keyvault-keys/test/ut/CMakeLists.txt
  sdk/keyvault/azure-security-keyvault-keys/test/ut/key_client_create_test_live.cpp
  sdk/keyvault/azure-security-keyvault-keys/test/ut/test_consts.hpp
Labels: test-enhancement, KeyVault

#6371 Sync eng/common directory with azure-sdk-tools for PR 9681
  eng/common/pipelines/templates/steps/sparse-checkout.yml
Labels: EngSys, Central-EngSys

#6368 Sync eng/common directory with azure-sdk-tools for PR 9687
  eng/common/scripts/stress-testing/deploy-stress-tests.ps1
  eng/common/scripts/stress-testing/stress-test-deployment-lib.ps1
Labels: EngSys, Central-EngSys

#6372 Sync eng/common directory with azure-sdk-tools for PR 9699
  eng/common/pipelines/templates/jobs/generate-job-matrix.yml
  eng/common/scripts/job-matrix/Create-PrJobMatrix.ps1
Labels: EngSys, Central-EngSys

#6375 Sync eng/common directory with azure-sdk-tools for PR 9700
  eng/common/TestResources/New-TestResources.ps1
Labels: EngSys, Central-EngSys

#6382 Fix CodeQL issue
  sdk/core/azure-core/inc/azure/core/internal/json/json.hpp
Labels: Azure.Core

#6384 Sync eng/common directory with azure-sdk-tools for PR 9724
  eng/common/pipelines/templates/jobs/archetype-spec-gen-sdk.yml
  eng/common/pipelines/templates/stages/archetype-spec-gen-sdk.yml
Labels: EngSys, Central-EngSys

#6383 Sync eng/common directory with azure-sdk-tools for PR 9732
  eng/common/pipelines/templates/archetype-typespec-emitter.yml
Labels: EngSys, Central-EngSys
