Repository Azure/azure-sdk-for-cpp, pull requests merged in 2025-05, with the labels that each got.

#6554 Temporarily disable CheckFailedCrlValidation test to unblock CI
  sdk/core/azure-core/test/ut/transport_policy_options.cpp
  sdk/core/ci.yml
Labels: Azure.Core

#6552 Identity: update Troubleshooting.md with all the credentials
  sdk/identity/azure-identity/TROUBLESHOOTING.md
Labels: Azure.Identity

#6556 Sync eng/common directory with azure-sdk-tools for PR 10523
  eng/common/pipelines/templates/archetype-typespec-emitter.yml
Labels: EngSys, Central-EngSys

#6559 Sync eng/common directory with azure-sdk-tools for PR 10542
  eng/common/scripts/Test-SampleMetadata.ps1
Labels: EngSys, Central-EngSys

#6560 Sync eng/common directory with azure-sdk-tools for PR 10534
  eng/common/scripts/Helpers/ApiView-Helpers.ps1
Labels: EngSys, Central-EngSys

#6558 Update release notes for version 4.3.0-beta.4
  sdk/keyvault/azure-security-keyvault-certificates/CHANGELOG.md
Labels: KeyVault

#6562 Increment version for keyvault releases
  sdk/keyvault/azure-security-keyvault-certificates/CHANGELOG.md
  sdk/keyvault/azure-security-keyvault-certificates/src/private/package_version.hpp
Labels: KeyVault

#6501 Storage STG98 Features
  sdk/storage/assets.json
  sdk/storage/azure-storage-blobs/inc/azure/storage/blobs/blob_options.hpp
  sdk/storage/azure-storage-blobs/inc/azure/storage/blobs/rest_client.hpp
  sdk/storage/azure-storage-blobs/src/append_blob_client.cpp
  sdk/storage/azure-storage-blobs/src/blob_client.cpp
  sdk/storage/azure-storage-blobs/src/blob_sas_builder.cpp
  sdk/storage/azure-storage-blobs/src/block_blob_client.cpp
  sdk/storage/azure-storage-blobs/src/page_blob_client.cpp
  sdk/storage/azure-storage-blobs/src/rest_client.cpp
  sdk/storage/azure-storage-blobs/swagger/README.md
  sdk/storage/azure-storage-blobs/test/ut/CMakeLists.txt
  sdk/storage/azure-storage-blobs/test/ut/append_blob_client_test.cpp
  sdk/storage/azure-storage-blobs/test/ut/blob_container_client_test.cpp
  sdk/storage/azure-storage-blobs/test/ut/block_blob_client_test.cpp
  sdk/storage/azure-storage-blobs/test/ut/page_blob_client_test.cpp
  sdk/storage/azure-storage-files-datalake/test/ut/datalake_file_system_client_test.cpp
  sdk/storage/azure-storage-files-shares/inc/azure/storage/files/shares/share_file_client.hpp
  sdk/storage/azure-storage-files-shares/inc/azure/storage/files/shares/share_options.hpp
  sdk/storage/azure-storage-files-shares/inc/azure/storage/files/shares/share_responses.hpp
  sdk/storage/azure-storage-files-shares/src/share_file_client.cpp
  sdk/storage/azure-storage-files-shares/test/ut/share_file_client_test.cpp
  sdk/storage/azure-storage-queues/test/ut/queue_client_test.cpp
Labels: Storage

#6564 Sync eng/common directory with azure-sdk-tools for PR 10579
  eng/common/TestResources/New-TestResources.ps1
  eng/common/TestResources/New-TestResources.ps1.md
  eng/common/TestResources/README.md
  eng/common/TestResources/Remove-TestResources.ps1
  eng/common/TestResources/TestResources-Helpers.ps1
  eng/common/scripts/common.ps1
Labels: EngSys, Central-EngSys

#6565 Sync eng/common directory with azure-sdk-tools for PR 10593
  eng/common/pipelines/templates/steps/verify-links.yml
  eng/common/scripts/Verify-Links.ps1
Labels: EngSys, Central-EngSys

#6537 Add SSL caching share for curl
  .vscode/cspell.json
  sdk/core/azure-core/CHANGELOG.md
  sdk/core/azure-core/inc/azure/core/http/curl_transport.hpp
  sdk/core/azure-core/src/http/curl/curl.cpp
  sdk/core/azure-core/src/http/curl/curl_connection_private.hpp
  sdk/core/azure-core/test/ut/curl_options_test.cpp
  sdk/core/ci.yml
Labels: Azure.Core, customer-reported, Community Contribution

#6566 Sync eng/common directory with azure-sdk-tools for PR 10611
  eng/common/pipelines/templates/steps/verify-links.yml
  eng/common/scripts/Verify-Links.ps1
Labels: EngSys, Central-EngSys

#6568 Sync eng/common directory with azure-sdk-tools for PR 10615
  eng/common/scripts/Helpers/ApiView-Helpers.ps1
Labels: EngSys, Central-EngSys

#6567 Increment version for storage releases
  sdk/storage/azure-storage-blobs/CHANGELOG.md
  sdk/storage/azure-storage-blobs/src/private/package_version.hpp
  sdk/storage/azure-storage-files-shares/CHANGELOG.md
  sdk/storage/azure-storage-files-shares/src/private/package_version.hpp
Labels: Storage

#6570 Sync eng/common directory with azure-sdk-tools for PR 10616
  eng/common/scripts/Verify-Links.ps1
Labels: EngSys, Central-EngSys

#6555 Sync eng/common directory with azure-sdk-tools for PR 10522
  eng/common/pipelines/templates/steps/check-spelling.yml
Labels: EngSys, Central-EngSys

#6571 Sync eng/common directory with azure-sdk-tools for PR 10532
  eng/common/TestResources/New-TestResources.ps1
  eng/common/TestResources/Remove-TestResources.ps1
  eng/common/TestResources/SubConfig-Helpers.ps1
  eng/common/TestResources/deploy-test-resources.yml
Labels: EngSys, Central-EngSys

#6572 Sync eng/common directory with azure-sdk-tools for PR 10550
  eng/common/TestResources/TestResources-Helpers.ps1
Labels: EngSys, Central-EngSys

#6576 Sync eng/common directory with azure-sdk-tools for PR 10664
  eng/common/pipelines/templates/steps/sparse-checkout.yml
Labels: EngSys, Central-EngSys

#6578 Sync eng/common directory with azure-sdk-tools for PR 10665
  eng/common/mcp/azure-sdk-mcp.ps1
Labels: EngSys, Central-EngSys

#6580 Sync eng/common directory with azure-sdk-tools for PR 10657
  eng/common/pipelines/templates/steps/save-package-properties.yml
Labels: EngSys, Central-EngSys

#6582 Fix Windows error for failing curl SSL cache
  .vscode/cspell.json
  sdk/core/azure-core/CHANGELOG.md
  sdk/core/azure-core/src/http/curl/curl.cpp
  sdk/core/azure-core/src/http/winhttp/win_http_transport.cpp
Labels: Azure.Core, customer-reported, Community Contribution

#6574 Update vcpkg baseline
  cmake-modules/AzureVcpkg.cmake
  eng/pipelines/templates/steps/vcpkg.yml
  sdk/core/azure-core-tracing-opentelemetry/test/ut/test_exporter.hpp
  sdk/eventhubs/azure-messaging-eventhubs/test/eventhubs-stress-test/src/eventhubs_stress_test.cpp
  sdk/eventhubs/azure-messaging-eventhubs/test/eventhubs-stress-test/src/scenarios/inc/batch_stress_tests.hpp
  sdk/eventhubs/azure-messaging-eventhubs/test/eventhubs-stress-test/src/scenarios/inc/shared_functions.hpp
  vcpkg.json
Labels: Azure.Core

#6584 Storage/STG99 Changed QueueProperties.ApproximateMessagesCount from int to long
  sdk/storage/assets.json
  sdk/storage/azure-storage-queues/CHANGELOG.md
  sdk/storage/azure-storage-queues/inc/azure/storage/queues/queue_client.hpp
  sdk/storage/azure-storage-queues/inc/azure/storage/queues/queue_responses.hpp
  sdk/storage/azure-storage-queues/inc/azure/storage/queues/rest_client.hpp
  sdk/storage/azure-storage-queues/src/queue_client.cpp
  sdk/storage/azure-storage-queues/src/rest_client.cpp
  sdk/storage/azure-storage-queues/swagger/README.md
  sdk/storage/azure-storage-queues/test/ut/queue_client_test.cpp
Labels: Storage

#6588 Sync eng/common directory with azure-sdk-tools for PR 10286
  eng/common/pipelines/templates/steps/detect-api-changes.yml
  eng/common/scripts/Detect-Api-Changes.ps1
  eng/common/scripts/Helpers/ApiView-Helpers.ps1
Labels: EngSys, Central-EngSys

#6589 Sync eng/common directory with azure-sdk-tools for PR 10718
  eng/common/scripts/Detect-Api-Changes.ps1
  eng/common/scripts/Helpers/ApiView-Helpers.ps1
Labels: EngSys, Central-EngSys

#6591 Direct traffic to credential chains doc
  sdk/identity/azure-identity/README.md
  sdk/identity/azure-identity/img/mermaidjs/DefaultAzureCredentialAuthFlow.md
  sdk/identity/azure-identity/img/mermaidjs/DefaultAzureCredentialAuthFlow.svg
Labels: Azure.Identity

#6595 Sync eng/common directory with azure-sdk-tools for PR 10736
  eng/common/pipelines/templates/jobs/prepare-pipelines.yml
Labels: EngSys, Central-EngSys

#6596 Sync eng/common directory with azure-sdk-tools for PR 10735
  eng/common/pipelines/templates/jobs/npm-publish.yml
Labels: EngSys, Central-EngSys

#6600 Sync .github/workflows directory with azure-sdk-tools for PR 10752
  .github/workflows/event-processor.yml
Labels: EngSys, Central-EngSys

#6601 Sync eng/common directory with azure-sdk-tools for PR 10731
  eng/common/pipelines/templates/steps/detect-api-changes.yml
  eng/common/scripts/Helpers/ApiView-Helpers.ps1
Labels: EngSys, Central-EngSys

#6603 Sync eng/common directory with azure-sdk-tools for PR 10765
  eng/common/pipelines/templates/archetype-typespec-emitter.yml
Labels: EngSys, Central-EngSys

#6573 Identity: IMDS fail-fast and Cred order change in DAC (and Core support)
  .vscode/cspell.json
  eng/pipelines/templates/jobs/live.tests.yml
  samples/helpers/service/src/client.cpp
  sdk/core/azure-core/CHANGELOG.md
  sdk/core/azure-core/inc/azure/core/http/transport.hpp
  sdk/core/azure-core/src/http/curl/curl.cpp
  sdk/core/azure-core/src/http/curl/curl_connection_pool_private.hpp
  sdk/core/azure-core/src/http/curl/curl_connection_private.hpp
  sdk/core/azure-core/src/http/http.cpp
  sdk/core/azure-core/src/http/winhttp/private/win_http_transport_impl.hpp
  sdk/core/azure-core/src/http/winhttp/win_http_request.hpp
  sdk/core/azure-core/src/http/winhttp/win_http_transport.cpp
  sdk/identity/azure-identity/CHANGELOG.md
  sdk/identity/azure-identity/src/default_azure_credential.cpp
  sdk/identity/azure-identity/src/managed_identity_source.cpp
  sdk/identity/azure-identity/src/private/managed_identity_source.hpp
  sdk/identity/azure-identity/test/ut/default_azure_credential_test.cpp
  sdk/identity/azure-identity/test/ut/managed_identity_credential_test.cpp
  sdk/tables/test-resources.json
Labels: Azure.Core, Azure.Identity, Managed Identity
