Repository Azure/azure-sdk-for-cpp, pull requests merged in 2025-08, with the labels that each got.

#6682 Sync eng/common directory with azure-sdk-tools for PR 11493
  eng/common/mcp/README.md
Labels: EngSys, Central-EngSys

#6686 Sync eng/common directory with azure-sdk-tools for PR 10749
  eng/common/TestResources/TestResources-Helpers.ps1
Labels: EngSys, Central-EngSys

#6683 Sync eng/common directory with azure-sdk-tools for PR 11330
  eng/common/spelling/Invoke-Cspell.ps1
  eng/common/spelling/README.md
Labels: EngSys, Central-EngSys

#6695 Storage/STG100 Protocol Layer Changes
  sdk/storage/assets.json
  sdk/storage/azure-storage-blobs/inc/azure/storage/blobs/rest_client.hpp
  sdk/storage/azure-storage-blobs/src/rest_client.cpp
  sdk/storage/azure-storage-blobs/swagger/README.md
  sdk/storage/azure-storage-files-datalake/inc/azure/storage/files/datalake/rest_client.hpp
  sdk/storage/azure-storage-files-datalake/src/rest_client.cpp
  sdk/storage/azure-storage-files-datalake/swagger/README.md
  sdk/storage/azure-storage-files-shares/inc/azure/storage/files/shares/rest_client.hpp
  sdk/storage/azure-storage-files-shares/src/rest_client.cpp
  sdk/storage/azure-storage-files-shares/src/share_file_client.cpp
  sdk/storage/azure-storage-files-shares/swagger/README.md
  sdk/storage/azure-storage-queues/inc/azure/storage/queues/rest_client.hpp
  sdk/storage/azure-storage-queues/src/rest_client.cpp
  sdk/storage/azure-storage-queues/swagger/README.md
Labels: Storage

#6698 Fix IMDS token requests for managed identities
  sdk/identity/azure-identity/CHANGELOG.md
  sdk/identity/azure-identity/src/managed_identity_source.cpp
Labels: customer-reported, Azure.Identity, Community Contribution

#6699 Principal Bound Delegation Sas and TQF
  sdk/storage/azure-storage-blobs/inc/azure/storage/blobs/blob_sas_builder.hpp
  sdk/storage/azure-storage-blobs/src/blob_sas_builder.cpp
  sdk/storage/azure-storage-blobs/test/ut/blob_sas_test.cpp
  sdk/storage/azure-storage-files-datalake/inc/azure/storage/files/datalake/datalake_sas_builder.hpp
  sdk/storage/azure-storage-files-datalake/src/datalake_sas_builder.cpp
  sdk/storage/azure-storage-files-datalake/test/ut/datalake_sas_test.cpp
  sdk/storage/azure-storage-files-shares/inc/azure/storage/files/shares/share_options.hpp
  sdk/storage/azure-storage-files-shares/inc/azure/storage/files/shares/share_sas_builder.hpp
  sdk/storage/azure-storage-files-shares/inc/azure/storage/files/shares/share_service_client.hpp
  sdk/storage/azure-storage-files-shares/src/share_sas_builder.cpp
  sdk/storage/azure-storage-files-shares/src/share_service_client.cpp
  sdk/storage/azure-storage-files-shares/test/ut/share_sas_test.cpp
  sdk/storage/azure-storage-queues/inc/azure/storage/queues/queue_options.hpp
  sdk/storage/azure-storage-queues/inc/azure/storage/queues/queue_sas_builder.hpp
  sdk/storage/azure-storage-queues/inc/azure/storage/queues/queue_service_client.hpp
  sdk/storage/azure-storage-queues/src/queue_sas_builder.cpp
  sdk/storage/azure-storage-queues/src/queue_service_client.cpp
  sdk/storage/azure-storage-queues/test/ut/queue_sas_test.cpp
Labels: Storage

#6703 Sync eng/common directory with azure-sdk-tools for PR 11726
  eng/common/scripts/Mark-ReleasePlanCompletion.ps1
Labels: EngSys, Central-EngSys

#6704 Storage STG100/ Blob Tags Condition and DataLake Tags support
  sdk/storage/assets.json
  sdk/storage/azure-storage-blobs/inc/azure/storage/blobs/blob_options.hpp
  sdk/storage/azure-storage-blobs/inc/azure/storage/blobs/rest_client.hpp
  sdk/storage/azure-storage-blobs/src/blob_client.cpp
  sdk/storage/azure-storage-blobs/src/rest_client.cpp
  sdk/storage/azure-storage-blobs/test/ut/block_blob_client_test.cpp
Labels: Storage

#6712 Sync eng/common directory with azure-sdk-tools for PR 11807
  eng/common/scripts/Mark-ReleasePlanCompletion.ps1
Labels: EngSys, Central-EngSys

#6708 Blob and DFS start from
  sdk/storage/azure-storage-blobs/inc/azure/storage/blobs/blob_options.hpp
  sdk/storage/azure-storage-blobs/src/blob_container_client.cpp
  sdk/storage/azure-storage-files-datalake/inc/azure/storage/files/datalake/datalake_options.hpp
  sdk/storage/azure-storage-files-datalake/src/datalake_file_system_client.cpp
Labels: Storage

#6711 Sync eng/common directory with azure-sdk-tools for PR 11802
  eng/common/instructions/azsdk-tools/typespec-to-sdk.instructions.md
  eng/common/instructions/azsdk-tools/validate-codeowners.instructions.md
  eng/common/instructions/azsdk-tools/validate-service-label.instruction.md
Labels: EngSys, Central-EngSys

#6716 Sync eng/common directory with azure-sdk-tools for PR 11840
  eng/common/instructions/azsdk-tools/validate-service-label.instructions.md
Labels: EngSys, Central-EngSys

#6717 Sync eng/common directory with azure-sdk-tools for PR 11839
  eng/common/instructions/azsdk-tools/check-package-readiness.instructions.md
  eng/common/instructions/azsdk-tools/create-release-plan.instructions.md
  eng/common/instructions/azsdk-tools/sdk-details-in-release-plan.instructions.md
  eng/common/instructions/azsdk-tools/typespec-to-sdk.instructions.md
  eng/common/instructions/azsdk-tools/verify-namespace-approval.instructions.md
Labels: EngSys, Central-EngSys

#6719 Sync eng/common directory with azure-sdk-tools for PR 11905
  eng/common/instructions/azsdk-tools/validate-codeowners.instructions.md
  eng/common/instructions/azsdk-tools/validate-service-label.instructions.md
Labels: EngSys, Central-EngSys
