Repository Azure/azure-sdk-for-cpp, pull requests merged in 2025-04, with the labels that each got.

#6499 Sync eng/common directory with azure-sdk-tools for PR 10181
  eng/common/scripts/logging.ps1
Labels: EngSys, Central-EngSys

#6500 Sync eng/common directory with azure-sdk-tools for PR 10176
  eng/common/scripts/Helpers/ApiView-Helpers.ps1
Labels: EngSys, Central-EngSys

#6494 Sync eng/common directory with azure-sdk-tools for PR 10038
  eng/common/pipelines/templates/stages/archetype-sdk-tool-pwsh.yml
  eng/common/scripts/Package-Properties.ps1
Labels: EngSys, Central-EngSys

#6503 Sync eng/common directory with azure-sdk-tools for PR 10191
  eng/common/scripts/Helpers/ApiView-Helpers.ps1
Labels: EngSys, Central-EngSys

#6486 Add support for building with ICU 75.1 or later
  sdk/storage/azure-storage-common/CHANGELOG.md
  sdk/storage/azure-storage-common/src/xml_wrapper.cpp
  sdk/tables/azure-data-tables/CHANGELOG.md
  sdk/tables/azure-data-tables/src/xml_wrapper.cpp
Labels: customer-reported, Storage, Community Contribution, Tables

#6502 Sync eng/common directory with azure-sdk-tools for PR 10184
  eng/common/scripts/stress-testing/stress-test-deployment-lib.ps1
Labels: EngSys, Central-EngSys

#6505 Sync eng/common directory with azure-sdk-tools for PR 10190
  eng/common/testproxy/test-proxy-standalone-tool.yml
  eng/common/testproxy/test-proxy-tool.yml
Labels: EngSys, Central-EngSys

#6506 Sync eng/common directory with azure-sdk-tools for PR 10206
  eng/common/TestResources/New-TestResources.ps1
Labels: EngSys, Central-EngSys

#6511 Storage/STG98 Update blob sas new string to sign
  sdk/storage/azure-storage-blobs/src/blob_sas_builder.cpp
Labels: Storage

#6512 Sync eng/common directory with azure-sdk-tools for PR 10182
  eng/common/scripts/job-matrix/Create-JobMatrix.ps1
  eng/common/scripts/job-matrix/job-matrix-functions.ps1
Labels: EngSys, Central-EngSys

#6507 Certs update
  .vscode/cspell.json
  sdk/keyvault/assets.json
  sdk/keyvault/azure-security-keyvault-certificates/CMakeLists.txt
  sdk/keyvault/azure-security-keyvault-certificates/inc/azure/keyvault/certificates/certificate_client.hpp
  sdk/keyvault/azure-security-keyvault-certificates/inc/azure/keyvault/certificates/certificate_client_models.hpp
  sdk/keyvault/azure-security-keyvault-certificates/samples/certificate-basic-operations/certificate_basic_operations.cpp
  sdk/keyvault/azure-security-keyvault-certificates/samples/certificate-get-certificates/certificate_get_certificates.cpp
  sdk/keyvault/azure-security-keyvault-certificates/samples/certificate-import-certificate/certificate_import_certificate.cpp
  sdk/keyvault/azure-security-keyvault-certificates/src/certificate_client.cpp
  sdk/keyvault/azure-security-keyvault-certificates/src/certificate_client_models.cpp
  sdk/keyvault/azure-security-keyvault-certificates/src/certificate_client_operations.cpp
  sdk/keyvault/azure-security-keyvault-certificates/src/certificate_client_paged_response.cpp
  sdk/keyvault/azure-security-keyvault-certificates/src/certificate_serializers.cpp
  sdk/keyvault/azure-security-keyvault-certificates/src/generated/certificates.cpp
  sdk/keyvault/azure-security-keyvault-certificates/src/generated/certificates_models.hpp
  sdk/keyvault/azure-security-keyvault-certificates/src/generated/get_certificate_issuers_paged_response.cpp
  sdk/keyvault/azure-security-keyvault-certificates/src/generated/get_certificate_versions_paged_response.cpp
  sdk/keyvault/azure-security-keyvault-certificates/src/generated/get_certificates_paged_response.cpp
  sdk/keyvault/azure-security-keyvault-certificates/src/generated/get_deleted_certificates_paged_response.cpp
  sdk/keyvault/azure-security-keyvault-certificates/src/generated/key_vault_client.cpp
  sdk/keyvault/azure-security-keyvault-certificates/src/generated/key_vault_client.hpp
  sdk/keyvault/azure-security-keyvault-certificates/src/generated/key_vault_client_options.hpp
  sdk/keyvault/azure-security-keyvault-certificates/src/generated/key_vault_client_paged_responses.hpp
  sdk/keyvault/azure-security-keyvault-certificates/src/private/certificate_serializers.hpp
  sdk/keyvault/azure-security-keyvault-certificates/test/ut/CMakeLists.txt
  sdk/keyvault/azure-security-keyvault-certificates/test/ut/certificate_client_base_test.hpp
  sdk/keyvault/azure-security-keyvault-certificates/test/ut/certificate_client_test.cpp
  sdk/keyvault/azure-security-keyvault-certificates/tsp-location.yaml
  sdk/keyvault/azure-security-keyvault-certificates/tspconfig.yaml
  sdk/keyvault/ci.yml
Labels: KeyVault

#6508 Kv april releases
  sdk/keyvault/azure-security-keyvault-certificates/CHANGELOG.md
  sdk/keyvault/azure-security-keyvault-keys/CHANGELOG.md
  sdk/keyvault/azure-security-keyvault-secrets/CHANGELOG.md
  sdk/keyvault/azure-security-keyvault-secrets/src/private/package_version.hpp
Labels: KeyVault

#6514 Sync eng/common directory with azure-sdk-tools for PR 10238
  eng/common/scripts/Package-Properties.ps1
Labels: EngSys, Central-EngSys

#6516 Update Identity live test
  sdk/identity/azure-identity/test/ut/azure_pipelines_credential_test.cpp
Labels: Azure.Identity

#6515 Increment version for keyvault releases
  sdk/keyvault/azure-security-keyvault-certificates/CHANGELOG.md
  sdk/keyvault/azure-security-keyvault-certificates/src/private/package_version.hpp
  sdk/keyvault/azure-security-keyvault-keys/CHANGELOG.md
  sdk/keyvault/azure-security-keyvault-keys/src/private/package_version.hpp
  sdk/keyvault/azure-security-keyvault-secrets/CHANGELOG.md
  sdk/keyvault/azure-security-keyvault-secrets/src/private/package_version.hpp
Labels: KeyVault

#6517 Increment version for identity releases
  sdk/identity/azure-identity/CHANGELOG.md
  sdk/identity/azure-identity/src/private/package_version.hpp
Labels: Azure.Identity

#6518 Sync eng/common directory with azure-sdk-tools for PR 10241
  eng/common/pipelines/templates/archetype-typespec-emitter.yml
Labels: EngSys, Central-EngSys

#6520 Sync eng/common directory with azure-sdk-tools for PR 10246
  eng/common/pipelines/templates/archetype-typespec-emitter.yml
Labels: EngSys, Central-EngSys

#6519 Kv cleanup
  sdk/keyvault/assets.json
  sdk/keyvault/azure-security-keyvault-certificates/CMakeLists.txt
  sdk/keyvault/azure-security-keyvault-certificates/inc/azure/keyvault/certificates/certificate_client_models.hpp
  sdk/keyvault/azure-security-keyvault-certificates/inc/azure/keyvault/certificates/certificate_client_options.hpp
  sdk/keyvault/azure-security-keyvault-certificates/src/certificate_client.cpp
  sdk/keyvault/azure-security-keyvault-certificates/src/certificate_client_models.cpp
  sdk/keyvault/azure-security-keyvault-certificates/src/keyvault_certificates_common_request.cpp
  sdk/keyvault/azure-security-keyvault-certificates/src/private/certificate_constants.hpp
  sdk/keyvault/azure-security-keyvault-certificates/src/private/keyvault_certificates_common_request.hpp
  sdk/keyvault/azure-security-keyvault-certificates/test/ut/certificate_client_base_test.hpp
  sdk/keyvault/azure-security-keyvault-certificates/test/ut/certificate_client_test.cpp
  sdk/keyvault/azure-security-keyvault-keys/CMakeLists.txt
  sdk/keyvault/azure-security-keyvault-keys/src/delete_key_operation.cpp
  sdk/keyvault/azure-security-keyvault-keys/src/deleted_key.cpp
  sdk/keyvault/azure-security-keyvault-keys/src/import_key_options.cpp
  sdk/keyvault/azure-security-keyvault-keys/src/json_web_key.cpp
  sdk/keyvault/azure-security-keyvault-keys/src/key_backup.cpp
  sdk/keyvault/azure-security-keyvault-keys/src/key_client.cpp
  sdk/keyvault/azure-security-keyvault-keys/src/key_client_paged_responses.cpp
  sdk/keyvault/azure-security-keyvault-keys/src/key_get_random_bytes.cpp
  sdk/keyvault/azure-security-keyvault-keys/src/key_release_options.cpp
  sdk/keyvault/azure-security-keyvault-keys/src/key_release_policy.cpp
  sdk/keyvault/azure-security-keyvault-keys/src/key_request_parameters.cpp
  sdk/keyvault/azure-security-keyvault-keys/src/key_rotation_policy.cpp
  sdk/keyvault/azure-security-keyvault-keys/src/keyvault_key.cpp
  sdk/keyvault/azure-security-keyvault-keys/src/private/key_backup.hpp
  sdk/keyvault/azure-security-keyvault-keys/src/private/key_constants.hpp
  sdk/keyvault/azure-security-keyvault-keys/src/private/key_request_parameters.hpp
  sdk/keyvault/azure-security-keyvault-keys/src/private/key_serializers.hpp
  sdk/keyvault/azure-security-keyvault-keys/src/recover_deleted_key_operation.cpp
  sdk/keyvault/azure-security-keyvault-keys/test/ut/key_client_create_test_live.cpp
  sdk/keyvault/azure-security-keyvault-keys/test/ut/key_client_delete_test_live.cpp
  sdk/keyvault/azure-security-keyvault-keys/test/ut/key_client_test.cpp
  sdk/keyvault/azure-security-keyvault-keys/test/ut/key_rotation_policy_test_live.cpp
  sdk/keyvault/azure-security-keyvault-secrets/src/private/secret_constants.hpp
Labels: KeyVault

#6524 Sync eng/common directory with azure-sdk-tools for PR 10293
  eng/common/pipelines/templates/archetype-typespec-emitter.yml
Labels: EngSys, Central-EngSys

#6526 Small cleanup
  sdk/keyvault/azure-security-keyvault-keys/CMakeLists.txt
  sdk/keyvault/azure-security-keyvault-secrets/CMakeLists.txt
Labels: KeyVault

#6522 Expose Scopes on the client options
  sdk/tables/azure-data-tables/CMakeLists.txt
  sdk/tables/azure-data-tables/inc/azure/data/tables.hpp
  sdk/tables/azure-data-tables/inc/azure/data/tables/table_audience.hpp
  sdk/tables/azure-data-tables/inc/azure/data/tables/table_client.hpp
  sdk/tables/azure-data-tables/src/private/tables_constants.hpp
  sdk/tables/azure-data-tables/src/table_clients.cpp
  sdk/tables/azure-data-tables/test/ut/serializers_test.hpp
  sdk/tables/azure-data-tables/test/ut/table_client_test.cpp
Labels: Tables

#6528 Sync eng/common directory with azure-sdk-tools for PR 10314
  eng/common/pipelines/templates/archetype-typespec-emitter.yml
Labels: EngSys, Central-EngSys

#6529 Sync eng/common directory with azure-sdk-tools for PR 10345
  eng/common/pipelines/templates/jobs/prepare-pipelines.yml
Labels: EngSys, Central-EngSys

#6531 Sync eng/common directory with azure-sdk-tools for PR 10287
  eng/common/scripts/Helpers/ApiView-Helpers.ps1
Labels: EngSys, Central-EngSys

#6530 Storage/Content Validation Part2
  sdk/storage/azure-storage-blobs/src/blob_client.cpp
  sdk/storage/azure-storage-blobs/src/block_blob_client.cpp
  sdk/storage/azure-storage-blobs/test/ut/block_blob_client_test.cpp
  sdk/storage/azure-storage-files-datalake/inc/azure/storage/files/datalake/datalake_file_client.hpp
  sdk/storage/azure-storage-files-datalake/inc/azure/storage/files/datalake/datalake_options.hpp
  sdk/storage/azure-storage-files-datalake/inc/azure/storage/files/datalake/datalake_responses.hpp
  sdk/storage/azure-storage-files-datalake/inc/azure/storage/files/datalake/rest_client.hpp
  sdk/storage/azure-storage-files-datalake/src/datalake_file_client.cpp
  sdk/storage/azure-storage-files-datalake/src/datalake_utilities.cpp
  sdk/storage/azure-storage-files-datalake/src/rest_client.cpp
  sdk/storage/azure-storage-files-datalake/swagger/README.md
  sdk/storage/azure-storage-files-datalake/test/ut/datalake_file_client_test.cpp
  sdk/storage/azure-storage-files-datalake/test/ut/datalake_service_client_test.cpp
  sdk/storage/azure-storage-files-shares/inc/azure/storage/files/shares/rest_client.hpp
  sdk/storage/azure-storage-files-shares/inc/azure/storage/files/shares/share_file_client.hpp
  sdk/storage/azure-storage-files-shares/inc/azure/storage/files/shares/share_options.hpp
  sdk/storage/azure-storage-files-shares/inc/azure/storage/files/shares/share_responses.hpp
  sdk/storage/azure-storage-files-shares/src/rest_client.cpp
  sdk/storage/azure-storage-files-shares/src/share_file_client.cpp
  sdk/storage/azure-storage-files-shares/swagger/README.md
  sdk/storage/azure-storage-files-shares/test/ut/share_file_client_test.cpp
Labels: Storage

#6533 Sync eng/common directory with azure-sdk-tools for PR 10400
  eng/common/scripts/Package-Properties.ps1
Labels: EngSys, Central-EngSys

#6539 Sync eng/common directory with azure-sdk-tools for PR 10432
  eng/common/pipelines/templates/steps/eng-common-workflow-enforcer.yml
Labels: EngSys, Central-EngSys

#6540 Sync eng/common directory with azure-sdk-tools for PR 10411
  eng/common/scripts/Package-Properties.ps1
Labels: EngSys, Central-EngSys

#6542 Sync eng/common directory with azure-sdk-tools for PR 10461
  eng/common/pipelines/templates/archetype-typespec-emitter.yml
Labels: EngSys, Central-EngSys

#6541 Storage/Fix unstable test cases
  sdk/storage/azure-storage-files-datalake/test/ut/datalake_file_client_test.cpp
  sdk/storage/azure-storage-files-datalake/test/ut/datalake_file_system_client_test.cpp
Labels: Storage

#6543 Sync eng/common directory with azure-sdk-tools for PR 10481
  eng/common/TestResources/New-TestResources.ps1
Labels: EngSys, Central-EngSys

#6544 Sync eng/common directory with azure-sdk-tools for PR 10467
  eng/common/pipelines/templates/steps/publish-1es-artifact.yml
Labels: EngSys, Central-EngSys

#6546 Sync eng/common directory with azure-sdk-tools for PR 10500
  eng/common/pipelines/templates/steps/save-package-properties.yml
Labels: EngSys, Central-EngSys

#6548 Sync eng/common directory with azure-sdk-tools for PR 10482
  eng/common/scripts/Helpers/ApiView-Helpers.ps1
Labels: EngSys, Central-EngSys

#6549 Sync eng/common directory with azure-sdk-tools for PR 10470
  eng/common/mcp/README.md
  eng/common/mcp/azure-sdk-mcp.ps1
  eng/common/scripts/Helpers/AzSdkTool-Helpers.ps1
  eng/common/testproxy/install-test-proxy.ps1
  eng/common/testproxy/test-proxy.ps1
Labels: EngSys, Central-EngSys

#6547 Sync .github/workflows directory with azure-sdk-tools for PR 10483
  .github/workflows/scheduled-event-processor.yml
Labels: EngSys, Central-EngSys

#6550 Sync eng/common directory with azure-sdk-tools for PR 10508
  eng/common/scripts/Helpers/ApiView-Helpers.ps1
Labels: EngSys, Central-EngSys
