Repository Azure/azure-sdk-for-cpp, pull requests merged in 2025-09, with the labels that each got.

#6725 Azure Core and Identity September Releases
  sdk/core/azure-core/CHANGELOG.md
  sdk/core/azure-core/src/private/package_version.hpp
  sdk/identity/azure-identity/CHANGELOG.md
  sdk/identity/azure-identity/src/client_certificate_credential.cpp
  sdk/identity/azure-identity/src/private/package_version.hpp
Labels: Azure.Core, Azure.Identity

#6740 Fix AMQP compilation on Android
  sdk/core/azure-core-amqp/src/impl/uamqp/amqp/claim_based_security.cpp
Labels: Azure.Core, EngSys, AMQP, vcpkg_package_manager

#6742 Sync eng/common directory with azure-sdk-tools for PR 12124
  eng/common/instructions/azsdk-tools/typespec-to-sdk.instructions.md
Labels: EngSys, Central-EngSys

#6746 Sync eng/common directory with azure-sdk-tools for PR 11868
  eng/common/instructions/azsdk-tools/create-sdk-locally.instructions.md
  eng/common/instructions/azsdk-tools/local-sdk-workflow.instructions.md
  eng/common/instructions/azsdk-tools/typespec-to-sdk.instructions.md
Labels: EngSys, Central-EngSys

#6747 Sync eng/common directory with azure-sdk-tools for PR 12060
  eng/common/tsp-client/README.md
  eng/common/tsp-client/package-lock.json
  eng/common/tsp-client/package.json
Labels: EngSys, Central-EngSys

#6734 Sync eng/common directory with azure-sdk-tools for PR 12061
  eng/common/testproxy/target_version.txt
Labels: EngSys, Central-EngSys

#6752 Sync eng/common directory with azure-sdk-tools for PR 12235
  eng/common/scripts/Helpers/CommandInvocation-Helpers.ps1
  eng/common/scripts/logging.ps1
Labels: EngSys, Central-EngSys

#6757 Sync eng/common directory with azure-sdk-tools for PR 12246
  eng/common/mcp/azure-sdk-mcp.ps1
Labels: EngSys, Central-EngSys

#6755 DAC: Disable probe when MIC is selected via env var
  sdk/identity/azure-identity/CHANGELOG.md
  sdk/identity/azure-identity/inc/azure/identity/managed_identity_credential.hpp
  sdk/identity/azure-identity/src/default_azure_credential.cpp
  sdk/identity/azure-identity/src/managed_identity_credential.cpp
  sdk/identity/azure-identity/src/managed_identity_source.cpp
  sdk/identity/azure-identity/src/private/managed_identity_source.hpp
  sdk/identity/azure-identity/test/ut/default_azure_credential_test.cpp
  sdk/identity/azure-identity/test/ut/managed_identity_credential_test.cpp
Labels: Azure.Identity, Managed Identity, Security
