Repository Azure/azure-sdk-for-cpp, pull requests merged in 2025-03, with the labels that each got.

#6439 Sync eng/common directory with azure-sdk-tools for PR 9950
  eng/common/pipelines/templates/archetype-typespec-emitter.yml
  eng/common/pipelines/templates/jobs/prepare-pipelines.yml
Labels: EngSys, Central-EngSys

#6443 Sync eng/common directory with azure-sdk-tools for PR 9955
  eng/common/scripts/Detect-Api-Changes.ps1
Labels: EngSys, Central-EngSys

#6444 Sync eng/common directory with azure-sdk-tools for PR 9945
  eng/common/scripts/job-matrix/Create-PrJobMatrix.ps1
Labels: EngSys, Central-EngSys

#6446 Sync eng/common directory with azure-sdk-tools for PR 9963
  eng/common/scripts/Package-Properties.ps1
Labels: EngSys, Central-EngSys

#6448 Sync eng/common directory with azure-sdk-tools for PR 9982
  eng/common/pipelines/templates/steps/sparse-checkout.yml
Labels: EngSys, Central-EngSys

#6447 Sync eng/common directory with azure-sdk-tools for PR 9918
  eng/common/scripts/job-matrix/pullrequest-faq.md
Labels: EngSys, Central-EngSys

#6438 Sync eng/common directory with azure-sdk-tools for PR 9943
  eng/common/TestResources/New-TestResources.ps1
Labels: EngSys, Central-EngSys

#6450 Azure Core March GA Release
  sdk/core/azure-core/CHANGELOG.md
  sdk/core/azure-core/src/private/package_version.hpp
Labels: Azure.Core

#6452 Increment version for core releases
  sdk/core/azure-core/CHANGELOG.md
  sdk/core/azure-core/src/private/package_version.hpp
Labels: Azure.Core

#6449 Update the logging level for CRL validation failures
  sdk/core/azure-core/src/http/curl/curl.cpp
Labels: Azure.Core

#6445 Storage March Release
  sdk/storage/azure-storage-common/CHANGELOG.md
  sdk/storage/azure-storage-common/src/private/package_version.hpp
  sdk/storage/azure-storage-common/vcpkg.json
  sdk/storage/azure-storage-files-shares/CHANGELOG.md
  sdk/storage/azure-storage-files-shares/src/private/package_version.hpp
  sdk/storage/azure-storage-files-shares/vcpkg.json
  sdk/storage/azure-storage-files-shares/vcpkg/vcpkg.json
Labels: Storage

#6455 Sync eng/common directory with azure-sdk-tools for PR 10013
  eng/common/TestResources/New-TestResources.ps1
Labels: EngSys, Central-EngSys

#6451 Azure Identity March Beta Release
  sdk/identity/azure-identity/CHANGELOG.md
Labels: Azure.Identity, Managed Identity

#6456 Sync eng/common directory with azure-sdk-tools for PR 9993
  eng/common/scripts/Package-Properties.ps1
Labels: EngSys, Central-EngSys

#6457 Increment version for identity releases
  sdk/identity/azure-identity/CHANGELOG.md
  sdk/identity/azure-identity/src/private/package_version.hpp
Labels: Azure.Identity

#6459 Sync eng/common directory with azure-sdk-tools for PR 10030
  eng/common/pipelines/templates/steps/detect-api-changes.yml
Labels: EngSys, Central-EngSys

#6460 Increment version for storage releases
  sdk/storage/azure-storage-common/CHANGELOG.md
  sdk/storage/azure-storage-common/src/private/package_version.hpp
  sdk/storage/azure-storage-files-shares/CHANGELOG.md
  sdk/storage/azure-storage-files-shares/src/private/package_version.hpp
Labels: Storage

#6462 Sync eng/common directory with azure-sdk-tools for PR 10028
  eng/common/scripts/Package-Properties.ps1
Labels: EngSys, Central-EngSys

#6458 Sync eng/common directory with azure-sdk-tools for PR 10027
  eng/common/TestResources/New-TestResources.ps1
Labels: EngSys, Central-EngSys

#6464 Sync eng/common directory with azure-sdk-tools for PR 10039
  eng/common/scripts/job-matrix/Create-PrJobMatrix.ps1
Labels: EngSys, Central-EngSys

#6465 Sync eng/common directory with azure-sdk-tools for PR 10041
  eng/common/scripts/Helpers/Resource-Helpers.ps1
Labels: EngSys, Central-EngSys

#6467 Sync eng/common directory with azure-sdk-tools for PR 10046
  eng/common/scripts/job-matrix/Create-PrJobMatrix.ps1
Labels: EngSys, Central-EngSys

#6466 Sync eng/common directory with azure-sdk-tools for PR 10045
  eng/common/pipelines/templates/jobs/prepare-pipelines.yml
Labels: EngSys, Central-EngSys

#6463 Keyvault Secrets remake
  cmake-modules/TSPCompile.cmake
  eng/scripts/typespec/Build-Codegen.ps1
  eng/scripts/typespec/Generate-Code.ps1
  eng/scripts/typespec/Run-Tsp-Update.ps1
  sdk/keyvault/assets.json
  sdk/keyvault/azure-security-keyvault-secrets/CMakeLists.txt
  sdk/keyvault/azure-security-keyvault-secrets/README.md
  sdk/keyvault/azure-security-keyvault-secrets/client.tsp
  sdk/keyvault/azure-security-keyvault-secrets/inc/azure/keyvault/secrets/generated.hpp
  sdk/keyvault/azure-security-keyvault-secrets/inc/azure/keyvault/secrets/generated/dll_import_export.hpp
  sdk/keyvault/azure-security-keyvault-secrets/inc/azure/keyvault/secrets/generated/key_vault_client.hpp
  sdk/keyvault/azure-security-keyvault-secrets/inc/azure/keyvault/secrets/generated/key_vault_client_options.hpp
  sdk/keyvault/azure-security-keyvault-secrets/inc/azure/keyvault/secrets/generated/key_vault_client_paged_responses.hpp
  sdk/keyvault/azure-security-keyvault-secrets/inc/azure/keyvault/secrets/generated/models/generated_models.hpp
  sdk/keyvault/azure-security-keyvault-secrets/inc/azure/keyvault/secrets/generated/rtti.hpp
  sdk/keyvault/azure-security-keyvault-secrets/inc/azure/keyvault/secrets/keyvault_deleted_secret.hpp
  sdk/keyvault/azure-security-keyvault-secrets/inc/azure/keyvault/secrets/keyvault_operations.hpp
  sdk/keyvault/azure-security-keyvault-secrets/inc/azure/keyvault/secrets/keyvault_options.hpp
  sdk/keyvault/azure-security-keyvault-secrets/inc/azure/keyvault/secrets/keyvault_secret.hpp
  sdk/keyvault/azure-security-keyvault-secrets/inc/azure/keyvault/secrets/keyvault_secret_paged_response.hpp
  sdk/keyvault/azure-security-keyvault-secrets/inc/azure/keyvault/secrets/keyvault_secret_properties.hpp
  sdk/keyvault/azure-security-keyvault-secrets/inc/azure/keyvault/secrets/secret_client.hpp
  sdk/keyvault/azure-security-keyvault-secrets/samples/sample1-basic-operations/sample1_basic_operations.cpp
  sdk/keyvault/azure-security-keyvault-secrets/samples/sample1_basic_operations.md
  sdk/keyvault/azure-security-keyvault-secrets/src/generated.cpp
  sdk/keyvault/azure-security-keyvault-secrets/src/get_deleted_secrets_paged_response.cpp
  sdk/keyvault/azure-security-keyvault-secrets/src/get_secret_versions_paged_response.cpp
  sdk/keyvault/azure-security-keyvault-secrets/src/get_secrets_paged_response.cpp
  sdk/keyvault/azure-security-keyvault-secrets/src/key_vault_client.cpp
  sdk/keyvault/azure-security-keyvault-secrets/src/keyvault_deleted_secret.cpp
  sdk/keyvault/azure-security-keyvault-secrets/src/keyvault_operations.cpp
  sdk/keyvault/azure-security-keyvault-secrets/src/keyvault_secret.cpp
  sdk/keyvault/azure-security-keyvault-secrets/src/keyvault_secret_properties.cpp
  sdk/keyvault/azure-security-keyvault-secrets/src/keyvault_secrets_common_request.cpp
  sdk/keyvault/azure-security-keyvault-secrets/src/private/generated_package_version.hpp
  sdk/keyvault/azure-security-keyvault-secrets/src/private/keyvault_secrets_common_request.hpp
  sdk/keyvault/azure-security-keyvault-secrets/src/private/package_version.hpp
  sdk/keyvault/azure-security-keyvault-secrets/src/private/secret_serializers.hpp
  sdk/keyvault/azure-security-keyvault-secrets/src/secret_client.cpp
  sdk/keyvault/azure-security-keyvault-secrets/src/secret_serializers.cpp
  sdk/keyvault/azure-security-keyvault-secrets/test/ut/CMakeLists.txt
  sdk/keyvault/azure-security-keyvault-secrets/test/ut/secret_backup_deserialize_test.cpp
  sdk/keyvault/azure-security-keyvault-secrets/test/ut/secret_backup_deserialize_test.hpp
  sdk/keyvault/azure-security-keyvault-secrets/test/ut/secret_client_test.cpp
  sdk/keyvault/azure-security-keyvault-secrets/test/ut/secret_get_client_deserialize_test.cpp
  sdk/keyvault/azure-security-keyvault-secrets/test/ut/secret_get_client_deserialize_test.hpp
  sdk/keyvault/azure-security-keyvault-secrets/test/ut/secret_paged_deserialize_test.cpp
  sdk/keyvault/azure-security-keyvault-secrets/test/ut/secret_paged_deserialize_test.hpp
  sdk/keyvault/azure-security-keyvault-secrets/test/ut/secret_set_parameters_serializer_test.cpp
  sdk/keyvault/azure-security-keyvault-secrets/test/ut/secret_update_properties_test.cpp
  sdk/keyvault/azure-security-keyvault-secrets/tsp-location.yaml
  sdk/keyvault/azure-security-keyvault-secrets/tspconfig.yaml
  sdk/keyvault/ci.yml
Labels: KeyVault

#6468 Sync .github/workflows directory with azure-sdk-tools for PR 10054
  .github/workflows/event-processor.yml
  .github/workflows/scheduled-event-processor.yml
Labels: EngSys, Central-EngSys

#6472 regen into generated folder
  sdk/keyvault/azure-security-keyvault-secrets/CMakeLists.txt
  sdk/keyvault/azure-security-keyvault-secrets/inc/azure/keyvault/secrets/dll_import_export.hpp
  sdk/keyvault/azure-security-keyvault-secrets/inc/azure/keyvault/secrets/generated.hpp
  sdk/keyvault/azure-security-keyvault-secrets/inc/azure/keyvault/secrets/generated/dll_import_export.hpp
  sdk/keyvault/azure-security-keyvault-secrets/inc/azure/keyvault/secrets/generated/rtti.hpp
  sdk/keyvault/azure-security-keyvault-secrets/inc/azure/keyvault/secrets/keyvault_options.hpp
  sdk/keyvault/azure-security-keyvault-secrets/inc/azure/keyvault/secrets/keyvault_secret_paged_response.hpp
  sdk/keyvault/azure-security-keyvault-secrets/inc/azure/keyvault/secrets/secret_client.hpp
  sdk/keyvault/azure-security-keyvault-secrets/src/generated/get_deleted_secrets_paged_response.cpp
  sdk/keyvault/azure-security-keyvault-secrets/src/generated/get_secret_versions_paged_response.cpp
  sdk/keyvault/azure-security-keyvault-secrets/src/generated/get_secrets_paged_response.cpp
  sdk/keyvault/azure-security-keyvault-secrets/src/generated/key_vault_client.cpp
  sdk/keyvault/azure-security-keyvault-secrets/src/generated/key_vault_client.hpp
  sdk/keyvault/azure-security-keyvault-secrets/src/generated/key_vault_client_options.hpp
  sdk/keyvault/azure-security-keyvault-secrets/src/generated/key_vault_client_paged_responses.hpp
  sdk/keyvault/azure-security-keyvault-secrets/src/generated/secrets.cpp
  sdk/keyvault/azure-security-keyvault-secrets/src/generated/secrets_models.hpp
  sdk/keyvault/azure-security-keyvault-secrets/src/keyvault_deleted_secret.cpp
  sdk/keyvault/azure-security-keyvault-secrets/src/keyvault_secret.cpp
  sdk/keyvault/azure-security-keyvault-secrets/src/keyvault_secret_paged_response.cpp
  sdk/keyvault/azure-security-keyvault-secrets/src/keyvault_secret_properties.cpp
  sdk/keyvault/azure-security-keyvault-secrets/src/private/generated_package_version.hpp
  sdk/keyvault/azure-security-keyvault-secrets/src/secret_client.cpp
  sdk/keyvault/azure-security-keyvault-secrets/tspconfig.yaml
Labels: KeyVault

#6473 Sync eng/common directory with azure-sdk-tools for PR 10081
  eng/common/scripts/job-matrix/job-matrix-functions.ps1
Labels: EngSys, Central-EngSys

#6478 Sync eng/common directory with azure-sdk-tools for PR 10100
  eng/common/pipelines/templates/stages/archetype-spec-gen-sdk.yml
Labels: EngSys, Central-EngSys

#6483 Sync eng/common directory with azure-sdk-tools for PR 10129
  eng/common/scripts/job-matrix/Create-PrJobMatrix.ps1
Labels: EngSys, Central-EngSys

#6476 Sync eng/common directory with azure-sdk-tools for PR 10099
  eng/common/TestResources/New-TestResources.ps1
  eng/common/TestResources/deploy-test-resources.yml
Labels: EngSys, Central-EngSys

#6484 Sync eng/common directory with azure-sdk-tools for PR 10135
  eng/common/TestResources/deploy-test-resources.yml
Labels: EngSys, Central-EngSys

#6485 Storage/Fix unstable test cases
  sdk/storage/azure-storage-files-datalake/test/ut/datalake_directory_client_test.cpp
Labels: Storage

#6461 GeoDR preparation - EventHubs Offset is a string, not an integer encoded as a string
  sdk/eventhubs/azure-messaging-eventhubs-checkpointstore-blob/src/blob_checkpoint_store.cpp
  sdk/eventhubs/azure-messaging-eventhubs-checkpointstore-blob/test/ut/blob_checkpoint_store_test.cpp
  sdk/eventhubs/azure-messaging-eventhubs/inc/azure/messaging/eventhubs/models/checkpoint_store_models.hpp
  sdk/eventhubs/azure-messaging-eventhubs/inc/azure/messaging/eventhubs/models/event_data.hpp
  sdk/eventhubs/azure-messaging-eventhubs/inc/azure/messaging/eventhubs/models/management_models.hpp
  sdk/eventhubs/azure-messaging-eventhubs/inc/azure/messaging/eventhubs/models/partition_client_models.hpp
  sdk/eventhubs/azure-messaging-eventhubs/src/event_data.cpp
  sdk/eventhubs/azure-messaging-eventhubs/src/partition_client.cpp
  sdk/eventhubs/azure-messaging-eventhubs/src/private/eventhubs_constants.hpp
  sdk/eventhubs/azure-messaging-eventhubs/src/private/eventhubs_utilities.hpp
  sdk/eventhubs/azure-messaging-eventhubs/src/processor_partition_client.cpp
  sdk/eventhubs/azure-messaging-eventhubs/test/ut/checkpoint_store_test.cpp
  sdk/eventhubs/azure-messaging-eventhubs/test/ut/event_data_test.cpp
  sdk/eventhubs/azure-messaging-eventhubs/test/ut/processor_test.cpp
  sdk/eventhubs/azure-messaging-eventhubs/test/ut/round_trip_test.cpp
Labels: Event Hubs

#6490 Sync eng/common directory with azure-sdk-tools for PR 10004
  eng/common/scripts/Helpers/ApiView-Helpers.ps1
  eng/common/scripts/Invoke-GitHubAPI.ps1
Labels: EngSys, Central-EngSys

#6488 Sync eng/common directory with azure-sdk-tools for PR 10145
  eng/common/pipelines/templates/jobs/generate-job-matrix.yml
  eng/common/scripts/job-matrix/Create-PrJobMatrix.ps1
Labels: EngSys, Central-EngSys

#6493 Update Identity root README to align with the common format
  sdk/identity/azure-identity/README.md
Labels: Docs, Azure.Identity

#6496 Temporary fix for the live pipeline
  sdk/tables/azure-data-tables/test/ut/table_client_test.cpp
Labels: Tables

#6489 Sync eng/common directory with azure-sdk-tools for PR 10134
  eng/common/scripts/Delete-RemoteTag.ps1
  eng/common/scripts/Helpers/git-helpers.ps1
  eng/common/scripts/Helpers/git-helpers.tests.ps1
Labels: EngSys, Central-EngSys
