Repository Azure/azure-sdk-for-cpp, pull requests merged in 2025-02, with the labels that each got.

#6387 Sync eng/common directory with azure-sdk-tools for PR 9752
  eng/common/scripts/Helpers/DevOps-WorkItem-Helpers.ps1
  eng/common/scripts/Helpers/PSModule-Helpers.ps1
Labels: EngSys, Central-EngSys

#6388 Sync eng/common directory with azure-sdk-tools for PR 9698
  eng/common/pipelines/templates/jobs/prepare-pipelines.yml
  eng/common/pipelines/templates/steps/sparse-checkout.yml
  eng/common/pipelines/templates/steps/validate-all-packages.yml
Labels: EngSys, Central-EngSys

#6389 Sync eng/common directory with azure-sdk-tools for PR 9733
  eng/common/scripts/Detect-Api-Changes.ps1
Labels: EngSys, Central-EngSys

#6386 Sync eng/common directory with azure-sdk-tools for PR 9747
  eng/common/scripts/job-matrix/Create-PrJobMatrix.ps1
  eng/common/scripts/job-matrix/job-matrix-functions.ps1
Labels: EngSys, Central-EngSys

#6390 Sync eng/common directory with azure-sdk-tools for PR 9745
  eng/common/TestResources/New-TestResources.ps1
Labels: EngSys, Central-EngSys

#6397 Sync eng/common directory with azure-sdk-tools for PR 9764
  eng/common/pipelines/templates/jobs/prepare-pipelines.yml
Labels: EngSys, Central-EngSys

#6399 Sync eng/common directory with azure-sdk-tools for PR 9783
  eng/common/TestResources/TestResources-Helpers.ps1
Labels: EngSys, Central-EngSys

#6400 Sync eng/common directory with azure-sdk-tools for PR 9788
  eng/common/scripts/Package-Properties.ps1
Labels: EngSys, Central-EngSys

#6401 Sync eng/common directory with azure-sdk-tools for PR 9793
  eng/common/pipelines/templates/steps/install-pipeline-generation.yml
Labels: EngSys, Central-EngSys

#6396 Storage STG97 Features
  sdk/core/azure-core-test/src/test_proxy_manager.cpp
  sdk/storage/assets.json
  sdk/storage/azure-storage-common/src/account_sas_builder.cpp
  sdk/storage/azure-storage-files-shares/inc/azure/storage/files/shares/rest_client.hpp
  sdk/storage/azure-storage-files-shares/inc/azure/storage/files/shares/share_file_client.hpp
  sdk/storage/azure-storage-files-shares/inc/azure/storage/files/shares/share_options.hpp
  sdk/storage/azure-storage-files-shares/inc/azure/storage/files/shares/share_responses.hpp
  sdk/storage/azure-storage-files-shares/src/rest_client.cpp
  sdk/storage/azure-storage-files-shares/src/share_directory_client.cpp
  sdk/storage/azure-storage-files-shares/src/share_file_client.cpp
  sdk/storage/azure-storage-files-shares/src/share_options.cpp
  sdk/storage/azure-storage-files-shares/src/share_responses.cpp
  sdk/storage/azure-storage-files-shares/swagger/README.md
  sdk/storage/azure-storage-files-shares/test/ut/CMakeLists.txt
  sdk/storage/azure-storage-files-shares/test/ut/share_directory_client_test.cpp
  sdk/storage/azure-storage-files-shares/test/ut/share_file_client_test.cpp
  sdk/storage/azure-storage-files-shares/test/ut/share_utility_test.cpp
Labels: Azure.Core, Storage

#6402 Sync eng/common directory with azure-sdk-tools for PR 9799
  eng/common/scripts/Helpers/Package-Helpers.ps1
Labels: EngSys, Central-EngSys

#6403 Storage February Release
  sdk/storage/azure-storage-common/CHANGELOG.md
  sdk/storage/azure-storage-common/vcpkg.json
  sdk/storage/azure-storage-files-shares/CHANGELOG.md
  sdk/storage/azure-storage-files-shares/vcpkg.json
Labels: Storage

#6405 Storage STG98 Get Set Acl and AccountInfo OAuth Support(Test only)
  sdk/storage/assets.json
  sdk/storage/azure-storage-blobs/test/ut/blob_container_client_test.cpp
  sdk/storage/azure-storage-files-datalake/test/ut/datalake_file_system_client_test.cpp
  sdk/storage/azure-storage-queues/test/ut/queue_client_test.cpp
Labels: Storage

#6406 Storage STG98/Added support for x-ms-file-request-intent for blob copy APIs
  sdk/storage/assets.json
  sdk/storage/azure-storage-blobs/inc/azure/storage/blobs/blob_options.hpp
  sdk/storage/azure-storage-blobs/inc/azure/storage/blobs/rest_client.hpp
  sdk/storage/azure-storage-blobs/src/append_blob_client.cpp
  sdk/storage/azure-storage-blobs/src/blob_client.cpp
  sdk/storage/azure-storage-blobs/src/block_blob_client.cpp
  sdk/storage/azure-storage-blobs/src/page_blob_client.cpp
  sdk/storage/azure-storage-blobs/src/rest_client.cpp
  sdk/storage/azure-storage-blobs/swagger/README.md
  sdk/storage/azure-storage-blobs/test/ut/CMakeLists.txt
  sdk/storage/azure-storage-blobs/test/ut/append_blob_client_test.cpp
  sdk/storage/azure-storage-blobs/test/ut/block_blob_client_test.cpp
  sdk/storage/azure-storage-blobs/test/ut/page_blob_client_test.cpp
Labels: Storage

#6404 Storage STG98/NFS 2
  sdk/storage/assets.json
  sdk/storage/azure-storage-files-shares/inc/azure/storage/files/shares/share_file_client.hpp
  sdk/storage/azure-storage-files-shares/inc/azure/storage/files/shares/share_options.hpp
  sdk/storage/azure-storage-files-shares/inc/azure/storage/files/shares/share_responses.hpp
  sdk/storage/azure-storage-files-shares/src/share_file_client.cpp
  sdk/storage/azure-storage-files-shares/test/ut/share_file_client_test.cpp
Labels: Storage

#6409 Sync eng/common directory with azure-sdk-tools for PR 9810
  eng/common/pipelines/templates/steps/set-test-pipeline-version.yml
  eng/common/scripts/SetTestPipelineVersion.ps1
Labels: EngSys, Central-EngSys

#6417 Sync eng/common directory with azure-sdk-tools for PR 9807
  eng/common/scripts/Package-Properties.ps1
  eng/common/scripts/job-matrix/Create-PrJobMatrix.ps1
Labels: EngSys, Central-EngSys

#6416 Sync eng/common directory with azure-sdk-tools for PR 9821
  eng/common/pipelines/templates/steps/save-package-properties.yml
Labels: EngSys, Central-EngSys

#6419 Sync eng/common directory with azure-sdk-tools for PR 9823
  eng/common/scripts/Generate-PR-Diff.ps1
Labels: EngSys, Central-EngSys

#6418 Update github.io doc links
  sdk/attestation/azure-security-attestation/samples/README.md
  sdk/eventhubs/azure-messaging-eventhubs-checkpointstore-blob/README.md
  sdk/eventhubs/azure-messaging-eventhubs/README.md
  sdk/eventhubs/azure-messaging-eventhubs/samples/README.md
  sdk/tables/azure-data-tables/README.md
Labels: Attestation, Event Hubs, Tables

#6415 Identity: Add AzureCliCredentialOptions::Subscription
  sdk/identity/azure-identity/CHANGELOG.md
  sdk/identity/azure-identity/inc/azure/identity/azure_cli_credential.hpp
  sdk/identity/azure-identity/src/azure_cli_credential.cpp
  sdk/identity/azure-identity/test/ut/azure_cli_credential_test.cpp
Labels: Azure.Identity

#6414 Identity: Disable GCC warning
  sdk/identity/azure-identity/CHANGELOG.md
  sdk/identity/azure-identity/inc/azure/identity/client_certificate_credential.hpp
Labels: Azure.Identity

#6420 Sync eng/common directory with azure-sdk-tools for PR 9832
  eng/common/pipelines/templates/steps/save-package-properties.yml
Labels: EngSys, Central-EngSys

#6421 Sync eng/common directory with azure-sdk-tools for PR 9834
  eng/common/TestResources/New-TestResources.ps1
  eng/common/TestResources/Remove-TestResources.ps1
  eng/common/TestResources/Update-TestResources.ps1
Labels: EngSys, Central-EngSys

#6422 Sync eng/common directory with azure-sdk-tools for PR 9836
  eng/common/scripts/job-matrix/Create-PrJobMatrix.ps1
Labels: EngSys, Central-EngSys

#6407 Storage STG99/Content Validation - Main Function and Blob Support
  sdk/storage/assets.json
  sdk/storage/azure-storage-blobs/inc/azure/storage/blobs/blob_client.hpp
  sdk/storage/azure-storage-blobs/inc/azure/storage/blobs/blob_options.hpp
  sdk/storage/azure-storage-blobs/inc/azure/storage/blobs/rest_client.hpp
  sdk/storage/azure-storage-blobs/src/append_blob_client.cpp
  sdk/storage/azure-storage-blobs/src/blob_client.cpp
  sdk/storage/azure-storage-blobs/src/block_blob_client.cpp
  sdk/storage/azure-storage-blobs/src/page_blob_client.cpp
  sdk/storage/azure-storage-blobs/src/rest_client.cpp
  sdk/storage/azure-storage-blobs/swagger/README.md
  sdk/storage/azure-storage-blobs/test/ut/append_blob_client_test.cpp
  sdk/storage/azure-storage-blobs/test/ut/block_blob_client_test.cpp
  sdk/storage/azure-storage-blobs/test/ut/page_blob_client_test.cpp
  sdk/storage/azure-storage-common/CMakeLists.txt
  sdk/storage/azure-storage-common/inc/azure/storage/common/internal/constants.hpp
  sdk/storage/azure-storage-common/inc/azure/storage/common/internal/structured_message_decoding_stream.hpp
  sdk/storage/azure-storage-common/inc/azure/storage/common/internal/structured_message_encoding_stream.hpp
  sdk/storage/azure-storage-common/inc/azure/storage/common/internal/structured_message_helper.hpp
  sdk/storage/azure-storage-common/inc/azure/storage/common/storage_common.hpp
  sdk/storage/azure-storage-common/src/structured_message_decoding_stream.cpp
  sdk/storage/azure-storage-common/src/structured_message_encoding_stream.cpp
  sdk/storage/azure-storage-common/src/structured_message_helper.cpp
  sdk/storage/azure-storage-common/test/ut/CMakeLists.txt
  sdk/storage/azure-storage-common/test/ut/structured_message_test.cpp
Labels: Storage

#6425 fix certs and missing include
  sdk/core/azure-core/test/ut/logging_test.cpp
  sdk/keyvault/azure-security-keyvault-certificates/samples/certificate-import-certificate/certificate_import_certificate.cpp
Labels: Azure.Core, KeyVault

#6428 Sync eng/common directory with azure-sdk-tools for PR 9862
  eng/common/scripts/Helpers/Package-Helpers.ps1
  eng/common/scripts/Package-Properties.ps1
Labels: EngSys, Central-EngSys

#6430 Sync eng/common directory with azure-sdk-tools for PR 9896
  eng/common/scripts/Package-Properties.ps1
Labels: EngSys, Central-EngSys

#6429 Sync eng/common directory with azure-sdk-tools for PR 9889
  eng/common/scripts/Verify-Links.ps1
Labels: EngSys, Central-EngSys

#6431 Sync eng/common directory with azure-sdk-tools for PR 9895
  eng/common/pipelines/templates/steps/detect-api-changes.yml
  eng/common/scripts/Detect-Api-Changes.ps1
Labels: EngSys, Central-EngSys

#6432 Sync eng/common directory with azure-sdk-tools for PR 9901
  eng/common/testproxy/target_version.txt
Labels: EngSys, Central-EngSys

#6426 Identity: Log Client ID used in ManagedIdentityCredential
  sdk/identity/azure-identity/CHANGELOG.md
  sdk/identity/azure-identity/src/managed_identity_source.cpp
  sdk/identity/azure-identity/src/private/managed_identity_source.hpp
  sdk/identity/azure-identity/test/ut/managed_identity_credential_test.cpp
Labels: Azure.Identity, Managed Identity

#6433 Sync eng/common directory with azure-sdk-tools for PR 9902
  eng/common/scripts/Package-Properties.ps1
Labels: EngSys, Central-EngSys

#6435 Remove impressions pixel from Markdown files
  README.md
  sdk/attestation/azure-security-attestation/README.md
  sdk/core/azure-core-amqp/README.md
  sdk/core/azure-core-tracing-opentelemetry/README.md
  sdk/eventhubs/azure-messaging-eventhubs-checkpointstore-blob/README.md
  sdk/eventhubs/azure-messaging-eventhubs/README.md
Labels: Azure.Core, Attestation, Event Hubs

#6436 Sync eng/common directory with azure-sdk-tools for PR 9921
  eng/common/scripts/Package-Properties.ps1
Labels: EngSys, Central-EngSys

#6434 Sync eng/common directory with azure-sdk-tools for PR 9888
  eng/common/scripts/Helpers/PSModule-Helpers.ps1
  eng/common/scripts/stress-testing/deploy-stress-tests.ps1
  eng/common/scripts/stress-testing/stress-test-deployment-lib.ps1
Labels: EngSys, Central-EngSys

#6437 Sync eng/common directory with azure-sdk-tools for PR 9917
  eng/common/pipelines/templates/steps/detect-api-changes.yml
Labels: EngSys, Central-EngSys
